== Chapter I.

[.chapter-synopsis]
* His early sense of the impressions of divine love, and spiritual conflicts in his youth
* Death of his father
* His marriage
* The settlement of a monthly meeting at Nottingham
* His joining with other Friends in visiting families
* Appointed an elder, and first appearance in the ministry, etc.

I was born in the township of Nottingham, in the county of Chester,
and province of Pennsylvania, on the 4th day of the sixth month, 1705,
and was tenderly brought up in the profession of the truth.
My parents, John and Hannah Churchman, were diligent attenders of religious meetings,
both on the first and other days of the week,
and encouragers of their children in that practice, which is certainly a duty in parents,
and often owned by the visitations of divine love,
even to those who are very young in years, of which I am a living witness.
I early felt reproof for bad words and actions, yet knew not from where it came,
until about the age of eight years, as I sat in a small meeting,
the Lord by his heavenly love and goodness, overcame and tendered my heart,
and by his glorious light discovered to me the knowledge of himself.

I saw myself and what I had been doing, and what it was which had reproved me for evil,
and was made in the secret of my heart to confess that childhood and youth,
and the foolish actions and words to which they are prepense, are truly vanity.
Yet blessed forever be the name of the Lord! in his
infinite mercy and goodness he clearly informed me,
that if I would mind the discoveries of his pure light for the future,
what I had done in the time of my ignorance, he would wink at and forgive;
and the stream of love which filled my heart with solid joy at that time,
and lasted for many days, is beyond all expression.

I was early taught to think differently from such who hold the perdition of infants,
and am since confirmed in believing that the sin
of our first parents is not imputed to us,
though as their offspring, we are by nature prone to evil, which brings wrath,
until by the discovery of light and grace,
we are taught to distinguish between good and evil,
and in that divine light which shows the evil,
we feel the enmity against the evil and the author thereof, the wicked one.
If we afterwards commit those things which we saw to be evil,
we then fall under condemnation and wrath, and here every soul that sins,
must die to the sin he has committed, and witness a being raised by the power of God,
into newness of life in Christ Jesus, not to live to himself,
to fulfill the will of the flesh; but to live unto Him who died to take away sin.

My father sent me about three miles from home on an errand; and on my return,
the colt which accompanied the mare I rode, ran away to a company of wild horses,
which were feeding not far from the path I was in.
My father bid me go back to the place with speed, that it might follow the mare home.
I went,
and found the horses feeding on a piece of ground where the
timber trees had been killed perhaps about two or three years.
Before I went among the dead trees, a mighty wind arose, which blew some down,
and many limbs flew about.
I stood still with my mind turned inward to the Lord,
who I believed was able to preserve me from hurt;
and passed among the trees without fear, save the fear of the Lord,
which fills the hearts of his humble depending
children with love that is stronger than death.
I found the colt,
and returned home with great bowedness of heart and thankfulness to the Lord,
for his mercy and goodness to me.

It was my practice, when I went to bed, to examine how I had spent the past day,
and to endeavour to feel the presence of the Lord near,
which for some considerable time I preferred to all other things,
and I found this practice a great help to sleep sweetly,
and by long experience I can recommend it to children, and those also of riper age.

I suppose that no one living knew my condition; for I delighted to keep hidden,
yet was quick to observe the conduct of others.
I remember a person was once at my father`'s,
who spoke about religious matters with an affected tone, as if he was a good man;
and when he mounted his horse to go away, taking a dislike to some of his motions,
he called him an ugly dumb beast, with an accent which bespoke great displeasure,
and grieved me much.
I believed that a man whose mind was sweetened with divine love,
would not speak wrathfully, or diminutively, even of the beasts of the field,
which were given to man for his use;
and I relate this instance as a warning to be
careful of giving offence to the little ones.

Notwithstanding I had been favoured as before mentioned, yet as I grew in years,
I was much given to play, and began to delight again in several things,
for which I had before been reproved,
and by the divine witness in my mind was still brought under judgment for;
but having lost my innocence,
I endeavoured through fear to fly from the voice of the holy Spirit in my own heart.
The enemy persuaded me, that I could never be restored to my former state,
because I had sinned against so great knowledge, or if I was,
that the judgment through which I must pass, would be intolerable,
so that I had better be cheerful, and take my ease and delight.
When I was about nine years old, my father sent me to school to learn to read,
having been taught to know my letters and spell a little at home,
in which I took great delight,
and thereby diverted myself from feeling pain of mind for the
great loss of my innocence which I had sustained.
Although the man by whom I was taught, was poor and sat in his loom, being a weaver,
while the children read to him, I improved very fast, and he soon put me to writing,
and finding my capacity as ripe as is common in boys of that age,
he began to teach me arithmetic.
But my gracious Lord still favoured me with conviction,
his spirit bearing witness against me,
and in mercy he visited me with a sore fit of sickness,
and by his rod of correction brought me a little more to myself.
This was in the forepart of the winter, when I was between nine and ten years of age,
and in the following spring I had a relapse of the same disorder.
Thus by outward correction with sickness and inward judgment,
he was pleased to draw me to himself, which caused me to renew my covenant with him,
and I hoped never more to stray from him to follow lying vanities,
whose sweets I had experienced to be exceeding bitterness in the end.
I had taken great delight from a child to play with whistles and pipes,
made of the bark of small branches of trees, and of straws of wheat and rye;
but now it grieved me to observe children delight therein,
and I ventured to tell my mind to some of them concerning such things.

Man is distinguished from other creatures by his voice;
and by varying the breath together with the orderly motion of tongue and lips,
that voice is made to convey the ideas of the mind and
thoughts of the heart to his fellow creatures.
As he was created to glorify his Maker,
the use of his voice should be directed to promote his glory among men,
whether in things natural or spiritual, that is of this life, or that which is to come.
Music as now commonly used, and whistling and singing, have no such tendency;
but rather divert the mind from what it ought to be employed about,
and are therefore a waste of precious time, for which man must be accountable.
If this were enough regarded, instead of music, whistling, and singing merry,
foolish and profane songs,
many would have occasion to lament and weep for their misspent time.
I leave this as a caution to parents,
to beware of indulging their dear children in anything which
may impress their tender minds with a desire after music,
or other improper diversions; but that instead thereof,
by living in the pure fear of the Lord, and near the Spirit of truth in their own hearts,
they may by example and precept,
direct the minds of their offspring to attend to the
voice of Him who called to Samuel in days of old,
and remains to be the Teacher of his people in this age;
may his holy name be magnified forever and ever!

I retained my care and circumspection for some time;
but through unwatchfulness and a desire for play,
which led into lightness and forgetfulness,
I lost this state before I was twelve years of age; and though the Lord was near,
and followed me by his reproof, in order to bring me under judgment,
I fled from it as much as I could.
I let in a belief, that as I had been favoured to taste in so wonderful a manner,
"`of the good word of life, and powers of the world to come,
and had so shamefully fallen away, there remained for me no more sacrifice for sin;
but a fearful looking for of judgment, and fiery indignation,`" which as I thought,
burned in me to that degree that I was afraid to be alone,
for it seemed to be loudly proclaimed in me, that whether I ate, or drank, waked,
or slept, I was accursed.
When alone, I abhorred myself; but when in company,
I used my utmost endeavours to hide my condition
by being cheerful and arch in my discourse,
and was thought by most young people to have a knack, as they called it,
at jesting and witty turns; yet even in this time,
I entertained such a value for religion, that I was not willing to disclose my situation,
lest I should be a reproach thereto, or discourage others from seeking happiness.
When night came and I went to bed, no tongue can express the anguish I felt.
I was afraid to lay awake, and afraid to desire sleep,
lest I should be cut off from the land of the living,
and my portion appointed in utter darkness.
I so far neglected my learning, that when about thirteen years old,
I could read but poorly, though once a ready reader.
I was not willing that good Friends should take notice of me,
or look me steadily in the face; for I thought they would discern my wickedness,
and it would be a trouble to them, or their reproving me would add to my distress.
I seemed to be left without any power to resist what I knew to be evil,
and being ashamed that I had so lost my little learning,
I sought to divert myself by endeavouring to regain it.
My former genius and delight returned, and when about fifteen years of age,
I had made great improvement, not only in reading, but in writing, arithmetic,
and several branches of the mathematics, and began to value myself thereon,
and so got over the convictions of the divine Witness, which spoke trouble in me.
During this time I was diligent in attending meetings,
hoping at seasons that the Lord would condescend once more to visit me;
for a saying of an eminently pious man was revived in my remembrance,
"`That if there remained a desire in the heart after redemption, as it was kept to,
the Lord would again assuredly visit such in his own time.`"

I was therefore fearful of neglecting meetings,
lest I might miss of the good intended for me;
yet the subtle working of the power of darkness was very great,
suggesting to me that all things came by nature, and that there was no God, no heaven,
no devil, no punishment for evil, religion a jest,
and painful care about futurity a silly whim, propagated to deprive people of pleasure.
But blessed be the Lord! he preserved me from this snare;
for while I felt his judgments for sin, I believed in his being and holiness;
and I am indeed fully of the mind,
that no man can be an atheist before he acts contrary to knowledge, when,
to allay the horror and anguish of mind he feels for the commission of sin,
he closes in with this temptation.
At other times, the same subtle power would tempt me to despair of mercy, which,
if given way to, would lead to distraction; but the hand of the Lord was underneath,
though for my disobedience he allowed me to remain in
the wilderness and to dwell as among fiery serpents,
until he had wasted that disposition in me which lusted after forbidden things.

In this state I continued until I was about nineteen years of age,
and as I was one day walking to meeting, thinking on my forlorn condition,
and remembering the bread in my heavenly Father`'s house,
of which I had partaken when I was a dutiful child, and that by straying from him,
and spending my portion, I had been eight years in grievous need, I inwardly cried,
if you are pleased again to visit me, I beseech you O Lord, visit my body with sickness,
or pain, or whatever you may please, so that the will of the old man may be slain,
and everything in me that your controversy is against,
that I may be made a sanctified vessel by your power; spare only my life,
until my redemption is wrought, and my peace made with you!

About this time, in the tenth month, 1724, my father died,
which was a great loss to our whole family;
and as he had allotted me to live with and take care of my mother,
it became my duty to keep mostly at home.
I spent nearly a year in the condition above mentioned;
often out of hope of ever attaining to the state I had witnessed when very young;
but in the fall of the year after I had arrived to the age of twenty years;
it pleased the Lord to remember me, who had been an exile,
in captivity under the old taskmaster in Egypt spiritually,
and by his righteous judgments mixed with unspeakable mercies,
to make way for my deliverance.
I was visited with a sore fit of sickness, which in a few days so fully awakened me,
that I had no hope of being again entrusted with health.
My misspent time, and all my transgressions were brought to my remembrance,
and heavy judgment was upon me for them.
I was met with in this narrow path,
and could no longer fly from God and his spirit in my conscience,
whose sore displeasure I had justly incurred.
I had heard of men who had been notorious offenders,
and fled from the justice of the law, until they became outlawed;
such in a spiritual sense my case appeared to be.
I thought I had, as it were, heard an act of grace and free pardon repeatedly proclaimed,
if I would return and live uprightly for the future; but in the time of such visitations,
I concluded it was only to bring me under judgment and to take me from my pleasure,
for that my offences would never be pardoned, and so I had withstood,
or neglected those visitations.
I now saw clearly, that herein I had followed the lying suggestions of Satan, my enemy.

At this time my old will in the fallen nature gave up its life, and I cried,
"`I am not worthy to live or enjoy your favour,
yet Oh Lord! if you will be pleased to look on me with an eye of pity,
do what you will with me, magnify your own name,
prepare me by your judgments and power that your mercy may be shown in and by me,
whether you cut the thread of my life, or shall grant me more days,
which is only in your power.`"
My heart was made exceedingly tender, I wept much, and an evidence was given me,
that the Lord had heard my cry, and in mercy looked down on me from his holy habitation,
and a willing heart was given me and patience to bear
his chastisements and the working of his eternal Word,
which created all things at the beginning,
and by which only poor fallen man is created anew in the
heavenly image and prepared to praise him with acceptance,
who lives forever and ever.

While I lay in this condition I said little or nothing, but was quite sensible,
yet exceedingly weakened,
having for about twenty-four hours felt more inward and inexpressible anguish,
than outward pain.
Toward the morning of the fifth day and night of my illness,
I felt the incomes and owning of divine love in a greater degree than ever;
for the prospect I had of so great forgiveness made me love the more,
for love is ever reciprocal.
I saw the morning light and thought all things looked new and sweet.
I lay where the sun shone near, or on my bed, and have sometimes since thought,
that being weak, the strength of the light and too much company hurt me.
I leave this hint to excite nurses and those who
have the care of very weak indisposed people,
to beware of letting over much light come upon them, or many visitors,
except they be such who are sensible of the weak by being inward and quiet,
waiting to feel the sympathy which truth gives,
the company of such being truly refreshing.

It pleased the Lord to restore me so that I recovered my usual strength,
and was frequently humbled under a sense of the tender dealings of a merciful God,
whose goodness and owning love I felt to be very near.
I then loved retirement and to feel after the incomes of life,
and was often fearful lest I should again fall away.
In this time it was manifested to me, that if in patience I stood faithful,
I should be called to the work of the ministry.
I loved to attend religious meetings, especially those for discipline,
and it was clearly shown me,
that all who attend those meetings should wait in great awfulness,
to know the immediate presence of Christ, the head of the church,
to give them an understanding what their several services are,
and for ability to answer his requirings,
for it is by his light and spirit that the Lord`'s work is done with acceptance,
and none should presume to speak or act without its motion and direction.
They who act and speak without it, often darken counsel, mislead the weak,
and expose their own folly, to the burden and grief of sensible Friends.
It was in great fear that I attempted to speak in these meetings, and as I kept low,
with an eye single to the honour of truth,
I felt peace and inward strength to increase from time to time.

It is good for all who are concerned to speak to matters in meetings for discipline,
to take heed that their own spirits do not prompt thereto,
and to mind the time when to speak fitly;
for a word in season from a pure heart is precious,
and frequently prevents debates instead of ministering contention,
and when they have spoken to business,
they should turn inward to feel whether the pure truth owns them, and in that rest,
without an over anxious care whether it succeeds at that time or not,
so Friends will be preserved from being lifted up,
because their service is immediately owned; or if it should be rejected or slighted,
in this inward humble state, the labour is felt to be the Lord`'s.

It is a great favour that the Lord is pleased to cover his children with his pure fear,
and to array their souls with the garment of humility,
that they may stand in his presence with acceptance, waiting to be taught of his ways,
and in meekness to be guided in judgment.
These feel the necessity of minding that excellent exhortation, "`Be steadfast,
immovable, always abounding in the work of the Lord.`"
In a degree of reverent thankfulness,
I bless the name of the Lord through his beloved Son,
that according to my measure I knew what I now write; it was a time of growing with me,
I rarely passed a day without feeling the incomes of divine life,
and was favoured strongly to desire the sincere milk of the holy word,
that in humility I might thereby grow in substance.
But afterwards I was left for many days together, without inward refreshment,
and was ready to fear that I had offended my gracious Redeemer;
and being thoughtful and inwardly engaged to know the cause,
I had to consider that children, though they may be thriving,
and darlings of their natural parents,
are not fit for much business until they are weaned; and although they grow finely,
they are gradually taught to wait the appointed time between meals,
before they have much care of their father`'s business, and are further prepared,
so as to miss a set meal, or be a longer time without outward food,
before they are fit for a journey.
With these thoughts a hope began to revive in me, that I was not forsaken,
of which indeed, as I kept patient, I was at times abundantly sensible,
even those times which are in the Lord`'s hand;
for his children experience that the times of refreshment come from him,
who when he has exercised and proved them,
in his infinite kindness is pleased to cause them to sit down,
and condescends himself to serve them.
Blessed forever be the name of the Lord who knows how
to prepare his soldiers to remain faithful,
and endure with patience what the natural man would account hardness!

I had strong desires that elderly Friends should be good examples to the youth,
not only in word and conduct, but in meetings for the worship of God,
and it grieved me exceedingly to see any of them overcome with sleep.
My concern for one Friend was so great on that account,
that I knew not what was best to do; and reasoned after this manner;
Lord! you know that I am young, and he an elderly man,
he will not take it well that I should speak to him, and perhaps I may yet fall;
and if so, the more I take upon me, the greater my fall will be; besides,
though I have spoken in meetings for discipline, when truth has been strong upon me,
yet out of meetings, I am not fit to reprove, or speak to particulars.
I was cautious indeed in those days, of talking about religion, or good things,
from a fear I should get a habit thereof, and so not know the true motion;
which I thought I had observed to be the failing of some.
In this strait it came into my mind to go to the person in the night,
as the most private time and manner; for if I took him aside before or after a meeting,
others might wonder for what, and I might betray my weakness and reproach the good cause,
and do no good, and if the Friend should be displeased with me, he might publicly show,
what otherwise he would conceal after private deliberation.

So in the evening I went, desiring the Lord to go with and guide me,
if it was a motion from him.
When I came to the house, I called, and the Friend came out to see who was there,
and invited me in.
I told him I was in haste to go home, but wanted to speak with him if he pleased,
and so passed quietly toward home, to draw him from the door,
and then told him my concern for him in a close, honest, plain manner;
and without staying to reason much, left him in a tender loving disposition,
as I believe, and returned home with great peace.
When you do or give alms, let not your left hand know what your right does,
is an excellent precept.
The left hand of self should not act in such things;
no matter how privately they are done, they often answer the end better;
neither is it a fault to lay things low and familiar, the truth will have its own weight,
and accompany what it dictates with its own evidence.
My intention in writing this,
is to encourage the humble careful traveller in the way of his duty.
Sometimes it appeared to be likely to do most good to write my mind,
which I did with success,
as I aimed only at a discharge of duty in the most private manner,
and the good of those to whom I wrote.

In the twenty-fifth year of my age, I married Margaret Brown, a virtuous young woman,
whom I had loved as a sister for several years, because I believed she loved religion.
I think I may say safely, it was in a good degree of the Lord`'s pure fear,
and a sense of the pointings of truth, on both sides,
that we took each other on the 27th day of the eleventh month, 1729, old style,
in an appointed meeting at East Nottingham,
and I thought that our heavenly Father owned us with his presence.
The covenants made in marriage are exceedingly great,
and I think they never can be truly performed without divine assistance;
and if all who enter into a marriage state, would in the Lord`'s fear seek his assistance,
they would know their own tempers kept down, and instead of jarring and discord,
unity of spirit, harmony of conduct,
and a concern to be exemplary to their offspring would increase and be maintained.

In the year 1730,
a monthly meeting was settled at Nottingham by the advice of the quarterly meeting,
it being before a branch of New Garden monthly meeting.
This brought a weighty concern upon me and many others,
that the affairs of truth might be managed to the honour thereof;
for we had but few substantial elderly Friends.
In a sense of our weakness,
it was the breathing desire of my soul that the Lord would be pleased for his own sake,
and the honour of his great name,
to be near his children and inspire them with wisdom and judgment for his own work.
Blessed forever be his holy name!
I believe he heard our cry, and in measure answered our prayers;
and we being kept low and humble, it was a growing time to several.
My affection to Friends of New Garden monthly meeting was so great,
that for many months after we parted from them, I seldom missed attending it,
and therein had great satisfaction, and some of their members frequently attended ours,
for our love towards each other was mutual.

When I was about twenty-six years of age,
some Friends were appointed to perform a family visit, and being desirous of my company,
I joined with them, and therein felt the ownings of truth in some degree.
But notwithstanding I saw at times the states of families and particulars,
yet not in so clear a manner as I thought necessary to
make it my duty to open my mouth in the service,
save now and then, in a private way to particulars,
of which none knew except those to whom I spoke.
At one house the Friends on the service had a good opportunity, several young folks,
some of whom were not of the family, being present.
I felt the Divine presence to be very near,
and a motion to conclude that sitting in supplication and thanksgiving to the Lord,
but was not hasty, for fear of doing what was not required of me, so omitted it,
and afterwards asked an experienced worthy minister,
if he had ever known any Friend appear in a meeting in public prayer,
before he had appeared in public testimony;
which inquiry I made in such a manner as to give him no mistrust of me; he answered.
"`no, I believe it would be very uncommon.`"
It struck me pretty closely, but I kept my condition very private;
having been exceedingly fearful of deception,
and now began to doubt whether it was not a delusion for me to entertain an
apprehension that I should be called to the work of the ministry;
the concern whereof had been at times very heavy upon me;
though no motion that felt like a gentle command to break silence,
until at the house before mentioned.
I let in reasoning, and so departed for a time from my inward guide and safe counsellor,
as all assuredly will, who place their dependence on man for instruction,
to perform duties required of them; or who forbear, or reason against the humbling,
gentle motions, and leadings of the Spirit of Truth.
Our only safety is in attending steadily thereto for
instruction and ability to perform religious services,
and when performed,
we ought to be tender of the sentiments of our brethren concerning them,
and not over confident of our call and commission;
for our brethren have a measure of the same spirit by which we are taught,
and have a sense and right thereby given to judge of our service.
A becoming diffidence of ourselves, and a readiness to attend to the advice of such,
is the badge of true discipleship;
divine love teaches us to esteem others rather than ourselves.

This was an exercising time to me, but I did not discover it to anyone.
I seemed to be forsaken, though not sensible of much judgment for my omission of duty,
for I could with sincerity appeal to Him who knows all things,
that it did not proceed from willful disobedience, but a fear of following a wrong spirit,
and a secret hope revived that my gracious Lord and master would not cast me off,
and blessed be his holy name! he did not leave
me very long before I was favoured as usual,
but had no motion of the same kind.

When this visit was over, I kept much at home,
yet was careful to attend meetings on the first and other days of the week,
and found work enough to watch against a lukewarm, indolent spirit,
which would come over me when I sat down to wait upon God.
Though I came to the meeting in a lively engagement of mind,
I found the warfare against lukewarmness, sleepiness, and a roving mind,
must be steadily maintained, and if none of these hinderances were given way to,
the Lord when he had proved his children, would arise for their help,
and scatter his and their enemies,
which my soul experienced many times beyond expression.
The Lord alone is all powerful,
and worthy to be waited upon and worshipped in
humility and reverent adoration of soul forever.
Indolence and lukewarmness bring darkness and death over a meeting,
and when generally given way to,
occasion hard work for even the most livingly exercised
Friends to get from under the burden thereof.
It was a mercy that I was preserved seeking,
and could not be satisfied without feeling the renewings of divine favour,
by which I grew in the root of religion, though I thought very slowly,
but had a hope it would be lasting.

The love of truth and a desire that the discipline and
good order of the church might be maintained,
made me willing to take considerable pains to attend neighbouring monthly meetings,
which I think was a blessing to me, being often instructed.
I have often admired at the slackness of some,
who allow trifling things to keep them from their
meetings for worship on week-days and first-days;
and though curiosity brings such to monthly meetings,
they are seldom of any real service when they come,
not being sensible of that divine love,
in which the church through its several members edifies itself.
As any become truly sensible of this,
they will delight to meet with their brethren and sisters to wait upon God,
who is the fountain of pure love, and so fills the hearts of his humble,
depending children therewith, that by it, they are known to be his disciples.

In the year 1731, our ancient and worthy Friend William Brown,
who had been in the station of an elder many years, grew feeble,
and incapable of attending the quarterly meeting of ministers and elders.
Friends of our particular meeting proposed me to the monthly meeting for that service,
which brought a close exercise upon me, considering myself a youth,
and the weight of the service; but after a solid consideration,
I found most peace in submitting to the meeting,
with fervent inward desires that the Lord would be pleased to be with me therein,
to preserve me from acting, or judging in my own will and spirit,
knowing that the service could not be performed but by wisdom, understanding,
and ability from him.
When I attended those large and weighty meetings of ministers and elders,
the care and fear that was upon me is not easily expressed;
and may I never forget the gracious condescension of kind providence,
who was pleased to own me, by the shedding abroad of his love in my heart.
I verily thought they resembled the school of the prophets, the High Priest,
great Prophet and Bishop of souls, our Lord Jesus Christ being President among them.

An apprehension that I should be called to the ministry, and a concern on that account,
had been at times, for several years, weightily on my mind;
but I now again thought I was mistaken in that belief,
and that it was only a preparative to qualify me for the station of an elder,
and thereby my exercise became somewhat lighter for a time.
The tenderness and love I felt to those engaged in public ministry, was very great,
and I believe I was made helpful to some by giving private hints,
where I thought there was occasion, in plainness, simplicity and fear,
which often afforded instruction to myself as well as to them.

In 1733 I accompanied Friends on another visit to families, wherein, at times,
I felt the opening of truth in the love of it,
and a few words to speak to the states of some, though in great fear,
lest I should put my hand to that weighty work without the real requiring of duty.
At one family, I thought it would be better for the whole family, in a religious sense,
if the heads of it were more zealous in attending meetings.
I saw the necessity of being examples to children and servants,
by a careful attendance of meetings for worship on the first, and other days of the week;
but I was so weak and poor,
that I doubted whether it was my duty to mention anything thereof to them,
so concluded to omit it; by which I hoped to judge of what I had been about before,
and so grew easy in my mind.

On the way to the next house,
I began to judge that I had no business to say anything at any house;
and having forborne in my own will, I was now left to my own judgment for a time.
At the next house, Friends were tenderly concerned to speak to several states,
and of several matters which I thought instructive; but I sat dry and poor,
and so remained during our passage to the next house; where I fared no better, but worse.
My feeling and judgment being quite gone, as to the service in which we were engaged;
and though I did not say anything to the other Friends how it fared with me,
yet they were affected therewith as I apprehended.
I was in great darkness and distress,
and sometimes thought of leaving the company privately, and going home, but concluded,
that would not only be a disappointment to my friends, but dishonourable to truth,
which made me determine to go forward, and endure my own pain,
as much undiscovered as possible.
My companions, as I before observed, were affected,
and all save one seemed closed up from the service,
and in the evening of the same day at the last house, all of them were silent.
There was a school near, the master of which was a Friend,
and the children mostly belonging to Friends,
whom some of our company appeared willing to visit, but others being doubtful,
we omitted it, which now some thought was not right,
and that therefore this cloud of darkness and distress came upon us,
and we were willing to meet at the schoolhouse next morning,
to try if we could recover our former strength in the ownings of truth.
This being agreed to, each took his way home, and it being now night, and I alone,
I rode slowly, under a deep exercise of mind,
and humble inquiry into the cause of my own distress; and after some time,
being favoured with great calmness and quietude of mind,
I was inwardly instructed after this manner;
You saw what was needed in a family this morning,
and would not exhort to more diligence in that respect,
and therefore if they continue to do wrong, it shall be required of you;
on which I became broken in spirit, and cried in secret, may I not perform it yet,
and be restored to your favour?
Oh Lord!
I am now willing to do whatsoever you require of me,
if you will be pleased to be with me.
Blessed be his name, in mercy he heard my supplication,
and I was fully persuaded that I must go to the house again;
which I concluded to do next morning, and went home with a degree of comfort,
and being weary in body and mind, slept sweetly,
and awoke in the morning quiet and easy in spirit,
and now began to conclude that I might meet my company and be excused.
But my covenant was brought to my remembrance, and I was given to believe,
that peace was restored on condition of my performance; therefore I went to the house,
though several miles distant, before sun-rise, the man of the house was up,
he invited me in, and I followed him, and sitting down by the fire, being cool weather,
with my mind retired, I felt that I must not speak before the rest of the family,
but rather in private, yet was fearful of calling him out,
being unwilling to discover anything to them.
In the mean time, he went out, and walked the way I was to go, I followed,
and told him how I felt when we were at his house the morning before,
and could not be easy without exhorting him to be more careful in several respects,
and a better example to his family in his attendance of meetings.
He seemed affected, and said he hoped he should mind my advice.
I then left him, and met my companions at the schoolhouse, and enjoyed great peace.
I leave this remark, to excite all to dwell in meekness and fear,
and to beware of the will of the creature, and the reasonings of flesh and blood,
which lead into doubting and disobedience.
They who are faithful in small things,
shall truly know an increase in that wisdom and knowledge which are from above.

Before we had gone through this visit,
I attended the quarterly meeting of ministers and elders at Concord,
and as I sat therein, the unwearied adversary renewed a former charge against me,
by suggesting to my mind, that I might know I had been wrong and under a delusion,
in entertaining a belief I should be called to the work of the ministry;
for that all who had ever been rightly engaged therein,
it was greatly in the cross to the will of the creature, which was not my case,
for I was willing.
This I felt to be true, and was exceedingly distressed,
not considering that I was made willing by the weight of the exercise,
which had been several years at times very heavy upon me,
until it seemed as a fire in my bones, and as though I was dumb with silence,
I held my peace even from good, and my sorrow was stirred, my heart was hot within me,
while I was musing the fire burned.
While under this conflict, a Friend stood up with these words,
"`Also I heard the voice of the Lord, saying, whom shall we send,
and who will go for us?
Then said I, here am I, send me.`"
Showing, that "`to them whose will was rightly subjected to the Lord,
it became their meat and drink,
to do the will of him who had subjected them by his divine power,
and influenced their hearts with his love to mankind;`" by which I was relieved,
and my spirit humbled and made thankful.

Next morning being the first-day of the week, I went to Kennet meeting,
and toward the close thereof, something appeared to my mind to offer,
but I was fearful that the motion for speaking was not enough powerful,
and had like to have forborne,
but remembering what I had suffered by neglecting a weak motion in a family visit,
as already related, I stood up,
and spoke a few sentences in great fear and brokenness of spirit,
and had solid satisfaction.
I attended the quarterly meeting of business at Concord on second-day;
on my return from which, I let in the old reasoner, who suggested to me,
that if I was called to the public ministry,
I had not waited for a sufficient commission to speak;
for some had been raised up with great power, and an authority they could not withstand,
but that I might have been still and quiet, the motion was so gentle and low,
and that I must not think to speak in public testimony
in great meetings with so small a motion,
and in so doing, I had committed a sin that would not be readily forgiven,
perhaps a sin against the Holy Spirit.
My exercise was great, but as I endeavoured to be quiet in my mind,
seeking to know the truth of my present condition,
I was secretly drawn to attend to something that spoke inwardly after this manner,
"`if you were to take a lad, an entire stranger to your language and business,
however likely he appeared for service, you must speak loud and distinctly to him,
and perhaps with an accent or tone, that might show you to be in earnest,
to engage his attention, and point out the business;
but you would expect it should be otherwise with a child brought up in your house,
who knew your language, and with whom you had been familiar.
You would expect him to wait by you, and watch your motions,
so as to be instructed by your eye looking upon him, or pointing your finger,
and would rebuke or correct such a one,
if he did not obey your will on such a small intelligent information.`"
I was instantly relieved thereby, believing it to be from the Spirit of Truth,
that is to lead and guide into all truth.

When this meeting was over, being in the ninth month, 1733,
we proceeded to finish our family visit.
The part which remained was on the west side of the Susquehanna, at Bush River,
and a few families settled near Deer Creek.
We were remarkably favoured with the presence of our great and good Master,
who opened the states of families to us, and gave ability to speak thereto;
may his holy name be praised.
The visit being finished, we returned home, and in a short time after,
as I sat in a week-day meeting, I had a few words fresh before me,
with a gentle motion to deliver them, which I feared to omit,
still remembering what followed a former neglect; so I expressed what was on my mind,
and therein had peace, and afterwards was silent for several weeks,
in which time I let in a fear that I was forsaken by my dear Lord and Master,
whom I loved above all things, for I had no openings in heavenly things, as I thought,
but was left poor and needy, yet I loved Friends,
and remembering a saying of a minister formerly,
"`We know that we have passed from death unto life,
because we love the brethren;`" I hoped that I was not quite forgotten.
Some remarkable sentences had fixed in my mind sometime before,
which I now began to understand more sensibly; "`ministry should be of necessity,
and not of choice, and there is no living by silence,
or by preaching merely;`" for something in me was ready to wish to be employed,
that I might have bread, for when I found a motion to speak,
I had the owning love of the heavenly Father;
which is and ever will be bread to his children.
The creaturely will, would choose and would be busy with questioning,
may it not be so and so; this is that womanish part,
which is not permitted to speak in the church: it runs first into transgression,
for lack of learning of the husband at home, or being in subjection to him,
which if Eve had literally done, instead of reasoning with the serpent that tempted,
she might have been preserved from being a tempter.
Our strength, preservation,
health and peace stand in our entire subjection to the will of the Lord,
whether in silence or speaking, suffering or reigning, still dwelling with the seed,
Christ, in our own hearts; humbly waiting for, and feeling after his power,
who is the resurrection and the life, and when he is pleased to appear,
his children partake in measure of his glory!

I continued in the station of an elder,
and sometimes delivered a few sentences in public testimony,
which occasioned me to apprehend I should not be in my proper place,
except I requested to be released from my eldership.
After a time of weighty consideration,
I modestly requested that Friends would consider my case,
for instead of taking care of the ministry of others,
I stood in need of the care of my friends, and that it would be relieving to my mind,
if they would nominate an elder in my room,
which was taken into consideration for a time; Friends waiting, I suppose,
to see what proof I should make of my ministry.
I attended the winter quarterly meeting of ministers and elders,
and had to give an account of the ministry at our meeting,
the elders being called to answer one after another in order,
according to the meetings they belonged to;
a fear struck me lest a form of words was too much in general observed, particularly,
"`that the ministry was well received.`"
When my turn came, I could not be easy without varying that part, and instead of saying,
the ministry is well received,
I said that I believed the ministry of the public Friends was generally approved of,
and added,
that I wished the ministry of all the ministering
Friends was better received than I conceived it was.
I was asked what I meant, and under the weight I felt on my mind, I replied,
that it was not from a thought of bearing hard on the service of public Friends;
but from the difference between approving thereof, because they believed it to be right,
and attending no further to it, which would not do the work,
but to put in practice what they heard recommended,
was the only way of receiving it well, and if that was really the case,
our Society would appear more beautiful than at present; thus the matter closed,
and I had peace in the remark.
I think this was the last meeting I attended as an elder;
before the next quarterly meeting in the second month, 1734,
another was recommended in my place.

About this time, as I sat in one of our own meetings,
I felt a flow of affection to the people, for many not of our Society came there,
perhaps out of curiosity, several young ministers having come forth in public testimony;
in which extraordinary flow of affection, I had a very bright opening as I thought,
and expected to stand up with it very soon,
but being willing to weigh it carefully was not very forward,
viewing its decreasing brightness, until something said as it were within me,
"`Is the woe in it?
Is necessity laid upon you, and therefore woe if you preach not the gospel?`"
This put me to a stand, and made me feel after the living presence of Him,
in whose name and power I desired to speak, if I appeared in testimony;
and not feeling the pure life and power of Truth, so as to stand up,
the brightness of the vision faded, and left me quiet, humble,
and thankful for this preservation.
The drawing strength and lusting desire of the unstable,
who centre not to the pure gift in themselves, are as the many waters,
or sea of mystery Babylon, for her merchants to sail their ships and trade upon.
This was a time of inward growing to me,
the welfare of the churches was strongly desired,
and the extendings of the love of the heavenly Father,
I felt at times to reach over sea and land, to my great admiration;
but although my heart was enlarged, I believed it was my duty to retire inward,
and wait with patience until my friends should so approve of my ministry,
as to recommend me as a minister, before I made any request to go abroad;
though I went to some neighbouring meetings,
such as I could go to in a morning and return home at night,
but not without acquainting some elderly Friends therewith and desiring their company,
which I generally had.

In the winter 1735-6, William Brown, my brother-in-law, my sister Dinah Brown,
then a widow, and myself, were all recommended to the meeting of ministers and elders,
as ministers.
At this meeting I informed a Friend that for sometime I
had had a desire to visit Friends at Newtown,
Middletown, Goshen, Cain, and Bradford meetings, hoping that he would go with me.
I was not easy to go without a suitable companion,
because it would be necessary that notice should be given to answer the end of a visit;
which he approved, and let me know that he would take the needful care,
which I supposed was previously to inform some Friends of each meeting,
in order that they might acquaint their neighbours if they had freedom.
I was easy, not knowing but he would bear me company.

On third-day I was at the general meeting of worship held at Providence,
and at the breaking up thereof, the Friend to whom I had spoken,
stood up and gave public notice that I intended
to sit with Friends at the aforesaid meetings,
naming the days in order, and requested Friends would take proper care to give notice;
at which I was exceedingly surprised, and repented that I had spoken thereof.
I would gladly have ran home but for the fear of bringing reproach on the truth,
and to me it seemed likely this would be the case if I pursued the track laid out for me.
In this strait I was humbled even to weeping;
but a sympathizing experienced Friend came to me, and spoke affectionately,
bidding me not to be cast down,
for it was heard with gladness that it was in my heart to visit those meetings,
and that if I lived and did well, I must meet with greater trials.
I suppose Friends of those meetings knew more of me than I expected,
for I had carefully attended meetings of discipline for several years,
and had sometimes been active therein.
The meetings were generally pretty full, and I believe truth owned my service,
which was to me great cause of thankfulness.
In this little journey Friends were very kind to me,
and I was afraid were too free in manifesting it.
Indeed there are many indulgent nurses, many forward instructors,
but too few fathers in the church,
who having been acquainted with the great Alpha in their tender beginning,
and dwelling in his holy counsel and fear, have the care of the members at heart,
and in the wisdom of truth know how to instruct, advise,
and conduct themselves towards such who are called to
the Lord`'s work according to their several dispositions,
growths, and the gifts received;
in order that they may be preserved growing in and by him, who was their beginning,
and know him to be with them in their conclusion, to be the first and the last,
all in all, the Lord God over all, blessed in himself and in the Son of his love,
our holy High Priest and instructor.
For lack of proper caution, some have valued themselves above what they ought,
and thereby reduced their credit with others.

In the summer following I felt a gentle draft to
visit the meetings in the back parts of Chester,
Philadelphia and Bucks counties, which continuing with me,
and my brother-in-law William Brown, having the like concern,
we acquainted Friends at our monthly meeting, and had their concurrence,
and I believe their good wishes for us.
In the tenth month, 1736, we proceeded, and went to Goshen, Radnor,
to a general meeting at Haverford,
to an evening meeting at a schoolhouse in Upper Merion, and over Schuylkill to Plymouth;
and mostly had good satisfaction, I could see that my brother grew in his gift;
and after one of the meetings a well-meaning Friend told me that I was a seer,
and knew the states of people better than they could inform me,
at which I felt some secret pleasure, yet not without, as I thought, a humble fear,
knowing that flattery or unguarded commendation, if listened to,
is a kind of poison to young ministers,
and sometimes makes them swell beyond the proper size.
At Plymouth I had an open meeting,
and it seemed to me as if what I had to say was received freely by the people,
and after meeting I was filled with joy to such a degree,
that I wept and dropped behind my company, to keep undiscovered.

In going to a Friend`'s house, I prayed that it might be taken from me, for I feared,
that by the natural part in me, it was taken to excess.
Next day we had a small meeting in Job Pugh`'s house,
where I thought I saw the states of particulars very clearly, and had something to say,
which perhaps I delivered in too strong terms,
considering my age and experience in the ministry.
A becoming fear and modesty in expression, are very safe for ministers,
both young and old.
After meeting we went home with Evan Evans, to North Wales,
who conversed but little with us, but was grave and solid,
and therein a good example to me;
for sometimes young ministers hurt themselves by too much talking,
and draw from others of like freedom, things not convenient for them to hear.

The next day we were at North Wales meeting, which was large, being first-day;
my brother, William Brown, appeared in the forepart and had good service;
afterwards I stood up with a large and good opening as I thought, but found hard work,
and soon sat down again without much relief, which being unusual,
I ventured to stand up again, and with a zeal that exceeded my childish knowledge,
laid on some strokes with the strength of the man`'s part,
more than with the humbling power of truth.
If we deliver hard things to the people, we should ever remember,
that we are flesh and blood, and by nature subject to the same frailties;
this would lead us closely to attend to the power,
and to minister only in the ability of truth, in the meekness,
gentleness and wisdom which it inspires.
I soon sat down again, and in a moment felt myself left in great darkness,
and Friends broke up the meeting in a minute or two after,
which I soon thought was rather unkind, as it seemed to show a public dislike,
when a private admonition, which I believed was my due,
would have answered the end better.
But when I knew they held an afternoon meeting,
I judged that I had infringed on the time,
and the weight of the trial settled still deeper on my mind.
In the afternoon I sat silent, and was very much dejected, and my good friend Evan Evans,
an experienced minister and father in the church, bid me be steady and inward,
looking to the Lord who knew how to deal with his children and gently correct,
as well when they went too fast, as too slow.
This fatherly tender hint fully opened my eyes;
for before I was in some doubt wherein I had missed;
I now believed he saw I was too zealous and forward,
and believed also that he had the judgment of truth; this was enough for me;
I abhorred myself, and was in great fear that I should not be forgiven.
Another Friend told me that I only felt an opposing spirit in some,
whose states had been remarkably spoken to by me,
and desired me not to be too much cast down, for I had the mind of truth.
This instead of relieving, rather added to my affliction,
for I saw it would have a tendency, if heeded,
to take me from under the hand of the Lord, which was heavy upon me,
and something in me said, "`Let God be true and every man a liar,
keep to the witness in your own heart, attend to the Spirit of Truth there,
and mind its reproof.`"
Man through natural affection and sympathy may err, and administer false instruction,
but the other proceeds from the God of truth.
I would have given all that I had to be at home,
for I greatly feared that I should bring a reproach on the truth,
the honour whereof was dear to me, I hid my distress as much as possible,
and proceeded to attend meetings with my brother, whom I greatly preferred,
and was afraid to discourage by my complaints.

We were at a meeting at Skippack, and at another at Perkioming, or New Providence,
in each of which I had so much light and understanding as to offer a few words,
but the service lay chiefly on my brother.
From there we went to Oley,
where I had a few things to deliver in a Friend`'s
house in an evening sitting with his family,
which was large.
The Friend in great tenderness observed afterward, that revelation was not ceased,
for their states were very exactly spoken to, at which I marvelled,
for I was greatly reduced,
and thought myself one of the poorest and most
unqualified that ever travelled in that great service,
in which we were now engaged.
This dispensation though sorrowful to wade through,
was very humbling and profitable for me,
who perhaps but a little before was ready to think I knew something about preaching,
but now knew nothing,
that I might more fully understand that he who thinks he knows anything,
knows nothing as he ought to know;`" and that all pure knowledge is
sealed up in Him who is the fountain of wisdom and knowledge,
to be opened only by himself to his dependent children,
by the revelation of his own spirit, when and to whom he pleases.

From hence we went to Maiden Creek and Richland, in Bucks county,
being still low in my mind, yet favoured for a few minutes in meetings,
in which I had a few sentences, and then was closed up again:
I was like one who having learned a few things in literal knowledge,
was again turned back to his beginning.

We went to Plumstead in Bucks county, where I was rather more enlarged, and to Buckmgham,
Wrightstown, Falls, Middletown, Bristol, and over on the ice to Burlington,
in New Jersey, the weather being exceedingly cold,
and came back again on the ice over Delaware the same evening to Bristol,
and from there proceeded to Byberry and Horsham meetings.
By this time I was relieved from the depression of spirit I felt before,
yet was under a humble reverent fear, not forgetting the meeting at North Wales.
I was in some degree again admitted to behold the
lifting up of the heavenly Father`'s countenance,
which makes the solitary rejoice.
From Horsham we went to a meeting appointed at William Hallowell`'s;
the company of the man who undertook to show us the way not being agreeable,
we persuaded him to return, and so were left not knowing the way to the house,
which made me very thoughtful, lest we should miss our way,
and Friends would then be blamed for neglect of duty towards us.
As I was thus pondering in my mind, faith arose, that Providence could direct,
and that moment I saw the track of a man who had crossed the road we were in,
and felt a sudden turn of mind to follow the same, which made me quite easy;
it brought us to a field, where we found the fence down on both sides,
and led to the house where Friends were gathered,
and we were not discovered to be without a guide, for which I was thankful,
believing it to be the secret direction of kind Providence, and not barely chance.
I relate this with a view to excite such who may meet with difficulties,
to rely on Him alone who can show the way, and give faith to follow,
but man must be humble and quiet in mind,
to understand the inward gentle sense that truth favours with:
this small gathering was owned in a good degree with the divine presence.

We passed to Abington, Frankford and Philadelphia; and after visiting those meetings,
turned to Germantown, and so over Schuylkill to Merion meeting,
where we met our worthy friend John Fothergill, who had great and good service therein,
with whom my brother William Brown, returned to Philadelphia to the quarterly meeting,
which began next day.
While he was absent from me I attended Springfield and Newtown meetings,
when he again came to me,
and we attended some other meetings until our quarterly meeting began,
at which was our friend John Cadwalader, from Horsham, who had good service.
After this I returned home and was glad to sit with Friends in our own meeting,
wherein I did not see it my place to say much, but by example to recommend silence.

Early this spring, 1737,
the Lord was pleased to try me with poverty and inward destitution,
which brought me into great searching of heart, and inquiry into the cause,
but could not understand that I had willfully disobeyed,
neither stood convicted in my mind for doing amiss.
But my poverty and inward privation increased, with distress and doubting,
to that degree, that I began to fear I had mistaken error for truth,
and in my own imagination formed a religion,
and for the rebellion of my youth was permitted to go on until now.
All that ever I had done was brought into judgment and reduced to nothing,
and the enemy endeavoured to stir me up to impatience,
and to persuade me that my transgressions would never be forgiven.
Many days of sorrow and nights of sore distress I passed through,
and began to despair of ever beholding the light of the
Heavenly countenance again lifted up towards me.

Towards the last of the third month I went to Sadsbury,
to settle a dispute about the bounds of land,
and having something to do near Samuel Nutt`'s iron works, on French Creek,
as I was going there alone, my inward sorrow and distress being very great,
I thought I would now endeavour to vent it, were it but in mournful groans.
My inward anguish seemed to burn like fire,
but I was instantly stayed from breaking forth, for I was persuaded my grief,
if given way to, would go beyond bounds.
My heart not being tender, I could not weep,
but was brought to a more calm pause than I had known for some time,
and therein was ready to say, can the good hand be still near to stay me!
Oh! that I may have patience given, and resolution strengthened to continue seeking,
and if at last I should perish, that it may be at his footstool.
For a small space I had some hope of again beholding
Him whom my soul once loved above all things;
but in a few miles riding it began to look pleasant to me,
to go into some remote place where I should not be known.
When reflecting thus--what! abandon my acquaintances! violate my marriage covenant,
and leave my nearest connections!
I saw this prospect of pleasure was from the evil one,
and something in me abhorred it as wicked, and as it were closed my eyes therefrom.
That evening I went to the house of a former intimate acquaintance to lodge,
who received me kindly,
and in the evening brought a book containing some astronomical problems,
and began to converse very freely thereon,
supposing it would be pleasant to me as aforetime.
But I was heavy in my spirit and thoughtful about something of another nature,
and he soon perceiving his conversation on that subject was disagreeable,
proposed my going to bed, as fittest for a weary man,
judging that to be my present ailment,
I was glad of the offer and immediately accepted it.
I saw that when my mind was turned from delighting in
that wherein our former friendship consisted,
my company was rather unpleasant to him, and soon left his house in the morning,
dispatched my business, and returned home with as much speed as I could,
without the least inclination to go elsewhere.
I believe my prayer was heard; for I had patience granted me; I say granted,
because no man can endue himself therewith,
and I think my distress gradually abated after the time aforementioned.

When one has fasted for a long season,
men of prudence will portion out food to him with care,
that his strength may be increased and the constitution preserved healthful and sound.
The Lord,
whose love and care to His children far exceed
that of any natural parent to his offspring,
dealt with me in his tender mercy, giving me at times, by the gentle touches of his love,
to feel that he had not forsaken me, which in a few minutes would be again withdrawn;
but though of short continuance,
it was sufficient for me to own that it was worth all my sorrowful longing.
He was pleased to let me experimentally know the value of heavenly bread,
by the lack of it, and having food and raiment, I was taught to be therewith content;
the renewing of heavenly favour and the covering of the Holy Spirit,
so as to be admitted to stand before Him in humble reverence with gracious acceptance,
was all my soul craved.
I neither wanted this man`'s gift, nor the other man`'s popularity and eloquence,
but to be in mercy admitted into the number of his family,
and enabled to occupy my own gift to the honour of Him who gave it.
When Peter was examined by his Lord whom he had denied through fear,
"`Do you love me more than these?
the third time he answered, "`You know all things, you know that I love you.`"
He did not answer the question in its full extent, that is,
"`more than these,`" the rest of the disciples who had not denied their Lord and Master,
as Peter had done, who was nevertheless looked upon with forgiving compassion,
and therefore had need to love in proportion.
Perhaps his honest confession and appeal to his
Master`'s knowledge might shorten his answer;
and his threefold charge of feeding the sheep and lambs of his Lord,
be necessary to gain his diligent attention to
the work of Him whom he had three times denied;
he to whom much is forgiven, loves much if he is not ungrateful.
No marvel that I met with this trial of my love and affection, who so often,
not through fear, but the desire of indulging my creaturely will, had denied,
or neglected to follow my Lord and Master,
who had so early made me acquainted with his will,
and who now had passed by my offences, and called me to work in his vineyard.
I was now made thankful for favours which before had scarcely been owned as such.
To be preserved inwardly watchful and quietly resigned to wait upon the Lord,
though we partake not of immediate consolation by the renewing of life,
is a great blessing, for which we ought to be thankful, as we cannot stay our own minds,
nor curb our thoughts without divine aid.
I believed that labour was healthful,
created an appetite and sweetened the relish of rest
and food in a spiritual as well as natural sense,
and therefore I wanted not to eat the bread of idleness and live on the labour of others.

After this trial, which continued most of the summer,
I was much favoured with the incomes of divine love and life,
and in the winter following, visited most of the meetings in Chester county,
and some few in Philadelphia county.
The weather was very cold, being about the middle of the tenth month when I set out,
and in my journey I went to visit a worthy Friend who was indisposed,
and as we sat together in the evening,
he asked me why I chose the winter season to visit my friends,
for many infirm folks could hardly attend meetings,
and said he was sometimes ready to query,
whether public Friends do not take that time to serve their Master,
because they could do but little for themselves.
I was thoughtful and low in my mind before,
and had some reasoning whether it had not been better that I had stayed at home,
than ventured out on the service at that time of the year.

Though I thought I had an engagement sufficient when I set out,
his query made me more thoughtful, and added to my reasoning.
But I soon recovered strength,
and it came into my mind to ask him whether Friends could eat
to supply and sustain their bodies in the summer,
and partake also of spiritual food for their souls in that season,
so as not to labour in the winter and care for the sustenance of then bodies,
or assemble and attend meetings to worship and
wait upon God for spiritual food for their souls.
He acknowledged I had by this query satisfied him to the full,
and said he was glad of my visit, and hoped his talking as he did,
would not discourage me, for I believe he saw it brought a damp over me at first.
This answer I believe was given to me for my own help,
and was encouragement to me through this journey, in most of which I had Joshua Johnson,
of Londongrove, for a companion, who was very agreeable,
and in my return home I felt great peace.
