== Chapter II.

[.chapter-synopsis]
* His journey with Robert Jordan to the Western part of Maryland, in the year 1738. Also to the quarterly meeting at Shrewsbury, in New Jersey
* And with John Hunt through that province
* His visit to the Eastern shore of Maryland
* His journey to Fairfax and Hopewell, in Virginia, in company with a committee of Friends
* And a second time to the Eastern shore of Maryland, with John Cadwalader and companion
* His visit to New England in company with Samuel Hopwood, in 1742.

In the summer following I went with Robert
Jordan to West River yearly meeting in Maryland,
and we visited most of the meetings of Friends in that province,
and his company was profitably instructive to me who was but young in the ministry.
I think I knew him well, he had a good gift of the ministry,
and was highly favoured in the living openings of truth,
but was often low in mind and very humble in spirit.
One time as we were riding together, he lagged behind for several miles.
I asked him why he rode so slow, he made no reply, whereupon I stopped until he came up,
his countenance was solid, and looked as if he had been weeping.
I asked what ailed him, after some time he told me,
that he had been thinking of the great favours which man partakes of,
particularly in being placed over the beasts of the field,
and how easily they were broken, and made subject to his will,
what a small turn with the bridle would put them to the right hand or to the left,
and on a gentle motion would amend or slacken their pace,
at the will or pleasure of the rider; and that man,
the most noble and intelligent creature,
should so far neglect the duty of a willing subjection to his Maker,
who has so highly favoured him with temporal blessings,
and the knowledge of heavenly things.

I had been at that meeting about three years before;
having had some business to do for a friend of
mine on the Eastern shore of the Chesapeake,
and crossed over the bay to the Western shore, and was at the yearly meeting,
and was grieved at the conduct of some of the elders, whose age,
if they had kept to the truth and had been zealous for the honour thereof,
would have made them better examples.
I spoke my mind plainly to them, but not without proper caution, as I thought,
both with respect to my youth and their age.
But some seemed a little warmed thereby, and asked for my certificate, if I had any.
I honestly told them the principal business that brought me from home was temporal,
and having accommodated it, I thought I might attend that meeting without offence,
if I did not misbehave myself.
William Richardson desired Friends to consider what I had said,
for he believed if they did,
they would perceive the young man had a certificate with him that might
answer for one of a neighbouring province to attend such a meeting.

It may not be unseasonable to relate that in the year 1736, one night as I lay in bed,
my mind was uncommonly affected with the incomes of divine love and life,
and therein I had a view of the churches in New Jersey,
with a clear prospect that I should visit them.
In that prospect, and the strength of affection which I then felt,
I said in my heart it is enough;
I will prepare for the journey as soon as I can hear of a suitable companion,
for I do not expect that I shall have a clearer sight than I now have.
I soon heard of a Friend who had a visit to New Jersey before him,
and spoke to him about my concern, but he let me know that he knew of a companion,
and they had agreed upon a time to proceed.
After I had mentioned it to him and some other Friends, my concern seemed to die away;
but I remembered the resolution I had taken up,
and that I then thought I would not look to be bidden again,
and was fearful something had drawn my mind from the proper attention to that opening,
which was the reason it seemed to go off.
The more I strove to look after it, the duller it grew;
and I then sorely repented that I had spoken about it,
and thought it should be a warning to me in future;
for I began to see there was a difference between seeing what was to be done,
and being bidden to do the thing shown: besides this,
I had to consider there was a time to bud, a time to blossom,
a time for fruit to set and appear, and a time for it to ripen.

In the fore part of the winter of 1738, I thought it seemed to revive,
and when I saw John Hunt, a Friend from England,
I believed I should go with him when he went through New Jersey,
and told him what I thought, at which he rejoiced, for we were nearly united.
We appointed a time to meet at Philadelphia, and when we had so far concluded,
being about six weeks beforehand, my concern, as I thought, soon withered away,
and I began to be in great fear that I had been again too forward therein.
But after some time of humbling exercise on that account, the Lord, whom I feared,
from the love with which he was pleased to enrich my heart, gave me to remember,
that when I made the appointment with my friend,
it was in his fear and great abasement of self;
and as I had seen clearly to make the appointment,
it was my place to attend to it in humble reliance on
him for ability to perform the embassy;
for the Lord who calls and sends forth his own,
will also provide all things convenient for them.

When the time came, I set forward very poor and needy,
and continued so until we entered upon our service.
We took a few meetings before our general spring meeting; and after attending that,
went to Woodbury, Pilesgrove, Salem, Alloway`'s Creek, Cohansey, and so to Cape May,
and had some close work, but in the main it was satisfactory to ourselves.

After having several meetings at and near the Capes, we went to Great Egg Harbour,
and had a meeting there, and another at the house of our friend Japhet Leeds,
and so over the marshes to Little Egg Harbour River,
and had two meetings with Friends there.
In one of these I stood up with a large opening as I thought,
but after a short introduction it closed up, and I sat down again,
which was some mortification to me as a man, though very profitable;
being thereby taught to know that he who would speak as the oracle of God, must,
under the gentle burden of the word, in humble fear wait for wisdom, utterance,
and ability to perform the service to the edification of the church and his own peace,
and not to look after large and specious openings,
however desirable to the creaturely part in ourselves or others,
which must suffer famine.

At one of the meetings in these parts, coming very early,
a Friend belonging thereto invited us to go to his house not far off,
and he would put up our horses to hay during the time of the meeting,
saying that we must go to his house to dine.
I felt a stop in my mind,
and told him that our horses could stand very well there until after meeting.
It so fell out that neither of us said anything in the meeting,
which was satisfactory to us,
for we had a sense that the people had been fed with words and hungered for them
more than for the instruction of the pure word of life nigh in the heart and mouth,
that they might not only hear it but be found doers thereof.
After the meeting no one asked us to dine, but went away and left us,
and had it not been for the care of our kind
guide who came from the meeting we were last at,
we should have been at a loss to get forward.
I mention this to show how unacceptable silence is to such whose ears itch after words.

From hence we went through the desert to Upper Springfield,
where we had a satisfactory meeting; then taking the meetings northward,
to Stonybrook and Trenton, we returned to Bordentown, and so crossed the Delaware.
Some of the meetings were large and satisfactory under the owning of truth,
the power whereof was in dominion and the name of the Lord praised,
who is worthy forever.
Some were remarkably close and hard,
which made me remember a saying of that experienced minister and elder, John Fothergill,
that, "`When he was first in this country, he had some extraordinary meetings hereaway,
the people being industrious in a natural as well as spiritual sense,
some of whom were now removed,
and their children possessed the temporal estates of their fathers,
and though their outward habitations looked spacious,
their meetings for worship were dull and heavy, by reason of a worldly spirit,
and their indifference about heavenly treasure.`"

One meeting we were at was remarkably hard, and my companion was exceedingly exercised,
under a sense that the people were too rich, full and whole in their own eyes,
but he sat the meeting through and suffered in silence.
I had something to say which was very close,
and felt a degree of the strength and power of truth to
clear myself in an innocent and loving manner,
and remembering they were brethren, I did not preach myself out of charity towards them,
and so had peace.
We went home with an elderly Friend, who in a stern manner asked me from where I came,
and said I was a stranger to him.
I answered him with a cheerful boldness; he asked me what my calling was,
I told him husbandry: he queried if I was used to splitting wood;
I let him know I had practiced it for many years.
He again asked me,
if I knew the meaning of a common saying among those who were used to that business,
"`'`Tis soft knocks must enter hard blocks.`"
I told him I knew it well,
but that to strike with a soft or gentle blow at a wedge in
blocks of old wood that was rather decayed at heart,
would drive it to the head without renting them, and the labour would be lost,
when a few smart lively strokes would burst them asunder.
Whereupon he laid his hand on my shoulder, saying, "`Well my lad,
I perceive you are born for a warrior, and I commend you.`"
Thus we came off better than we expected,
for I thought he pointed at my service that day; he was ever afterward very loving to me,
and I was thankful that the Lord was near to me, for which I praise his sacred name.
To be becomingly bold in the cause of truth, at times is particularly necessary,
otherwise the weight of the testimony thereof would be lessened,
and a carping spirit be set over it.

From Bordentown we went to Plurastead in Bucks county,
and on a first-day had a pretty good meeting; to a monthly meeting at Buckingham,
then to Wrightstown, the Falls, and Middletown,
which meetings were in a good degree satisfactory,
the power of truth being felt to arise, for which we were thankful;
though in some of them there is a lack of faithful members to put the
discipline in practice against those that are disorderly,
and thereby bring a reproach on the truth.
We then went to Philadelphia, and next day to Chester,
from which I went home the same day.

In the fall of the year 1740,
I had drawings in my mind to attend the quarterly meeting at Shrewsbury,
and was at several meetings on my way there, at one of which a Friend appeared,
who I thought had good service in the fore part of his testimony,
but as truth did not rise into dominion so high as he expected,
perhaps in too much zeal and creaturely warmth,
he laid on a little too fast,`" and continued until the life rather abated,
and some tender minds were hurt.
It often happens that such to whom hard things belong, put them off,
and those who are more tender and least deserving of such doctrine,
take it to themselves to their own hurt.
Ministers ought to be careful while engaged in service,
that they may be favoured with a feeling and sense of the states to which they minister,
and be influenced with wisdom from above to divide the word aright, in meekness,
gentleness, and holy fear; then truth will have its own authority and power.
After the Friend sat down, it became the concern of another in a few words,
as it were to number the slain and search for the wounded,
and set close and hard things where they belonged,
by describing the several dispositions in choosing and refusing to take hard things.
Afterwards I was in company with the Friend, and he being down in his mind,
and perhaps not fully knowing the cause, asked me what I thought of the meeting,
to which I was not forward to answer.
He said,
'`tell me what I have done this day`'? I asked him privately and in a pleasant manner,
what Gideon did to the men of Succoth?
At which he was greatly humbled, fully understanding what I meant,
and did not in the least resent the hint; which I thought was truly great in him,
and very becoming a minister; for if we would instruct others,
we should be exemplary in taking instruction ourselves when necessary.

Falling in company with Robert Jordan,
we proposed a meeting to the Anabaptists at Middletown, to which they readily consented,
and we had a profitable opportunity with them in their meeting house,
and on the same evening a meeting at the house of Hugh Hartshome,
to which several Baptists came.
This was a time of favour, and I hope of service,
it was concluded by Robert Jordan in solemn prayer and thanksgiving to the Lord,
who is worthy forever and ever.
Just as the meeting broke up, I felt myself poor and inwardly weak,
to as great a degree as ever I had done,
and looking towards my said friend I saw he was in the same condition;
but a query of our dear Lord`'s came suddenly into my mind and ministered relief, namely:
Who has touched me?
Which I repeated to my companion, believing that it was as much for his help as my own.
He understood the meaning instantly without further explanation, and was also relieved.

Perhaps some who may hereafter peruse these lines,
may think this is too bold for a mortal man to mention;
but I have by a degree of experience known,
that when the healing virtue of truth from the holy Physician of souls,
has flowed through a humble servant,
to the relief of some of the infirm and poor amongst the people,
who have followed physicians of no value and spent all
their living without a cure being wrought,
notwithstanding virtue has gone through them as instruments or conduits only,
they have felt inwardly weak for a time,
that in humble abasement of soul they might be taught to acknowledge, that the kingdom,
power and glory, does belong to Him alone, who is God over all blessed forever and ever.

From there we went to William Hartshorne`'s, at Sandy-hook,
and so to the quarterly meeting at Shrewsbury, which was large,
and the power of truth was felt in a good degree;
but many loose and rude people of the neighbourhood and
parts adjacent coming together at such times to drink,
carouse, and ride races, are very hurtful to each other and disturbing to Friends.
I had several meetings on the way home, and enjoyed great peace,
and could therefore rejoice and ascribe the praise to the Lord,
who had called and enabled me to perform this service.

Having a concern on my mind to visit the meetings of
Friends on the Eastern shore in Maryland,
I laid it before our monthly meeting and obtained a certificate in the tenth month.
My brother-in-law, James Brown, bore me company;
and we were at Cecil monthly meeting held at Chester in the eleventh month.
Before meeting a Friend informed me that he thought it
would be best for me to cross Chester River,
and go directly southward.
I told him it might be so, but I could say little to it at present;
but some Friends consulting about it,
and one being there who lived near the meeting house in Queen Ann`'s county,
they thought he could give notice on first-day to several meetings;
so a Friend ventured to speak publicly thereof at the close of the meeting for worship,
without letting me know what he intended to do.

I had been uncommonly distressed as I sat in the meeting,
from an apprehension that but few of the Friends
belonging to that particular meeting were there,
and when he published where it was proposed I should be during the ensuing week,
I felt my mind turned another way.
I stood up and told Friends,
that I believed they thought it most for my ease
to lay out the meetings after that manner,
but if Friends at that particular meeting would
favour me so far as to meet there next day,
I should be glad to sit with them,
provided they would please to let other Friends
and neighbours who were absent know of it;
for if I had a right sense, there were several members not present.
Also, that I should be willing to be at Cecil meeting on first-day,
and Sassafras on second-day, which was directly back,
but told them it seemed easiest to my mind, though it would occasion more riding.
This being agreed to, we had a much larger meeting next day, for many before were absent,
as I had thought,
and I had a full opportunity to discharge myself toward the lukewarm and indifferent,
and the disorderly walkers, and had peace.

I visited several families on seventh-day to good satisfaction,
and was at Cecil meeting on first-day, and the next day at Sassafras,
and had to believe it was by the secret direction of the good Shepherd,
who never fails his dependent children, that I was turned this way;
for he was pleased to own my service in these meetings by his presence in a good degree,
to the praise of his own name, which is worthy forever.
From there we passed over the head of Chester by the bridge, John Browning,
a Friend from Sassafras, going with us as a guide,
who some time before had been convinced of the blessed truth,
by the inward operation of the holy Spirit, without any instrumental means.
He had been a member of the church of England,
and for his sobriety was chosen a vestryman;
but after a time felt a scruple in his mind about taking off his hat,
when he entered the church yard, so called,
fearing it was a superstitious adoration of the ground, from its supposed holiness;
but would take it off when he entered the worship house, and walk uncovered to his pew.
But after a time he could not uncover his head,
until what they call divine service began; which,
as he kept attentive to the scruple in his mind, became very lifeless to him,
who was inwardly seeking for substance and life.
He therefore withdrew from it, and after some time went to one of our meetings,
rather out of curiosity than expecting any good, but felt himself owned,
and had a taste of the peace which the world cannot give,
and from that time became a constant attender of our meetings.

We had a meeting at Queen Ann`'s,
amongst a people who for lack of keeping to the life of religion,
had almost lost the form.
In conversation at a house in the evening,
I asked a Friend whether she was a Friend`'s child, or one convinced of our principles;
her reply was, that when she was young, she lived at a Friend`'s house,
and took a notion of going to meeting with them, which she had done ever since.
Alas! when notion changes the will,
and not that faith which works by love to the purifying of the heart,
the religion is without reformation, empty and dead.
From there we went to Tuckaho meeting,
and the weather being very cold and rivers frozen up,
several masters of vessels and sailors came there, and others who were people of fashion.

In the forepart of the meeting a man spoke, whose communication grieved me,
for my heart yearned towards the people; the words he began with were,
"`Woe, woe, to the crown of pride and the drunkards of Ephraim;`"
and with very little application he sat down.
It appeared to me as if the appearance of gaiety had fired the creaturely zeal,
which was the chief motion to this short sermon;
this with the cold wind blowing in at the door, much unsettled the meeting,
it being at the time of a remarkable snow storm.
I desired the door might be shut, which being done,
the house became more comfortable and the meeting settled,
and I stood up with a heart filled with affection,
having that passage of Scripture before me,
in which the apostle Peter declared the universality of the love of God, i.e.:
"`I perceive of a truth that God is no respecter of persons,`" etc.
I was enlarged thereon to my own admiration,
and I believe the satisfaction of the people; the meeting ended sweetly,
with thanksgiving and prayer to the Lord for the continuance of his mercy,
who is the author of all good, and worthy of adoration and worship forever.
After this we attended the several neighbouring meetings, through very cold weather;
and the houses being open and unprovided with the means of keeping them warm,
of which there is too manifest a neglect in those parts, they were uncomfortable,
which occasioned unsettlement.
We reached home just before our quarterly meeting in the twelfth month.

In this journey, travelling in Talbot county,
an elderly man asked us if we saw some posts to which he pointed, and added,
the first meeting George Fox had on this side of Chesapeake Bay,
was held in a tobacco house there, which was then new, and those posts were part of it.
John Browning rode to them, and sat on his horse very quiet;
and returning to us again with more speed than he went,
I asked him what he saw amongst those old posts; he answered,
"`I would not have missed what I saw for five pounds,
for I saw the root and ground of idolatry.
Before I went,
I thought perhaps I might have felt some secret virtue
in the place where George Fox had stood and preached,
whom I believe to have been a good man; but while I stood there, I was secretly informed,
that if George was a good man, he was in heaven, and not there,
and virtue is not to be communicated by dead things, whether posts, earth,
or curious pictures, but by the power of God, who is the fountain of living virtue.`"
A lesson, which if rightly learned,
would wean from the worship of images and adoration of relics.

I was not many miles from home this summer,
except to attend our own quarterly and yearly meetings;
but in the fall having some drawings in my mind to
visit Friends in the new settlements in Virginia,
I went with a committee of the quarterly meeting,
appointed to inspect whether Friends at Fairfax were in number and weight
sufficient to have a meeting settled amongst them to the reputation of truth.
We visited all the families of Friends there,
and had a meeting among them to satisfaction;
from there we went to a place called Providence, or Tuscarora,
and had a meeting with the Friends there, who were glad to see us;
and attended Hopewell monthly meeting to some satisfaction.
I also went to a few families settled up Shanandoah, above the three-topped mountain,
so called, and had a meeting amongst them; they were pretty much tendered,
and received the visit kindly,
especially such as did not make profession of the truth with us.
I admired how they had notice, for many came to it,
and some from ten miles or more distance.
I believe that the delight in hunting, and a roving, idle life,
drew most of those under our name to settle there,
and having discharged myself in a plain, yet loving manner, I returned;
and after having several other meetings thereaway,
I went home with peace of mind and thankfulness to Him
who enables his children to answer his requirings,
having rode in this journey above four hundred miles.

This winter, John Cadwalader and Zebulon Heston,
in their return from a religious visit to Friends in Maryland, Virginia and Carolina,
were at my house,
and being desirous to visit some meetings on the Eastern shore of Maryland,
I went with them to Sassafras meeting,
and called to see the widow and children of John Browning,
who had been dead about a month,
and she gave me in substance the following account of him:

"`My husband was not long sick, but said he believed he should not recover,
and charged me to endeavour that his children should be
brought up in the way of truth which Friends profess;
and if they inclined to have trades, to put them apprentice to real Friends,
not barely nominal ones, which she said she was willing to do,
though she had not yet joined Friends.
He desired she would not trust her own judgment,
and named some Friends with whom she should advise in choosing masters; then said,
when I am dead,
bury me by my father and mother in the grave yard belonging to our family,
and you know that I put a large grave-stone at my father`'s grave,
and there is one ready for my mother`'s grave, which I did not put there,
because I began to think they were more for grandeur than service.
I sent for them to England, not at the request of my father, they are mine,
and now I have a full testimony against such formal tokens of respect;
therefore when I am buried, before the company leaves the grave,
inform them what my will is,
and desire their help to take the grave stone from my father`'s grave,
and carry it out of the yard, that it may be brought home, and lay one in one hearth,
and the other in the other hearth of this new house,
and they will be of real service there;^
footnote:[He had built a new brick house, and the hearth was not fully laid.]
which she promised him to observe, and told me she had complied therewith;
he remained sensible to near the last, and departed in a quiet resigned frame of mind.`"

How weak are the arguments of such who make profession with us,
and plead for those grand marks of memorial, or other tokens of distinction set up at,
or on the graves of their deceased relations; and how soon would they subside,
did they but live so near the pure truth as to feel the mind thereof,
as I fully believe this our friend did.
The name of the righteous will not perish, but be had in everlasting remembrance,
because their portion is life for evermore,
having entered into that kingdom prepared for
the blessed before the foundation of the world.

In the spring of the year 1742,
I felt strong drawings of mind to visit Friends in New England,
having had some view thereof several years before; and having obtained a certificate,
I set forward in the third month, and after visiting several meetings in New Jersey,
and one in New York, I attended the yearly meeting on Long Island,
wherein the power of truth was felt, and a great openness to those of other societies,
many of whom were present, particularly on the last day,
and two priests who behaved solidly.

I then went with Samuel Hopwood, a ministering Friend from England,
with whom I had travelled in this journey through part of New Jersey, to Ryewood,
and had a meeting there, where were a few solid Friends, but others were too talkative.
At Old Seabrook we had a meeting in an inn, on the first-day of the week,
the people being chiefly Presbyterians,
few attended besides ourselves and those of the family, who were kind and civil to us.

Then going to Conanicut, we had a meeting with Friends on that island,
and proceeded to Newport, on Rhode Island,
and on the fifth-day of the week attended the meeting at Portsmouth,
where we met with Lydia Dean, from Pennsylvania,
who was on a religious visit to Friends in New England,
and many other Friends coming to be at the yearly meeting.
It began on the sixth-day of the week with a meeting of ministers and elders,
and two meetings for public worship, one in the forenoon and the other in the afternoon,
which were held in the same order until the second-day of the next week,
when the meeting for discipline began.
This large yearly meeting was generally solid and satisfactory; after which,
taking several meetings in our way, and attending a monthly meeting,
all which were in a good degree satisfactory,
Samuel Hopwood and myself embarked for Nantucket.
Through the mercy of kind Providence we arrived safely there,
after a passage of three days and two nights,
occasioned by scant winds and an easterly storm, which tore our sails very much,
being old and rotten,
so that if some watchful Friends on the island had not seen us in distress,
and come with three whale-boats and took the passengers from the vessel,
we should have been in great danger; for being near a sand-bar,
the vessel struck ground soon after we left her,
and by the violence of the wind was driven on shore.
We looked on this deliverance as a mercy from God,
to whom several of us were bowed in humble thankfulness for this particular favour.
On the 22nd day of the fourth month the yearly meeting began,
which though small on this day by reason of the storm, was comfortable,
the other sittings were mostly large,
and in a good degree owned by the power and virtue of truth.

My friend Samuel Hopwood, apprehending himself clear,
inclined to return to the main land, but no passage offered;
and notwithstanding the meetings had been generally
attended by most of the inhabitants of the island,
and were large,
yet I was not easy without endeavouring to have
some opportunities with Friends by themselves,
as much as could be, which I obtained, besides attending their usual week-day meeting.
In these sittings it pleased the Lord to open my way to
deliver several things which had lain heavy on my mind;
for although some solid tender spirited Friends lived on this island,
yet I saw there was a libertine spirit at work amongst some others,
to draw away from the pure inward life of religion and the simplicity of truth,
into ease and liberty; after which I had great peace,
and my mind was made thankful to the Lord,
who had owned my labour by a good degree of his presence and power.

Being now fully clear and a passage offering,
on the 2nd of the fifth month we took leave of our friends,
and landed the same day in the evening at Seconnet.
On seventh-day Samuel Hopwood and I went to the quarterly meeting at Sandwich,
and were at their first-day meeting also, after which I went back to Seconnet,
and had a meeting at Benjamin Boreman`'s; then returned to Sandwich,
where I again met Samuel Hopwood, and on third-day we had a meeting at Yarmouth,
and returning to Humphrey Wady`'s, we from there went towards Boston,
taking a meeting with Friends at Pembroke.
We reached that town, on sixth-day,
and attended their morning and afternoon meetings on first-day,
also one at a Friend`'s house in the evening.
I have little to remark, save that religion seems to be at a low ebb.
From Boston I went to Lynn, but Samuel Hopwood returned towards Rhode Island.
I had a meeting at Lynn, also at Salem, Newberry and Dover, being the monthly meeting;
the next day at Cachechy, and in the afternoon again at Dover,
at the burial of Mary Whitehouse, who was ninety-five years of age.
On second-day morning I was drawn to have a meeting over the river on the Kittery shore,
among Friends, which was satisfactory to myself and them,
there being a tender people there.

On third-day morning as I lay in bed, I felt my mind drawn towards the north-west,
which was an exercise to me,
for I had before thought myself at liberty to return towards Boston.
I arose about sunrise, and asked the Friend where I lodged,
whether any Friends lived at a distance on that quarter, for that I had a draft that way,
he answered no, and asked how far I thought to go.
I told him it did not seem to me to be more than ten miles;
he said there was a people about eight miles distant,
which he supposed was the place to which I felt the draft.
I desired him to send a lad with a few lines to some person whom he knew,
to inform them that a stranger would be glad to have a
meeting among them at the eleventh hour of that day,
if they were free to grant it, which he did, and he and his wife went with me.
We got to the place near the time proposed, and found a considerable gathering of people,
that I wondered how it could be in so short a time, not more than three hours warning;
they were preparing seats, by laying boards on blocks in a large new house,
and soon sat down in an orderly manner.
I went in great fear and inward weakness, and at the sight of such a gathering of people,
and none of our profession among them except the Friend and his wife who accompanied me,
and two others who joined us on the way, my spirit was greatly bowed,
and my heart filled with secret cries to the Lord,
that he would be pleased to magnify his own power.
And blessed forever be his holy name!
He heard my cry,
and furnished with wisdom and strength to declare his word to the people,
among whom there were some very tender seekers after the true knowledge of God.
The doctrine of truth flowed freely towards them,
the universality of the love of God being set forth in opposition to
the common predestinarian notion of election and reprobation.

When the meeting was over, I felt an uncommon freedom to leave them,
for they began to show their satisfaction with the opportunity in many words;
so speaking to the Friend who went with me, we withdrew and went to our horses.
On mounting, I beheld the man of the house where the meeting was held, running to me,
who taking hold of the bridle, told me I must not go away without dining with them;
I looked steadfastly on him, and told him,
that I did believe this was a visitation for their good,
but I was fearful that by talking too freely, and too much,
they would be in danger of losing the benefit thereof,
and miss of the good the Lord intended for them,
and my going away was in order to example them to go home to their own houses,
and turn inward, and retire to the divine witness in their own hearts,
which was the only way to grow in religion.
I left him, and returned with my friend Joseph Estes and his wife.

Next day I was again at Cachechy meeting where Lydia
Dean and her companion Eliphal Harper met me,
it was a good meeting.
From there we went to Dover and had a meeting,
and another the same evening at the house of John Kenny, and being clear of those parts,
I returned, having meetings at Hampton, Salisbury, Amesbury, and Haverhill.
At this last place,
several persons assembled with us who had never heard the preaching of any Friend before;
there was great openness among them, and we had a good meeting together,
for which I was thankful to the holy Author of all good.

Next day I again met with Lydia Dean and Eliphal Harper, at Stephen Sawyer`'s,
near Newberry, where we had a meeting,
at which I was concerned to speak in a brief manner of the beginning
of the reformation from the errors of the church of Rome,
and the sufferings of the Protestants, particularly in England,
some of whose successors turned persecutors,
and were very cruel to those whom they called Sectarians.
The Presbyterians having suffered persecution, in order to be eased therefrom,
came into America and settled in New England,
expecting there to enjoy that reasonable right, the liberty of their consciences;
and forgetting the golden rule of doing to others as they would be done unto, became,
to their lasting ignominy, persecutors of the Quakers, so called,
even to the death of several of them.
I had to speak of the nature and ground of persecution,
and the great inconsistency thereof with Christianity.

Several Presbyterians were present, and an ancient man from Newberry,
one of their leaders and an elder among them, when the meeting was over,
desired he might speak with me.
I being withdrawn into a little parlour,
Stephen Sawyer came and informed me that the old man wanted to be admitted to me,
to which I felt no objection, being quiet and easy in my mind,
though I expected he would be for disputing.
When he came in, he let me know that he had some observations to make to me:
"`he supposed I was a man that had read much,
or I could not be so fully acquainted with the reformation,
and that I had had a college education.`"
As to the last, I told him that I never had been at a school but about three months,
and the man I went to being a weaver, sat in his loom and heard his scholars read;
that I was so far from having a college education, that I was born in a wilderness place,
where a few families had settled many miles remote from other inhabitants.
Lifting up his hands, he blessed himself and added,
"`Heaven has then anointed you to preach the gospel,
and you have this day preached the truth; but I can assure you,
though I have been a parish officer,
I never did take anything from your friends the Quakers, for I am against persecution;
so God bless you with a good journey.`"

The next day I had a meeting at Ipswich, in the house of Benjamin Hoeg,
none professing with us living in that town, but himself and family;
though a friendly man, as I came late to the town the evening before,
invited me to lodge at his house, which I accepted, and being weary, slept well.
In the morning I heard a noise of high words in the street,
and getting up I opened the door of the parlour where I lodged,
and through a passage into the kitchen,
saw a woman whom I took to be the mistress of the house, and went toward her;
but with a look of exceeding displeasure she immediately shut the door.
I turned into my room again; and after a while the landlord came to me,
and told me that he had been with the burgess,
who had given leave that a meeting might be held in the town-hall;
but the priest and his two sons had since been with the burgess and forbade him,
and that rather than displease them, he had withdrawn the leave.
The priest asserted that the Quakers were heretics,
and had gone about the town to forewarn his hearers against going to the meeting,
which was the meaning of the noise I had heard in the street.
I felt very easy,
and desired that he would not trouble himself any further than to inform them,
that the meeting would be held at the house of Benjamin Hoeg;
for I did believe that the railing of the priest
would raise the curiosity of the people to come,
and so it proved.
I asked him to show me the way to the house,
that I might assist in making provision for seats if occasion required;
he said I must take breakfast with him,
which was soon brought in by the woman who had shut the door as before mentioned.
I asked him if she was his wife, he told me she was,
on which I arose from my seat and offered her my hand, asking her how she did,
but she in displeasure refused, and saying not a word, directly left the room.

After breakfast we went to the house where the meeting was to be held,
and there soon came a great number of people, and the priest also very near the door,
where he stood cautioning his hearers; but several came by an alley to the back door,
and others seemed little to regard him.
After a time he went away,
and through the goodness of the Lord we had a solid profitable meeting.
I believe many were there whose hearts were reached and
tendered by the love and power of the gospel of Christ,
and among them I saw my scornful landlady;
a woman whom she valued having persuaded her to come with her.
Before the meeting ended,
I perceived her countenance was changed and her stout heart tendered,
and after it she came to me with her husband, and kindly invited me to dine with them.
I owned their love, and desired them to mind the truth by which they had been reached;
so in humble thankfulness of heart to the great Author of all mercies, I left them,
and went that night to Salem.

After tarrying one meeting the next day, passed on to Marblehead,
and had a large meeting in the townhall, the magistrates readily granting it.
I had to speak on the nature and necessity of morality,
showing that a man could not be a true Christian without being a good moralist.
I thought they had need of reformation in their morals,
though they professed Christianity in a high manner.
One thing is worthy of remarking,
the select men and officers were very careful to keep the rude
boys and people that came to the door from making disturbance;
several of them walked to the door and spoke to them,
and rapped some on their heads with their canes to make them still;
the meeting ended to satisfaction without the least opposition.
From there, taking a meeting at Lynn by the way, I went to Boston,
and was at their meetings on first-day in the forenoon and afternoon, at both which,
several came who were not in profession with us,
and truth opened the doctrine thereof to the people pretty freely.
I was not easy to leave this town without having
an opportunity with Friends by themselves,
for which purpose it was held at Benjamin Bagnall`'s,
and therein I was deeply bowed under a sense of the state of ease in
which some were delighting themselves in their imaginary attainments,
while the pure seed lay under suffering.
But blessed be the Lord,
who was graciously pleased to endue with a spirit of love and tender compassion,
and thereby enabled me to discharge myself fully,
and I was released from what had lain very heavy upon me for several days.

The next day I had an opportunity with several Friends at Samuel Pope`'s,
and then left Boston pretty easy in my mind, and went to Samuel Thayer`'s, at Mendam,
who accompanied me to Uxbridge, where we had a meeting with a few raw, talkative people,
which, through the goodness of God, was nevertheless to some degree of satisfaction.
I returned with Samuel Thayer to his house,
where I met with Hannah Jenkinson from Pennsylvania,
and we were at Mendam meeting together.
I was also at Wainsokett and Providencetown, the latter of which was a poor meeting,
the people looking for words, and not waiting for the word of life in their own hearts.
I had a large and good meeting at Neshanticut,
the Lord`'s presence being felt to his own praise, and another at Greenwich;
then proceeded to Smithfield and Taunton,
taking a meeting at each to some good degree of satisfaction; then to Swanzey, Freetown,
Rochester and Cushnet, having a meeting at each.
In one of these, I stood up to speak a few words in great fear, life being low,
and as I apprehended the seed under suffering.
I heard a kind of sighing by one in the gallery,
which seemed to bring death rather than to raise life,
and after I had spoken a sentence or two, it became exceedingly burdensome;
whereupon it came fresh in my mind to say,
"`can an Israelite sing a true Hebrew song while
the seed is in captivity and under suffering?
An attempt of the kind shows ignorance.`"
There was a great silence and the sighing ended,
and I received strength to deliver what was on my mind,
and truth was felt in a good degree to arise; the meeting ended well,
and several Friends expressed their satisfaction with the service that day.
Being clear of those parts I went to Rhode Island,
and in a sense of the goodness and mercy of the
Lord who had helped me in my travels in his work,
my soul worshipped before him.

On the 22nd of the sixth month I sat with Friends at Newport,
in their fore and afternoon meetings,
and next morning left Rhode Island with a heavy
heart and had a meeting at South Kingston,
where I met with Susanna Morris and her sister Hannah Hurford.
The day following we had one at Thomas Stanton`'s, in Westerly,
among a mixed people of several societies, to whom I felt a stream of gospel love;
but the meeting was hurt by some appearances by way of ministry.
Our manner of sitting in silence is so different from
the common practice of most other religious societies,
that it is no marvel if it should be as time misspent to some,
and fill others with wonder, which was the case this day.
For lack of a deep inward attention to the living word of truth,
instead of instructing the people in the true way of worship in the love of the gospel,
there may be a disposition to censure them for what they understand not,
and thereby raise a dislike in them, to the foreclosing of other service.
I have sometimes observed hurt done by this means,
by some who appeared in the impatience, not having the weight of the work upon them.
Custom had taught the people to look for words,
and they were offended by words spoken not in season, and therefore not fitly spoken.
I left this meeting with sorrow, and after I mounted my horse,
the person who had appeared there three times, came to me,
and said "`he hoped he had not hindered my service in it.`"
I reminded him, that he had informed the people in that meeting,
their looking for words had been one reason why the Lord had
shut up the testimony of Truth in the hearts of his servants,
which I told him I did believe was not then the case;
but that his forward appearances had unsettled the people, and marred the service.

Feeling my mind drawn back towards Newport, I went that evening to James Congdon`'s,
and the next day to Newport, calling in my way at James Parry`'s,
where I found Lydia Dean very sick, she being so far on her journey towards home.
On the fifth-day of the week I was at two satisfactory meetings there,
and on seventh-day had a small meeting at Nicholas Easton`'s,
and on first-day two large good meetings at Newport.
Next day hearing that Lydia Dean was come to Samuel Clark`'s, on Conanicut island,
I went with several others to see her, and she returned with us to Newport,
where after a very short notice we had a large evening meeting,
wherein the Lord was pleased mercifully to favour us with his
immediate presence to the glory and praise of his own eternal name,
who is worthy forever!

After attending their monthly meeting at Portsmouth,
finding my mind clear and easy to proceed homeward, Lydia Dean, Patience Barker,
John Easton and myself set out from Newport,
taking leave of Friends in a tender manner on both sides,
and were the first-day following at a meeting in Westerly,
which was in a good degree satisfactory, and passing through Connecticut to New Milford,
Oblong and Ninepartners, had meetings in each place.
Having a great desire to be at our yearly meeting for Pennsylvania and New Jersey,
to be held at Burlington, which was approaching, we passed on,
and took a meeting at Samuel Field`'s, to which several not of our Society came,
and the opportunity was, through the goodness of the Lord, profitable.
We then proceeded as fast as convenient,
and reached Burlington on first-day in the time of the yearly meeting,
where many Friends were gathered, and Michael Lightfoot in his return from Great Britain,
with whom came John Haslam and Edmund Peckover on a visit to Friends in America.
This meeting was large and solid, at which I met my dear wife to our mutual,
thankful rejoicing.
After the meeting I went home, where I found things as to the outward, in good order,
for which I was humbly thankful to the Lord,
who had not only been with me by his heavenly presence in this journey,
and brought me safely home to my family, but had supported them in my absence;
blessed be his holy name forever!
