== Chapter III.

[.chapter-synopsis]
* His visit to Long island
* Visit with others to the families of Friends in Nottingham
* to some families in Philadelphia and to the mayor of that city, also to the assembly of Pennsylvania in the year 1748
* His journey with Michael Lightfoot to the yearly meeting at West River, in Maryland
* and accompanied by Joshua Brown to several meetings in Pennsylvania and New Jersey
* His considerations on apprehending it his duty to visit Friends in Europe, and proceedings in preparing to enter on that weighty service, to the time of his leaving home in order to take shipping for London.

In the spring of the year 1743,
having drawings in my mind to make a general visit to Friends on Long island,
I sat out in the third month, in order to be at the yearly meeting at Flushing,
which began on the sixth-day of the week,
and continued until the second of the week following.
It was large and signally owned by the power of truth in each sitting;
the public service in the ministry lay mostly on Edmund Peckover,
who was there in his way to New England,
On first-day I thought I had an engagement to stand up,
and considerable matter before me,
and after speaking three or four sentences which came with weight, all closed up,
and I stood still and silent for several minutes, and saw nothing more,
not one word to speak.
I perceived the eyes of most of the people were upon me, they, as well as myself,
expecting more; but nothing further appearing, I sat down,
I think I may say in reverent fear and humble resignation,
when that remarkable sentence of Job was presented to my mind,
"`Naked came I out of my mother's womb, and naked shall I return; the Lord gave,
and the Lord has taken away; blessed be the name of the Lord.`"

I suppose for nearly a quarter of an hour I remained in a silent quiet;
but afterwards let in great reasonings and fear
lest I had not waited the right time to stand up,
and so was allowed to fall into reproach;
for the adversary who is ever busy and unwearied in his attempts to devour,
persuaded me to believe that the people would laugh me to scorn,
and I might as well return home immediately and privately,
as attempt any further visit on the island.
After meeting I hid my inward exercise and distress as much as I could.
I lodged that night with a sympathizing friend and experienced elder,
who began to speak encouragingly to me, but I said to him,
that I hoped he would not take it amiss if I desired him to forbear saying anything;
for if he should say good things, I had no capacity to believe, and if otherwise,
I could not then understand so as to be profitably corrected or instructed,
and after some time I fell asleep.

When I awoke, I remembered that the sentences I had delivered in the meeting,
were truths which could not be wrested to the disadvantage of Friends,
or dishonour of the cause of truth,
though they might look like roots or something to paraphrase upon;
and although my standing some time silent before I sat down
might occasion the people to think me a silly fellow,
yet they had no cause to blame me for delivering words without sense or life.
Thus I became very quiet, and not much depressed,
and was favoured with a humble resignation of mind,
and a desire that the Lord would be pleased to magnify his own name and truth,
and preserve me from bringing any reproach thereon.
I ventured to have meetings appointed,
and my particular friend and intimate acquaintance, Caleb Raper, of Burlington,
being at that meeting, went as companion with me, of whose company I was glad,
he being a valuable elder.
We went first to Rockaway, then to Jamaica, Sequetague, Setawket, Matinicock, Cowneck,
and Westbury meetings, and at most of them I had good satisfaction;
the presence of the Lord in whom I delighted above all things,
being witnessed to my comfort,
and I believe to the edification and comfort of the sincere in heart;
but the testimony of truth was particularly sharp to
the lukewarm professors and libertines in our Society.
That humbling time I had at Flushing was of singular service to me,
being thereby made willingly subject to the divine openings of truth,
the motion of the eternal Spirit and pure word of life,
in speaking to the several states of those who were present in the meetings,
and life came into dominion, and the power thereof overshadowed at times,
to my humble admiration; blessed be the name of the Lord who is worthy forever and ever!

Crossing Whitestone ferry we had meetings at West Chester, Mamaroneck,
Ryewood and Longreach, which were mostly to good satisfaction.
We then went to New York and were at their meeting,
and in the evening had a select one with Friends, which gave me considerable relief,
and I believe satisfaction to them,
and we were made thankful together in the renewings of the covenant of life.
From there we went to a meeting at Newtown on Long island,
and to the monthly meeting at Flushing,
where Friends gave me a certificate in return to that I brought from home,
in which they signified their unity with my service on the island.
Taking leave of Friends in sweetness of mind and inward peace,
being clear of those parts, I returned homewards, and went to the Narrows that night,
but could not get over.

Next morning early, crossed the ferry, when there was a great swell,
occasioned by the stormy weather in the evening and night before; having now no wind,
were obliged to row the boat over.
In the passage I remembered, that in crossing this ferry when coming on this visit,
I thought myself never much poorer,
having only a secret hope and trust in the holy Arm of power,
and being now inwardly sensible of my own weakness,
I had to acknowledge that I went not forth on this embassy in my own will and strength,
and therefore craved only that my blessed Lord and Master would blot out my offences,
and yet enable me so to walk in humble obedience, the residue of my time,
as to be favoured with the answer of well done at the conclusion.
Knowing the nature and treachery of self,
I did not want to be entrusted with much reward at present, choosing rather,
that the Lord in his infinite wisdom and mercy,
should deal out to me my daily bread according to his own pleasure.
"`I passed over this Jordan with my staff and now I am become two bands,`"
was the saying of Jacob.
As this saying of the good patriarch came fresh in my mind, I thought,
that although I could not see myself much increased in heavenly treasure, I came poor,
and had only the staff of faith to lean upon,
yet I had to bless the Lord that he was now pleased to
favour me with the same staff in my return,
on the never failing strength whereof, I might with safety rely,
and in holy resignation I had to praise his worthy name.
I proceeded with my friend Caleb Raper, to Burlington,
where we parted in much love and nearness, in which we had travelled together;
I reached home about wheat harvest, and found my dear wife and family well.

I went not much abroad during the residue of this summer and the year following;
but was careful to attend our own and many neighbouring meetings, also monthly,
quarterly and yearly meetings, in this and the adjacent provinces.
Some business of a public nature, together with my own circumstances,
necessarily engaged me for several years, during which time, that is,
in the spring of the year 1745,
my dear wife having drawings in her mind to visit the meetings of Friends in Virginia,
Maryland and North Carolina, obtained a certificate of the unity of Friends,
to travel in that service with Jane Hoskins of Chester.

In the same year I was nominated with several other Friends to
visit the families belonging to our monthly meeting,
which being large and many Friends living at a distance, was a laborious work,
and not fully performed until the fall of the year 1747,
when account was given that the service was perfected to a good degree of satisfaction.
In the winter following,
I had it on my mind to visit all the families of the particular meeting of Newark,
near Brandywine, who seemed to be in a declining state as to religion,
having dropped their weekday meeting,
and often much neglected to attend their first-day meeting,
many of the elderly Friends being deceased,
and their children almost turned to the world, and united to the spirit, pleasures,
and pastimes thereof.
My brother William Brown and his wife, and mine, were with me on this service,
and great plainness was used in opening to many
particulars the cause of their declension;
and as the love of truth engaged me in the service, I had peace and satisfaction,
and those visited seemed to receive the visit kindly.

In the spring of the year 1748,
I felt drawings in my mind to visit some families of Friends in Philadelphia,
of which I acquainted my brethren at home, and having their concurrence,
in the fourth month I joined with some Friends in the city,
who were before appointed to the service.
We went in much love from house to house, the Lord, by his good presence,
being with us to our mutual comfort; and as I attended to the drawings of truth,
I found a concern to go to the mayor of the city,
accompanied by my good friend Israel Pemberton, the elder,
and was engaged to lay before him the nature of his office as a magistrate,
and exhorted him to take care that he bore not the sword in vain,
but put the laws in execution against evil doers, such as drunkards, profane swearers,
etc., and to be, in his authority, a terror to the wicked,
and an encourager of them that do well; he was loving and tender,
and expressed his satisfaction with the visit.

While I was in the city, the governor summoned the members of assembly together,
and in pressing terms laid before them the defenceless state of Pennsylvania,
in order to prevail with the house to grant a sum of
money to station a ship of war at Delaware capes,
also to encourage the building of a battery below the city,
which was begun sometime before by subscription,
but likely to be too heavy for the undertakers.
One night as I lay in my bed,
it came very weightily upon me to go to the house of assembly,
and lay before the members thereof the danger of departing
from trusting in that divine power which had hitherto
protected the inhabitants of our land in peace and safety.
The concern rested on me several days,
which occasioned me with earnest breathings to seek the Lord,
that if this was a motion from him, he would be pleased to direct my steps therein,
so that I might be preserved from giving just cause of offence to any.
It seemed to be a very difficult time, many, even of our Society,
declaring their willingness that a sum of money should be given to the king,
to show our loyalty to him,
and that they were willing to part with their substance for his use, though as a people,
we had a testimony to bear against wars and fightings.
I made no man privy to my concern until nearly a week had passed;
when one morning it became so heavy upon me,
that I went to the house of an intimate friend,
and as we sat together he had a sense that something of weight was upon me,
and asked if I was concerned about the assembly.
I asked him if he ever knew of any Friend going
to the assembly with a concern to speak to them?
He answered no, adding, "`but I have often wondered that they have not,
for I have understood it was formerly a common
practice for them to sit in silence a while,
like solemn worship, before they proceeded to do business.`"
I told him I had it on my mind to go to the house that
morning and should be glad of suitable company.
He directed me to one whom he thought such,
and I immediately went to him and acquainted him with my concern; but as I spoke,
I felt that I had better go alone, and therefore told him,
if he did not feel clear and easy to go with me, I advised him to stay; he replied,
"`your way is before you, but I believe I must not go.`"
I returned to my friend, who did not discourage me, though I had no company.

Being pressed in mind, I went directly to the state-house before I took breakfast,
and got there just as the speaker was going in; I beckoned to him and he came to me.
I told him I wanted to be admitted into the house,
for I had something to say to them which seemed to me of importance.
He said it was a critical time, and they had a difficult affair before them,
and queried whether I had not better wait until the house parted;
and another member being near, said he thought it would be best,
and less liable to give offence, for there were many members not of our Society,
and if I would wait until the house broke up,
they would inform all the members who were Friends,
and did not doubt they would be willing to give me an
opportunity to inform them what was on my mind.
I told them that would give me no relief,
for I had a particular desire that those members
who were not of our Society should be present;
believing that it would be better for them to hear and
judge for themselves than to have it at second hand,
as it might be differently represented; at which they were silent.
I requested the speaker to go in and inform the members,
that a countryman was in waiting who had a desire to be admitted,
having something to communicate to them, and if they refused, he would be clear;
he readily and affectionately answered he would,
and soon brought me word that they were willing.
There was a great awe over my mind when I went in,
which I thought in some measure spread,
and prevailed over the members beyond my expectation;
after a silence of perhaps ten or twelve minutes,
I felt as though all fear of man was taken away,
and my mind influenced to address them in substance after the following manner:

[.embedded-content-document.address]
--

My countrymen and fellow-subjects, representatives of the inhabitants of this province,

Under an apprehension of the difficulties before you, I feel a strong sympathy with you,
and have to remind you of a just and true saying
of a great minister of Jesus Christ in his day,
"`The powers that be, are ordained of God.`"
If men in power and authority, in whatsoever station, would seek unto God,
who will be a spirit of judgment to them that sit in judgment,
for wisdom and counsel to act singly for Him who ordained the power,
and permitted them to be stationed therein, that they should be his ministers;
they would be a blessing under God to themselves and their country.
But if those in authority allow their own fears and the persuasions
of others to prevail with them to neglect such attention,
and enact laws for their own protection and defence by carnal weapons and fortifications,
according to what is styled human prudence, He who is the great Superintendent,
by withdrawing his power, may permit those evils they feared to come suddenly upon them,
and that in his heavy displeasure.
May it with gratitude be ever remembered,
how remarkably we have been preserved in peace
and tranquillity for more than fifty years!
No invasion by foreign enemies, and the treaties of peace with the natives,
wisely begun by our worthy proprietor, William Penn, preserved inviolate to this day.
Though you now represent,
and act for a mixed people of various denominations as to religion;
yet remember the charter is the same as at first.
Beware therefore of acting to oppress tender consciences,
for there are many of the inhabitants whom you now represent,
who still hold forth the same religious principles with their predecessors,
who were some of the first adventurers into this, at that time, wilderness land,
who would be greatly grieved to see warlike preparations carried on
and encouraged by a law consented to by their brethren in profession,
or others, contrary to the charter, still conscientiously concluding,
that the reverent and true fear of God, with a humble trust in his divine power,
would be our greatest defence and safety.
They who hold different principles and are settled in this government,
can have no just cause of reflection if warlike measures are forborne,
because they knew the charter framed, and the peaceable constitution,
and have ventured themselves therein.

We may observe by laws enacted in parliament when the
reformation was but newly begun in England,
our mother country, there seemed to be wisdom from above to influence their minds.
May you be rightly directed at this time,
many of whom do fully believe in the immediate influence of Christ, the wisdom of God,
which is truly profitable to direct.
It is not from disrespect to the king or government that I speak after this manner,
for I am thankful in heart,
that the Lord in mercy has vouchsafed that the throne of Great
Britain should be filled by our present benevolent prince,
King George II.
May his reign be long and happy.

--

I acknowledged their kindness in hearing me with so much patience,
and taking leave, withdrew.
Several members followed me out and expressed their
satisfaction in an affectionate manner with my visit;
and embracing each other, we parted in a sense of the love and power of Christ Jesus,
our Lord, who, with the Father,
is worthy of all thanksgiving and praise forever and ever.

After my service in Philadelphia was over, I returned home with peace and satisfaction,
and went not much abroad save to our quarterly and yearly meetings,
until the spring following, in the year 1749,
when I went with Michael Lightfoot to the yearly meeting at West River, in Maryland.
In this journey, the weather being hot and some weakness of body attending,
it threw me into a strong fever and a stoppage in my breast,
that it was with some difficulty I got home,
and continued without any amendment a considerable time;
and one evening as I was preparing for bed, an imposthume^
footnote:[a swelling containing pus; an abscess]
broke, which I suppose was on my lungs, almost strangling me for a considerable time.
I expected I was near expiring,
but felt resignation in this trying time beyond my expectation,
which I took to be a great favour from the Lord:
there is no support like the light of his countenance.
I continued bleeding more or less many days, but gradually mended.
In the eighth month being pretty well recovered,
in much love I felt drawings in my mind to visit
some meetings in the back parts of Chester,
Philadelphia and Bucks counties, and part of New Jersey;
and laying my concern before my friends, had their concurrence,
and was accompanied by my kinsman Joshua Brown, through most of the journey.

Our first appointed meeting was at Radnor,
in which truth owned our service in a good degree, and passing over Schuylkill,
went to Plymouth, North Wales, Skippack, and New Providence.
The last meeting, for lack of giving more careful notice was very small,
and not being easy in my mind, I had a singular freedom to let them know,
that I would endeavour to be at that place again on the second-day following,
and should be glad they would please to give full notice thereof.
Having a strong draft in my mind to turn back to North Wales,
I went the same evening to Robert Jones', at Skippack,
and next day to see a Friend who had been a long time indisposed,
with whom we had a good opportunity, which I believe was of advantage to the Friend,
through the goodness and mercy of the blessed Shepherd of Israel.
I also visited two other Friends,
and we were comforted together in the renewing of heavenly goodness.

On first-day I was at North Wales meeting, which was large and satisfactory,
and at Providence again on second-day, where Friends generally met,
and I had an opportunity to clear myself in a particular manner.
Then went to Evans' meeting by the side of Schuylkill,
and had a meeting the same evening at the house of Thomas May,
both which were to some satisfaction; afterwards went to Maiden Creek,
Exeter and Richland, and from there over Delaware to Kingwood,
and visited the meetings in Burlington, Gloucester and Salem counties,
as far down as Greenwich, and returned homewards by Haddonfield.
I called to visit Hannah Cooper, whose husband had not long been dead,
she seemed under affliction of body and mind.
I felt a near sympathy with her, and though we did not converse much together,
yet in the owning love of Him who is a friend to the afflicted,
we were mutually comforted.
She expressed her satisfaction in a tender manner, saying that soon after I came,
her exercise was lightened, and she was refreshed in a sense of the kindness of the Lord,
in affording a sympathy and inward feeling to the children of his family.
My soul was humbled in reverent thankfulness to him the Author of all good,
who is worthy of praise forever.
In the morning I had a passage over the Delaware,
which by reason of ice had not been passable for several days before;
and tarrying in Philadelphia that night, I went next day to Darby meeting,
and the day following got well home, and found my dear wife and family well.

On my leaving home to perform this visit, I felt great inward weakness,
and in going from meeting to meeting, frequent humbling baptisms attended,
in which the present state of the church was seen,
and the conditions of many spoken to in the love of truth,
which made me often think it seemed like a farewell visit, at least for a long time.

As I passed along in this visit,
I observed some people would earnestly press me to go home with them,
and would say they would not take it kind if I did not,
and Friends did not use to serve them so, that is, pass by them;
yet I thought there was not much of the innocent
sweetness of truth to be felt at their houses,
or even about them.
They would say, you have hit the nail on the head,
there is just such people among us as you have spoken of; and seemed as to themselves,
safe and easy,
when perhaps their religion lay much in thinking that good
Friends were familiar with them and thought well of them.
I also took notice of another sort,
who though they were not fond of having Friends to go with them,
would speak well of their service,
and deal it out liberally to others in a censorious manner,
not seeing themselves in a true light,
which would have led them to smite their own breasts, with a feeling, short prayer,
rather than apprehend themselves better than others,
when perhaps covetousness and a worldly spirit had almost destroyed charity,
which is the sure product of true religion.
A third sort, I beheld humbled and bowed, whose words were few, and would frequently,
if they said anything, lament the state of the Society, and speak of their own weakness,
and fear lest they should not walk in the uprightness
of truth before their own families and the church.
The dew of heaven rested on them in their humble situation.
I was thankful in the sense I had,
that there were a few of these in almost every meeting, and I had a firm belief,
that some among the youth were under the hand of
the great Preparer of men for his own work.
These children are mostly modest and diffident of themselves, sincerely affectionate,
not over forward or fondling, but lovers of truth in heart,
to whom I felt great nearness of spirit, believing they would grow in the root of life.

I beheld some others among the youth,
who I feared had too great a delight to live on the labours of others,
who nevertheless had been favoured with the reaches of divine love,
but for lack of dwelling deep and humble, with the pure witness in themselves,
ran out in the affectionate part, and were greatly delighted to hear truth's testimony,
and valued instruments according to their own liking.
These, though they appear as goodly flowers, for lack of a humble abode in the vine,
do sometimes wither away as grass on the house top.
"`If you love me, keep my commandments,`" is a precept of our holy Lord and Master;
to keep his commandments, we must dwell with his grace in our hearts,
by which the law of the spirit of life is known and understood,
by the enlightening and everlasting sure Word of prophecy,
which will privately interpret, and secretly show to every man his duty,
and the calling of God, and abilitate to abide therein;
and his law is light and his commandment as a lamp to the feet of his people forever.

As I sat in a week-day meeting in the winter of 1748,
I felt great weakness and poverty attending my mind,
which occasioned a deep inquiry into the cause.
After a time of inward waiting,
the humbling divine presence was felt in reverent profound silence,
yet the gentle operation of the divine power caused an inward trembling,
and the following was uttered in a language intelligible to the inward man;
"`Gather yourself from all the cumbers of the world, and be weaned from the popularity,
love, and friendship thereof.`"
I believed this to be the voice of the holy One of Israel,
as a merciful warning to prepare for my final change,
or to stand ready for some service which would separate me
from temporal business and the nearest connections in life;
and from that time I endeavoured to settle my affairs,
and contract my little business as well as I could.

In the summer following I met with an unexpected trial,
for without my knowledge my name was put in the new commission for justices of the peace,
and endeavours were used to persuade me to be qualified in order to act in that station;
and some of my particular friends told me it seemed providential,
and they thought it was my place to accept thereof,
as I might be helpful by way of example, to some in the commission who were Friends.
For a short time I was exceedingly straitened,
but my eye being fixed on the Lord for counsel,
it pleased him in great condescension once more to revive the sentence before mentioned,
"`gather yourself from all the cumbers of the world,`" etc., which settled the point,
and I became easy in mind,
and humbly thankful to my blessed Instructor who had called me for other service.

After my return home from the visit to Friends in New Jersey,
I felt such an inward silence for about two or three weeks,
that I thought I had done with the world, and also any further service in the church,
and the preparing hint was brought to my mind,
with thankfulness that I had endeavoured in a good degree to practice it.
One day walking alone, I felt myself so weak and feeble, that I stood still,
and by the reverence that covered my mind,
I knew that the hand of the Lord was on me and his presence round about,
the earth was silent and all flesh brought into stillness,
and light went forth with brightness, and shone on Great Britain, Ireland and Holland,
and my mind felt the gentle,
yet strongly drawing cords of that love which is stronger than death, which made me say,
Lord! Go before, and strengthen me, and I will follow whithersoever you leads.
I had seen this journey nearly fifteen years in a very plain manner,
and at times for ten years,
thought the concern so strong upon me that I
must lay it before my friends for their advice;
but was secretly restrained;
being made to believe that an exercise of that sort would ripen best
to be kept quiet in my own heart to know the right time,
by no means desiring to run without being sent.
To see a thing is not a commission to do it; the time when,
and judgment to know the acceptable time, are the gifts of God.

The time I had to prepare for the journey was short,
and I therefore thought it was needful to employ it to the best advantage;
and as I had a desire to see Friends of several particular meetings, namely, Bradford,
West and East Cain, Uwchland, Nantmill and Goshen.
My sister, Dinah James, went with me to those meetings,
which through the goodness of the Lord were solidly profitable.
We had also a meeting at Henry Hockley's, near French Creek iron works,
which was to some good satisfaction,
and so to the quarterly meeting at Concord in the twelfth month,
where I met my brother William Brown, who queried of me where I had been,
and what I had been doing?
I told him I had been doing as he and every honest man ought to do,
collecting little debts and paying where I owed, and endeavouring to settle my affairs;
for that such care was necessary when one expected a
great sum would be immediately demanded.

In a few days after my return from the quarterly meeting,
I laid my concern before our preparative meeting,
in order that Friends might have a month to weigh and
consider it before I spoke for a certificate.
I wanted their feeling concurrence in this weighty undertaking, firmly believing,
that my great and good Master would not require anything of me
in which my dear friends could not concur,
and though while the power of truth was upon me, I was made freely to give up;
yet now home, and the near affection to a dear wife, only son, relations and friends,
were exceedingly quick and affecting, and something in me seemed to have a choice,
that my friends would judge that I was too weakly and infirm in body,
or not otherwise qualified for the service, and if that should be their mind,
I thought I should be clear.
In the interval I visited the neighbouring meetings,
and carefully attended to the motion of truth therein; and in the first month,
having the concurrence of the preparative meeting,
I laid my concern before the monthly meeting,
and attended our general spring meeting at Philadelphia.
My brother, William Brown, having spoken for a certificate on the like concern,
it seemed pleasant to think of crossing the ocean together,
and Friends were for proposing a passage, and what ship we should go in.
I felt a secret prohibition against being any ways
concerned about a passage until I had a certificate,
and knew that I was fully clear; so returned home.
Having a desire to see Friends in York county, over Susquehanna, I went there,
accompanied by my brother, James Brown, to the meetings at Newberry, Warrington,
Huntingdon and Monallen, which were mostly to a good degree of satisfaction.

In my return, being humble and low in mind, and ruminating on my European journey,
which was before me, my spirit seemed to sink,
and my affection to my dear wife and family, and friends,
so awakened upon me that it looked to me impossible to part from them and live.
But endeavouring to retire, blessed be the name of the Lord, the helper of his people,
by whose power a silence was known, and by a gentle, instructive, inward voice,
my attention was gained, and my mind diverted from its pain by the following query:
"`Suppose you should lend a valuable thing to a neighbour of yours,
to be returned on demand, and you should favour him therewith from time to time,
not only one year, but seven, and then should see cause to demand it to be resigned;
would you not think that neighbour ungrateful, if he did not resign it cheerfully,
and with thankfulness and acknowledgment suitable to your kindness?`"
The proposition demanded my assent,
and my understanding was fully opened by the following application:
"`All that you enjoy is mine, do you love these things more than me?
If not, why is it so hard for you to resign all to follow me?
Which made me cry.
Lord! enable me, and I will follow you, it is only by your strength I can do it.`"
By the gracious help of Christ, my great and good Master,
I felt a humble resignation to his will, who being all things to his people,
is worthy to be followed and obeyed forever.
I was led to believe this was the instruction of his blessed spirit to me,
and as I had much comfort and satisfaction thereby, I am free to leave it as a hint,
that others under trials of what kind soever,
may be encouraged to look unto him for help, who is the Lord,
mighty to save and able to deliver to the uttermost all who sincerely trust in him.

My certificate being signed in the second month,
I attended our quarterly meeting at Concord in the third month,
and went to Philadelphia to seek for a passage, and with my brother, William Brown,
found one to our liking and to the satisfaction of Friends, which we also valued.
I then returned home, waiting until the ship was nearly ready to sail,
and during that time visited several neighbouring meetings,
taking leave of my neighbours and friends; and on the 1st day of the fourth month, 1750,
taking leave of my dear wife and aged mother, I left home before sun-rise,
and went to Philadelphia that night.
I spent the next day in visiting some of my acquaintances,
and on the first of the week attended three meetings; in the morning at the Bank,
which was a satisfactory good meeting,
wherein Friends were exhorted to attend on the gift of God,
for instruction and ability to perform every good word and work,
and in the afternoon and evening at the Market Street house,
which though not quite so open as the other, were in the main solid good meetings.
