== Chapter V.

[.chapter-synopsis]
* His attending the quarterly meetings at Philadelphia and Concord
* The yearly meeting at Philadelphia and quarterly meeting at Shrewsbury in New Jersey
* An account of an exercise attending his mind relating to the war and public commotions
* A conference of several Friends thereon, with their address to the Assembly of Pennsylvania on the subject, and an epistle to Friends in that province, in the year 1755
* His attendance of the general spring meeting in Philadelphia, in 1756, and some account of the calamities of the Indian war in Pennsylvania
* An account of the yearly meeting in Philadelphia the same year
* A relation of a visit of Peter Gardiner to Friends in Scotland
* A brief account of an Indian treaty at Easton, in 1757
* Some sentences expressed in two of his public testimonies.

Our yearly meeting for worship at Nottingham, was held in the week after I landed,
and I was greatly rejoiced to see many of my friends and acquaintances there.

In the eleventh month following I went up to the quarterly meeting in Philadelphia,
and returned to ours at Concord, where also was Samuel Fothergill.
It was a very large meeting,
in which he was divinely opened in speaking to
the state of Friends in his public ministry,
and serviceable in the discipline;
he also attended our general meeting in the same month at London-grove,
which was large and profitable; then went towards Lancaster,
on his way to the Southern provinces.

I spent this winter mostly at and near home,
at times attending some neighbouring meetings, until towards the spring,
when I took a small journey to seven or eight others.

During my late travels in Europe,
beholding the declension of many of the professors of truth
from the ancient simplicity in habit and deportment,
I sometimes was ready to cry out and say, O Pennsylvania!
May your inhabitants be forever strangers to the vanities of the world,
and the professors of truth keep their garments clean from the spots thereof,
pride and superfluity of every kind; but now with sorrow of heart,
I thought I beheld many of the youth in our Society taking their flight as into the air,
where the snares of the prince of the power thereof are laid to catch them;
some of whom are already much ensnared to their unspeakable hurt,
and their demeanour and habit being exceedingly altered in a little more than four years;
yet to my comfort I saw a few, who by walking in the light,
had escaped the wiles of Satan and were growing in the truth.

In the fourth month, 1755, I attended the general annual meeting at Duck Creek,
also meetings at Little Creek and George`'s Creek,
the last of which was more open than I expected, several of other societies being there,
who behaved orderly.
I spent most of the summer at home,
diligently attending our meetings for worship and discipline,
and had to observe that the greater part of the members of our meeting,
were for some time remarkable in their care to come together near the hour appointed,
and we had some precious opportunities, many of which were held in silence.
I often saw it to be a time of renewed visitation to many,
which if not carefully improved, would not be continued very long;
but that a more trying season would overtake us,
of which I was sometimes led to speak as truth opened,
wherein the door of outward ministry would be more closed up,
which would prove the religion of the professors of truth,
and manifest what they attended meetings for,
whether to wait upon God for the spiritual bread, or on man for outward ministry.

In the ninth month I attended our yearly meeting in Philadelphia,
which was large and solid, wherein many weighty matters under consideration,
were concluded to satisfaction;
and many Friends parted in a feeling sense of the overshadowing of the Heavenly wing,
with reverent thankfulness of heart.

In the tenth month I attended Shrewsbury quarterly meeting in East Jersey,
at which also were our friends John Evans and Joseph White.
It was large, the sittings thereof being favoured with a degree of the Divine presence.
We also attended the monthly meeting there and had some service;
Friends were encouraged to deal with such who were disorderly in conduct,
there having been some slackness among them in that respect.

As the sound of war and public commotions had now entered the
borders of these heretofore peaceful provinces,
some solid thoughts attended my mind at Shrewsbury,
respecting the nature of giving money for the king`'s use,
knowing the same to be intended for the carrying on of war.
John Evans accompanying me homewards, we took three meetings in our way,
the last being at Evesham;
at which place I told him I felt an engagement of mind to go to Philadelphia,
and he consented to go with me.
When we came to the city the assembly of Pennsylvania was sitting,
and we understood that a committee of the house was appointed to
prepare a bill for granting a sum of money for the king`'s use,
to be issued in paper bills of credit,
to be called in and sunk at a stated time by a tax on the inhabitants;
on which account several Friends were under a close exercise of mind,
some of whom being providentially together, and conferring on the subject,
concluded it was expedient to request a conference with those
members of the house who were of our religious profession.
On applying to the speaker, who was one himself,
we obtained an opportunity of conversing with them;
after which we believed that an address to the assembly would be necessary;
but we then being only few in number, consulted with several weighty Friends thereon;
at length upwards of twenty met together,
who after solidly considering the matter before us,
were all of opinion that an address to the assembly would be proper and necessary;
whereupon one was drawn up, which being considered, agreed to and signed by all of us,
we went together to the house, and presenting it to the speaker,
it was read while we were present; a copy whereof here follows:

[.embedded-content-document.address]
--

[.blurb]
=== To the Representatives of the freemen of the province of Pennsylvania, in general assembly met: The address of some of the people called Quakers, in the said province, on behalf of themselves and others.

The consideration of the measures which have lately been pursued, and are now proposed,
having been weightily impressed on our minds,
we apprehend that we should fall short of our duty to you,
to ourselves and to our brethren in religious fellowship,
if we do not in this manner inform you,
that we shall at all times heartily and freely contribute,
according to our circumstances, either by the payment of taxes,
or in such other manner as may be judged necessary, towards the exigencies of government,
and sincerely desire that due care may be taken, and proper funds provided,
for raising money to cultivate our friendship with our Indian neighbours,
and to support such of our fellow subjects, who are or may be in distress,
and for such other like benevolent purposes.
Yet as the raising sums of money, and putting them into the hands of committees,
who may apply them to purposes inconsistent with the peaceable testimony we profess,
and have borne to the world, appears to us in its consequences,
to be destructive of our religious liberties;
we apprehend many among us will be under the necessity of suffering,
rather than consenting thereto, by the payment of a tax for such purposes;
and thus the fundamental part of our constitution may be essentially affected;
and that free enjoyment of liberty of conscience by degrees be violated,
for the sake of which, our forefathers left their native country,
and settled this then a wilderness.

We sincerely assure you, we have no temporal motives for thus addressing you;
and could we have preserved peace in our own minds, and with each other,
we should have declined it; being unwilling to give you any unnecessary trouble,
and deeply sensible of your difficulty in discharging the trust committed to you,
irreproachable in these perilous times.
This has engaged our fervent desires, that the immediate instructions of Supreme wisdom,
may influence your minds; and that being preserved in a steady attention thereto,
you may be enabled to secure peace and tranquillity to
yourselves and those you represent,
by pursuing measures consistent with our peaceable principles;
and then we trust we may continue humbly to
confide in the protection of that Almighty power,
whose providence has heretofore been as walls and bulwarks round about us.

[.signed-section-context-close]
Philadelphia, Eleventh month 7th, 1755.

--

A bill was however brought in by the committee of the assembly,
and a law enacted for granting a large sum of money proposed to be sunk by a general tax.

When this service before related was over,
in which I apprehended it my duty to be concerned, I returned home;
but a close exercise remained on me as well as on the minds of several other Friends,
on account of the law now passed;
and as care had been taken to apprise the assembly of
the solid sentiments of Friends thereon,
that we apprehended our charter respecting liberty of conscience,
would thereby be affected; therefore a large committee of the yearly meeting,
which had been appointed to visit the quarterly and monthly meetings,
met at Philadelphia in the twelfth month, had a conference thereon,
together with another committee nominated to correspond
with the meeting for sufferings in London;
and after several solid opportunities of waiting on the Lord to be rightly instructed,
and being favoured with a renewed sense of the ownings of truth,
many Friends thought they could not be clear as faithful watchmen,
without communicating to their brethren their mind and
judgment concerning the payment of such a tax;
for which purpose an epistle was prepared, considered,
agreed to and signed by twenty-one Friends;
copies thereof were concluded to be communicated to the monthly meetings,
being as follows:

[.embedded-content-document.epistle]
--

[.letter-heading]
An epistle of tender love and caution to Friends in Pennsylvania.

[.salutation]
Dear and well beloved Friends,

We salute you in a fresh and renewed sense of our heavenly Father`'s love,
which has graciously overshadowed us in several weighty
and solid conferences we have had together,
with many other Friends,
upon the present situation of the affairs of the Society in this province;
and in that love, we find our spirits engaged to acquaint you,
that under a solid exercise of mind to seek for council and direction,
from the High Priest of our profession, who is the Prince of peace,
we believe he has renewedly favoured us with strong and lively evidences,
that in his appointed time, the day which has dawned in these latter ages,
foretold by the Prophet, wherein swords should be beaten into plough-shares,
and spears into pruning-hooks, shall gloriously rise higher and higher;
and the spirit of the gospel, which teaches to love enemies, prevail to that degree,
that the art of war shall be no more learned.
It is his determination to exalt this blessed day, in this our age,
if in the depth of humility we receive his instructions and obey his voice.
And being painfully apprehensive,
that the large sum granted by the late act of assembly for the king`'s use,
is principally intended for purposes inconsistent with our peaceable testimony;
we therefore think, that as we cannot be concerned in wars and fightings,
so neither ought we to contribute thereto, by paying the tax directed by the said act,
though suffering be the consequence of our refusal,
which we hope to be enabled to bear with patience.
Though some part of the money to be raised by the said act,
is said to be for such benevolent purposes,
as supporting our friendship with our Indian neighbours,
and relieving the distresses of our fellow subjects,
who have suffered in the present calamities, for whom our hearts are deeply pained,
and we affectionately, and with bowels of tenderness, sympathize with them therein;
and we could most cheerfully contribute to those purposes, if they were not so mixed,
that we cannot in the manner proposed, show our hearty concurrence therewith,
without at the same time assenting to, or allowing practices,
which we apprehend contrary to the testimony which the Lord has given us to bear,
for his name and truth`'s sake.

Having the health and prosperity of the Society at heart,
we earnestly exhort Friends to wait for the appearing of the true light,
and stand in the counsel of God,
that we may know him to be the Rock of salvation and place of our refuge forever.
Beware of the spirit of the world, that is unstable,
and often draws into dark and timorous reasonings;
lest the god thereof should be permitted to blind the eye of the mind.
Such, not knowing the sure foundation, the Rock of ages,
may partake of the terrors and fears,
which are not known to the inhabitants of that fold,
where the sheep and lambs of Christ ever had a quiet habitation,
with a measure of which a remnant have to say, to the praise of his name,
they have been blessed, in this day of distress.

Our fidelity to the present government,
and our willingly paying all taxes for purposes
which do not interfere with our consciences,
justly exempt us from the imputation of disloyalty; and we earnestly desire that all,
who by a deep and quiet seeking for direction from the holy Spirit, are, or shall be,
convinced that he calls us as a people to this testimony,
may dwell under the guidance of the same Divine Spirit,
and manifest by the meekness and humility of their conduct,
that they are really under that influence;
and therein may know true fortitude and patience to bear that,
and every other testimony committed to them, faithfully and uniformly.
And may all Friends know their spirits clothed with true charity,
the bond of Christian fellowship; wherein we again tenderly salute you,
and remain your friends and brethren.

[.signed-section-context-close]
Philadelphia, Twelfth month 16th, 1755.

--

In the year 1756 I attended our general spring meeting in Philadelphia,
at which we had the company of our dear friends, Samuel Fothergill and Catherine Payton, from
from Great Britain, and her companion, Mary Peasley, from Ireland,
and it was a solemn edifying meeting.
The Indians having burnt several houses on the frontiers of this province,
also at Gnadenhutten, in Northampton county,
and murdered and scalped some of the inhabitants; at the time of this meeting,
two or three of the dead bodies were brought to Philadelphia in a wagon,
with an intent as was supposed, to animate the people to unite in preparations of war,
to take vengeance on the Indians, and destroy them.
They were carried along several of the streets, many people following,
cursing the Indians, and also the Quakers,
because they would not join in war for destruction of the Indians.
The sight of the dead bodies and the outcry of the people,
were very afflicting and shocking to me.
Standing at the door of a Friend`'s house as they passed along,
my mind was humbled and turned inward, and I was made secretly to cry,
"`What will become of Pennsylvania?`"
For it felt to me that many did not consider that the sins of the inhabitants, pride,
profane swearing, drunkenness, with other wickedness,
were the cause why the Lord had permitted this calamity and scourge to come upon them.
The weight of my exercise increasing as I walked along the street;
at length it was said in my soul, "`This land is polluted with blood,
and in the day of inquisition for blood,
it will not only be required at the frontiers and borders,
but even in this place where these bodies are now seen.`"
I said within myself, "`How can this be?
since this has been a land of peace,
and as yet not much concerned in war;`" but as it were in a
moment my eyes turned to the case of the poor enslaved Negroes.
And however light a matter they who have been
concerned in it may look upon the purchasing,
selling, or keeping those oppressed people in slavery, it then appeared plain to me,
that such were partakers in iniquity,
encouragers of war and the shedding of innocent blood, which is often the case,
where those unhappy people are captivated and brought away for slaves.
The same day I went to Pine Street meeting in an exercised, mournful state of mind,
and thought I could be willing to sit among the people undiscovered.

I attended our quarterly meeting at Concord in the fifth month,
and in a few days after went to the yearly meeting at West River, in Maryland,
which was large and in a good degree satisfactory.
Then went to meetings at Herring Creek and the Clifts,
and returned the following first-day to West River,
where I had a good opportunity to clear myself towards Friends of that place;
being concerned on account of several of the elders,
who did not conduct so exemplarily as they ought before the youth.
I left them relieved in my mind, and returned home, taking several meetings in my way.

In the ninth month I was at our yearly meeting for Pennsylvania and New Jersey,
held this year at Burlington, which was large and edifying;
many weighty matters being in much brotherly love resulted to satisfaction.
Our friend, Thomas Gawthrop, from Great Britain, was there.
In the time thereof, our worthy friend and brother, John Evans, of Gwynnedd,
departing this life, Thomas and I went to attend the burial,
on which solemn occasion he had a seasonable opportunity to
remind a large gathering of people of their latter end;
and I thought it was a solid time.

Being one of the committee appointed by the yearly
meeting to visit the quarterly and monthly meetings,
I was careful in attending on that service as way was opened,
in company with other Friends, as likewise our meeting for sufferings,
established this year, and held monthly in Philadelphia,
frequently taking meetings in my way going and returning.
In the spring of the year 1757,
I also attended our general meeting for ministers and elders, held at Philadelphia.

[.asterism]
'''

I have often remembered a remarkable account given me, when in England, by our ancient,
worthy Friend, John Richardson,
which made such an impression on my mind that I committed it to writing,
and think it is worthy to be preserved, being nearly as follows:

Peter Gardiner, a Friend who lived in Essex, England,
had a concern to visit Friends in Scotland; but being low in circumstances,
and having a wife and several children, was under discouragement about it.
The Lord in mercy condescended to remove his doubts,
by letting him know he would be with him, and though he had no horse to ride,
and was but a weakly man, yet that he would give him strength to perform the journey,
and sustain him so that he should not be in need of what was sufficient.
Having faith in the Divine promise,
he laid his concern before the monthly meeting he belonged to, with innocent weight;
and friends concurring with him therein,
he took his journey along the east side of the nation, through Norfolk,
Lincolnshire and Yorkshire, and coming to a weekday meeting at Bridlington,
where John Richardson then dwelt, he lodged at his house.
In the evening the doors being shut, Peter asked him if any Friend lived that way,
pointing with his finger; John told him he pointed towards the sea,
which was not far from there.
He said he believed he must go and see somebody that way in the morning.
John asked him if he should go with him?
he said he believed it would not be best, and so went to bed.

In the morning when John`'s wife had prepared breakfast,
he thought he would go and see if the Friend was well, but found that he was gone;
at which John Richardson wondered.
Soon after, Peter came in, to whom John said, You have taken a morning walk,
come to breakfast.
Before they had done eating, a Friend from the quay, or harbour,
which lay in the direction that Peter Gardiner pointed to over night, came in, and said,
'`I wonder at you, John,
to send this man with such a message to my house;`' and related as follows:
That he came to him as he was standing at the fish-market-place, looking on the sea,
to observe the wind, and he asked him if he would walk into his house?
To which Peter answered that he came for that purpose;
this was in the twilight of the morning.
When he went into the house, Peter inquired whether his wife was well;
to which the man answered, that she was sick in bed,
and invited him to go in and see her; he said he came so to do.
Being conducted into the chamber where the sick woman was, he sat down by her;
and after a short time told her,
that the resignation of her mind was accepted instead of the deed,
and that she was excused from the journey which had been before her,
and should die in peace with God and men.
Then turning to the man, her husband, he said,
"`Your wife had a concern to visit the churches in another country beyond the sea,
but you would not give her leave, so she shall be taken from you; and behold,
the Lord`'s hand is against you, and you shall be blasted in whatsoever you do,
and reduced to beg your bread.`"
The man seemed angry with John Richardson, who said to him, "`Be still,
and weigh the matter, for I knew not of the Friend`'s going to your house;
but thought he was in bed,
and did not inform him about you nor your wife;`" at which he went away.

Peter pursued his journey towards Scotland,
John Richardson and another Friend going with him to Scarborough on horseback,
for he would not let them go on foot with him,
he kept before them as fast as they chose to ride; and when they had gone about half way,
he gained on them, and John said he was filled with admiration,
for he seemed to go with more slight and ease than ever he had seen any man before.
Riding fast to overtake him,
he thought he beheld a small white cloud as it were encompassing his head;
and when he overtook him John said to him, You do travel very fast.
Peter replied, My Master told me, before I left home, that he would give me hinds feet,
and he has performed his promise to me.

When they came in sight of Scarborough, Peter said,
take me to a Friend`'s house if there is any there.
John replied, I will take you to the place where I lodge, and if you are not easy there,
I will go until we find a place, if it may be.
So John Richardson took him to his lodgings, and just as they entered the door,
they heard someone go up stairs,
and the woman Friend of the house coming down with a neighbour of hers,
invited them to sit down.
In a short time Peter said, Here is light and darkness, good and bad in this house.
After the woman had got them some refreshment, she came and asked John,
Who have you brought here?
A man of God, he replied.

Having a meeting at Scarborough the next day, John Richardson stayed with him,
and said he had good service; he also went with him to several Friends`' houses there,
and he frequently spoke his sense of the state of the families;
but as they were about entering one house, Peter stopped, and said,
My Master is not there, I will not go in, so they turned away.

Next morning at parting, John Richardson asked him how he was prepared for money,
telling him the journey was long.
Peter answered, I have enough, my Master told me I should not go without,
and a bit of bread,
and some water from a brook refreshes me as much as a set meal at a table.
John insisted to see how much money he had, which was but two half-crowns;
upon which John took a handful of small pieces out of his pocket,
and forced Peter to take them, telling him it was as free to him as his own,
for so the Lord had put it into his heart.
Thus they parted, John and the other Friend returning home.

In about two weeks afterwards the man`'s wife, before mentioned, died,
as Peter had foretold.
At that time, the man had three ships at sea; his son was master of one,
and a second son was on board of another, and in their voyages they were all wrecked,
or foundered, and their cargoes chiefly lost;
his two sons and several of the hands being drowned.
The man soon after broke and could not pay his debts,
but came to beg bread before he died, though he had been in good circumstances,
if not very rich.

Some time after, John Richardson heard that Peter Gardiner died in Cumberland,
on his return from Scotland, and being attached to him in near affection,
he went to inquire how he ended.

John Bowstead, a noted Friend near Carlisle,
informed him that Peter had been through Scotland, and came to Carlisle,
and the small-pox being there, he took the infection very suddenly, and lay ill with it.
John Bowstead went, just as the pock was coming out on him, and took him to his house;
they never came out kindly, but swelled him very much, so that he was blind,
and died about the seventh day.
He was quite sensible to the last, and knew the states of those who came to see him.^
footnote:[For a further account of Peter Gardiner`'s remarkable journey in Scotland,
see the appendix.]

[.asterism]
'''

[.offset]
+++[+++Returning to John Churchman`'s Journal:]

On the 12th of the seventh month, this year,
I left home in order to attend a treaty to be
held between the Indians and our government,
at Easton, in Northampton-county; and proceeded to Philadelphia,
where I was present at several conferences with Friends;
the governor having declared his dislike to their attendance at that treaty,
or their distinguishing themselves by giving the Indians any presents.
The result was,
that as mutual tokens of the revival of ancient
friendship had passed between Friends and the Indians,
with a view to promote a general peace,
it would be of bad consequence now to neglect or
decline attending on this important occasion;
though it was judged necessary for Friends to act with great caution.
We therefore set forward, and taking a meeting at Gwynnedd in the way,
reached Easton on fourth-day, the 21st of the month,
the governor having arrived about two hours before us;
but did not enter on business that day.

Many Friends from Philadelphia and other parts being here collected,
we held a meeting on fifth-day, which was low and dull, things appearing very dark.
In the afternoon, the Indians with Teedyuscung, their king, or chief man,
went to the governor and signified the sincerity of
their intentions to promote the good work of peace,
when he delivered several strings and belts of wampum,
in order to certify the full power and authority given to Teedyuscung for that purpose,
who also desired that as things had heretofore been misunderstood, or forgotten,
he might have the liberty to choose a clerk to take the minutes of
the transactions at this treaty on behalf of the Indians;
which was put off by the governor at that time.

Next morning Teedyuscung renewed the same request, but was again put by:
then the Indians began to be very uneasy,
from an apprehension that some people from the
Jersey side of the river were likely to rise,
with a design to destroy them; but on going to converse with them,
and giving them some pipes and tobacco, which they were told was a present from Friends,
they became more quiet, and seemingly pacified;
this day and the next there was little business done.

On first-day, the 24th of the month.
Friends held a public meeting in the treaty-booth, to pretty good satisfaction,
to which a great number of people came, two Friends having acceptable service therein.
In the afternoon Friends`' met again; but there seemed so great a cloud over the meeting,
by reason of a raw careless spirit prevailing over the minds of the people,
as though there was no God, notwithstanding his judgments are so conspicuous,
especially in these parts of the country, that life did not arise in this meeting.
About sunset this evening,
we heard that the Mohawk Indians had requested to have a fire made to dance round,
which the governor allowed, as he had the evening before to the Delawares,
with both which we were very uneasy,
as the tendency thereof was to make the Indians drunk;
but no endeavours of ours could prevent it.

On second-day morning the governor agreed to
allow the Indian king to choose himself a clerk,
which he did, and about one o`'clock that day the treaty was first opened in public,
when Teedyuscung was desired fully to inform, with an open heart,
wherein he apprehended the Indians had been defrauded by the proprietaries,
to which he answered that he would tomorrow; but they must first clean up the blood,
as he expressed it, and bury the dead bodies.
Next day being again met, the king said, that according to his word,
he had met some of the several nations to do what they could for settling peace;
but in the first place he had seen and considered the
black cloud that hung over the land,
the blood and bodies of the people who had suffered.
I have gathered up the stained leaves, the blood and dead bodies, and looked round about;
when all seemed terrible, so that I could find no place to hide them; but looking up,
I saw the great and good Spirit above.
Let us heartily join in prayer to Him,
that he may give us power to bury all these things out of our sight,
that neither the evil spirit, nor any wicked person may ever be able to raise them;
that we may love like brethren, and the sun may shine clear upon us, that we, our wives,
our young men and children may rejoice in a lasting peace,
that we may eat the fruits of the earth, and they may do us good,
so that we may enjoy peace in the day time, and at night lie down and sleep in it.
He gave a belt of seventeen rows of wampum.

By another belt he told the governor, that he took him by one hand,
and the Five Nations of Indians and their allies took him by the other, therefore,
said he, let us all stand as one man, with one heart and one mind,
and join in this good work of peace.
When we intend to lift or remove a great weight, we must be strong,
if all do not exert themselves we can never do it; but if all heartily join,
it is easy to remove it.
Our forefathers did not proceed right when they met together,
they looked at the earth and things present, which will soon pass out of our sight;
but did not look forward to the good of posterity.
Let us set out right, and do better than they did,
that a peace may be settled which may last to our children.

He next acquainted the governor,
that one of the messengers who had gone on a late message to the Indians afar off,
meaning Moses Tatamy`'s son, was shot on his return by one of our young men,
and lay in a dangerous condition; and by a string of wampum insisted, that if he died,
the other should be tried by our law, and suffer death also;
and that some of their people should be present,
to be able to inform the other nations of Indians of the justice done.
He also revived the ancient agreement,
that if any of them should commit the like offence,
the criminal should be delivered up to be tried according to our laws,
and suffer death in the same manner.

On fourth-day there was no public treaty, things seemed in much confusion and very dull;
but Friends kept quiet.
Next day I found myself much indisposed, and therefore thought it best to leave Easton;
but before I left it Friends had a solemn opportunity together,
at which time I thought I saw, that the working of the dark revengeful spirit,
which opposed the measures of peace,
was one reason why Friends were so baptized into distress and suffering,
of which I made some mention to Friends, and that if they kept quiet,
the clouds as to them would somewhat break away;
Daniel Stanton had a solemn time in supplication.
After this meeting taking leave of Friends, I rode to Richland,
and though my distemper increased and I was very ill, I pursued my journey the next day,
and the day following reached Philadelphia,
where I was carefully attended through a time of tedious and close affliction.
My dear wife coming to me in my illness, was also taken with the same disorder,
that we were not able to move homewards until the 23rd of the eighth month,
but through the goodness of kind Providence in supporting us,
got to our own habitation the next day in the evening.

After about a weeks`' stay I set out again to attend the
meeting for sufferings in Philadelphia,
though very weak, and after tarrying part of three days in town,
went to attend the monthly meetings in Bucks county,
of which I had a view while I lay sick;
when it appeared to me the way to recover my strength
was to be faithful to every discovery of duty.
In company with several other Friends appointed by the yearly meeting,
I visited the several monthly meetings in that county,
in some of which a degree of the Divine presence being felt, was cause of thankfulness;
though at one of them we had some remarkably close work,
both in the time of worship and discipline.

Returning to Philadelphia much recovered,
I spent five days there attending meetings as they came in course;
and then went to Newtown meeting in Chester county, which was small,
there being an evident slackness of attending week-day meetings.
From there I went to Uwchland, to the marriage of William Trimble and Phebe Thomas,
which was a good meeting,
where I met my dear wife on her way to the yearly meeting at Philadelphia;
and after attending a meeting at Merion, we went into the city the next evening.
Our friends, Thomas Gawthrop, Samuel Spavold,
William Reckitt and others from Great Britain, also Thomas Nicholson from North Carolina,
were at this yearly meeting, which was large and satisfactory,
holding from the 17th to the 24th of the ninth month, 1757.

Before I left home to attend the late Indian treaty at Easton, I thought in my sleep,
that I was riding eastward in the twilight, and saw a light before me towards sun-rising,
which did not appear to be a common light.
I observed the appearance of something therein,
whereat the beast I rode was much affrighted, and would have ran from it,
which I knew would be in vain; for I took it to be an angel,
whose motion was as swift as thought,
so rather stopped and reined in my beast towards it.
It was encompassed with a brightness like a rainbow,
with a large loose garment of the same colour down to the feet.
It rather seemed to move than to walk,
and stood still in the midst of many curious stacks of corn; and smiling on me,
asked where I was going.
I said towards yonder building, which I thought was an elegant one directly before me;
it seemed to approve my way and vanished upwards.
Then I awakened and had particularly to remember
the complexion of this angelic apparition,
which was not much different from one of the
Indians clean washed from his grease and filth;
remembering my dream very fresh, when I had seen the Indians at the treaty,
and had heard some matters remarkably spoken to by some particulars of them,
I was made to believe it was not unreasonable to conclude,
that the Lord was in them by his good Spirit, and that all colours were equal to him,
who gave life and being to all mankind;
we should therefore be careful to examine deeper than the outward appearance,
with a tender regard to station and education,
if we desire to be preserved from error in judgment.

[.asterism]
'''

[.offset.emphasized]
The following sentences being delivered by John
Churchman in two of his public testimonies,
were soon after committed to writing by a Friend who was present,
and appearing worthy to be further preserved, are now communicated.

[.embedded-content-document]
--

In a first-day meeting at East Nottingham, the 19th of the twelfth month, 1756,
he expressed nearly as follows:
"`I felt my mind in this meeting remarkably drawn from outward observation,
and was commanded to centre in deep and awful silence,
wherein there was such a flowing of good will to mankind,
as is scarcely to be uttered by tongue.
Thus centering with diligent attention,
I thought I felt a strong power of darkness and stupid ignorance,
seemingly combined to make war against this solemn attention of mind;
yet after patiently waiting some time, to my comfort I felt a secret victory,
and the darkness vanished.
Then a voice was uttered in me, attended, I thought, with Divine authority thus;
'`I will bow the inhabitants of the earth, and particularly of this land,
and I will make them fear and reverence me,
either in mercy or in judgment.`' Hereupon a prospect immediately opened to
my view of a day of calamity and sore distress which was approaching,
and in which the careless and stupid professors, who are easy,
and not concerned properly to worship and adore the Almighty,
and have not laboured to witness their foundation to be laid on Him the immovable Rock,
will be greatly surprised with fearfulness.
On the behalf of such, a cry and lamentation ran through me, thus; Alas for the day!
Alas for the day!
Woe is me!
And a voice which seemed to be connected with the foregoing, said further;
'`Yet once more, says the Lord, I shake not the earth only, but also heaven.
Not only the situation of those who know not any place of safety or refuge,
but that which is outward and earthly; but also those who assume a higher place,
and in their specious appearances and false pretences among men,
do value themselves on their assumed goodness,
and would eagerly be accounted of the highest rank,
and even place themselves among the saints,
and are by some accounted as stars in the firmament;
yet in the day of my power wherein I will shake the heavens and the earth,
those stars shall fall to the ground.`'

"`In the opening, something within me was ready to say, Amen so be it!
O Lord Almighty, cut short your work in the earth,
in order that you may put an end to sin and finish transgression, that your fear,
and the knowledge of you, may cover the earth, as the waters cover the sea.
Wherefore, my friends, the fervent desire of my soul is,
that all present may with diligence labour to have
their minds truly centered and humbled before God,
to know a being fixed on that foundation which only stands sure,
that in a time of outward distress, which perhaps may come in your day,
you may find a place of safety and refuge.`"

--

All which with more to the like effect, was delivered in great humility and brokenness.

At a week-day meeting at the same place, the 17th of the second month, 1757,
several persons by unseasonably coming in, interrupted the quiet of the meeting,
and he gave a suitable caution in that respect, in gentle winning terms,
reminding those met of the awfulness and solemnity which should
attend us when we approach the presence of Him who is most holy;
and in what reverence, fear and care, we ought to come together,
not forgetting the hour appointed; and then expressed nearly as follows:

[.embedded-content-document]
--

"`A certain sentence has been presented to the view of my mind,
which seemed to contain a gentle engaging caution, and matter of instruction to me,
attended with sweetness; which was, '`Work while it is day.`' Friends, this is our day,
wherein we ought to be diligent and industrious.
In the light of the day we may see and understand how to work, and what to do,
that at the conclusion we may obtain from the Master of the day, who dwells in light,
the answer of well done; for the night will come, wherein no man can work.
We are favoured with liberty in this day, to assemble together for worship unmolested;
and my hearty desire is, that we may properly improve this mercy;
for the time to some of us may come, before our day in this life is closed,
wherein this privilege may in some measure be taken from us.
Something in me would be ready to say,
'`The Lord forbid that it should be the case;`' but by reason of
the great declension which has overspread the church,
I hardly dare to expect any other.
Oh may we therefore be careful to prize the mercy of God,
and endeavour to gain an inheritance in the light, that when night overtakes,
and darkness as to the outward, may hang over us,
we may be favoured to withdraw into the sure hiding place, and know a quiet habitation!`"

--
