== Chapter VI.

[.chapter-synopsis]
* Visits to meetings in Pennsylvania and New Jersey
* also in Maryland and Virginia
* His apprehensions of duty to proceed on a visit to Barbados and resignation thereto, but at length became most easy to decline it
* The settlement of Uwchland monthly meeting with his epistle to Friends there
* Some weighty expressions uttered in the time of his sickness in the year 1761.

Having drawings in my mind to visit the meetings of
Friends in the counties of Philadelphia and Bucks,
and being under an appointment of the yearly meeting to
join with others in a visit to the monthly meetings,
I informed our monthly meeting at Nottingham,
with whose concurrence I left home on the 3rd of the twelfth month, 1757,
accompanied by a near relation, and attended Darby meeting on first-day, wherein,
though life and the power of truth seemed to be low,
I thought the humble waiters were encouraged.
We went to the evening meeting in Philadelphia;
next morning attended the meeting of ministers and elders,
and the day following a meeting at the Bank, also a meeting for sufferings;
and on fourth-day returned to Darby, to their monthly meeting,
where we found Friends under a strait about disowning one among them,
who denied the divinity of our Lord and Saviour Jesus Christ;
on whom they had bestowed much labour to convince him of his error.
The meeting ended well;
the company of the Friends who attended it being acceptable and of service.

We were next day at Haverford monthly meeting held at Radnor,
where the lively exercise of the discipline appeared to be very low,
yet I was glad I was there.
During the time of the business,
feeling a concern on my mind to appoint a meeting at Haverford, to be held the next day,
I proposed it for concurrence, which being readily agreed to,
we attended there accordingly, and had a large meeting much to satisfaction,
having great peace in observing the motion of Truth respecting this appointment.
On the following day accompanied by my friend, Hugh Evans,
I visited some ancient Friends, who by reason of old age and indisposition,
could not get out to meetings,
wherein I was favoured with that peace which I have often experienced
to attend the acceptable work of visiting the afflicted.

On first-day, after a satisfactory meeting at Merion,
I went to the evening meeting in Philadelphia,
in which Truth favoured with a degree of openness,
to the instruction and comfort of many.
On third-day afternoon, accompanied by my brother, William Brown,
went forward to Richland monthly meeting held on fifth-day,
where we had some close hard work,
which generally happens when a lifeless formal spirit has the
prevalence in managing the affairs of the church,
for lack of feeling after and waiting for the true authority, even the power of God;
yet we were glad that we were there.
My brother returned home, but the rest of us went to an appointed meeting at Plumstead,
which, though the weather was severely cold, was large and comfortable,
in the sense whereof we were thankful to the Author of all good.

The meeting next day at Buckingham, was small but satisfactory.
The severity of the weather is not a sufficient excuse for the
Lord's panting children to neglect public worship,
which is a duty incumbent on us and due to his glorious name.
At Wrightstown meeting the next day,
the Master of our assemblies was pleased to appear in an eminent manner,
to the comfort of the poor, instruction of the inquirers, rebuke of the backsliders,
and edification of many;
for which the sacrifice of thanksgiving and praise was offered to Him,
who alone is worthy forever.

After this meeting I felt the value of that peace,
which by the humble is better felt than expressed.
We had next a good meeting at Makefield, at which were many seeking tender young people;
then attended the Falls preparative meeting, which was satisfactory,
a comfortable degree of unity subsisting among Friends.
Our next meeting was at Bristol, in which after a dark distressing time in silence,
what I had to communicate, was introduced by a question thus;
Are you sound in faith and practice?
I was led to set forth, that to profess and acknowledge even sacred truth,
without a life of self-denial, with an answerable honest conduct, was no way sufficient;
that being a dead faith,
which produces not good works in him who says he believes
showing what stumbling-blocks nominal professors are,
who by their example plainly manifest that they
are not possessors of what they profess to have,
and are the greatest enemies the truth has,
which I was doubtful was the case with some among them.
I had peace in this plain dealing.
Our next was a laborious meeting at Byberry, yet yielded a degree of the same peace;
a Friend afterwards told me that the state of the meeting was clearly spoken to,
which I relate not for any praise to man;
but that it was an additional confirmation of the Lord's sufficiency to his own work;
and when we are weak, foolish, or contemptible in our own esteem, his strength appears,
and his wisdom inspires with true knowledge, whereby he magnifies himself.
We went home with our friend, James Thornton, and next day to Horsham,
where was a large and good meeting;
after which we had a comfortable time in the family of John Cadwalader.

Next day we attended the monthly meeting at Abington,
in company with Samuel Eastburn and Joseph White; we found things low here,
because of a lack of that strength in which stands the authority of the church;
it is only the pure wisdom from above, that preserves Friends in peace, meekness,
gentleness, and unanimity in the distribution of right judgment in the church of Christ.

We were next day at Gwynnedd monthly meeting,
which was a precious time through the power of that sacred name,
which is as ointment poured forth,
the savour whereof continued through both worship and discipline,
in which the faithful were mutually comforted.
We went to Ellen Evans', and had an evening meeting, some of the neighbours coming in;
several Friends were much enlarged in counsel,
and the opportunity ended in solemn prayer and thanksgiving.
We went from there to Exeter monthly meeting, which ended to satisfaction in the main;
then home with our friend, Ellis Hugh,
where Joseph White and Samuel Eastburn left us to return homewards.
My companion and I proceeded to Reading, and had a public meeting in the court-house,
which I thought was pretty well considering the company, many loose people attending;
but Truth seemed to come into dominion and quieted them,
that the meeting ended in a degree of awful sweetness.

On first-day, being the first of the new year, 1758, we were at Maiden Creek meeting,
which although a low time, afforded peace and comfort,
from a prospect that there were among the youth in particular,
some true branches of the Vine of life,
who could not be satisfied without the living sap from the holy Root,
and in the Lord's time would be favoured therewith,
if there was a patient waiting for that springing season.
We returned to Reading that evening,
to a meeting held by appointment at a Friend's house,
for the members of our Society in that town, in the attendance of which I found peace;
crossing the river Schuylkill, we were next day at Robinson, or the Forest meeting,
after which I was much humbled in a sense of the great
condescension and mercy of the Lord our God,
who was pleased to renew the reaches of his power to several,
who had many years made profession of the pure truth,
and yet dwelt in that which is impure, as drinking to excess and other evils,
some of whom I knew, but did not know that they were there till the meeting was over;
the weak were strengthened and the humble seekers encouraged,
and great love flowed towards the youth.

Returning again over Schuylkill, we went to that called Evans' meeting,
which was very open for doctrine, several not of our Society being present:
the first sentence that appeared in my view, was,
"`Many are called, but few are chosen,`" attended with such weakness,
and such a sense of my own foolishness and inability for handling that subject,
that I was afraid,
because I had a secret apprehension that some would
incline to make an advantage of those words,
"`but few are chosen,`" in applying them to strengthen
themselves in the corrupt manner in which they hold election;
but it appeared to me that because "`All have not obeyed,`"
was the reason why so few are chosen.
My mouth was opened in fear, even to trembling,
yet with a secret hope and confidence that the Lord would be mouth and wisdom,
with desires that he would bind my attention to his own immediate instruction,
that the language of his Spirit only might be uttered by me;
and he was pleased to magnify his own truth in the opening of these passages.
I give this hint, that they who are concerned in the ministry may humbly trust in God,
and not lean to their fears, knowledge, experience, or wisdom,
in opening the mysteries of the gospel, but confide in the key of David;
for when it opens none can shut.

Next day we were at Providence meeting, which was poor, and truth low,
yet peace was afterwards measurably enjoyed,
from an evidence of having been honest according to the ability given.
On the day following, at Plymouth,
faithful Friends were comforted in the gracious condescension of our holy Head,
who was pleased to favour with the aboundings of the life and love of Truth;
we then returned to Philadelphia with thankful hearts for the evidence of peace.
My companion returning home,
I went in company with my brother on first-day morning to Frankford,
having felt an engagement for a considerable time to visit that meeting.
A sense of the declension of Friends in this place,
both in respect to numbers and the life of religion, was cause of heaviness of heart;
but having performed my visit in faithfulness, according to ability,
I returned with a degree of peace to the evening meeting in the city,
which was comfortable.
I remained there until the fifth-day of the week,
in which time I attended the usual meetings; one with the Negroes much to satisfaction,
and also the meeting for sufferings; and got safely home on seventh-day,
the 14th of the first month;
having travelled in this journey about four hundred and ten miles.

On the 22nd of the second month,
I again left home in order to attend the quarterly meeting at Burlington,
and some particular meetings in New Jersey,
as well on account of the yearly meeting's appointment, as my own sense of duty,
in which I had the approbation of our monthly meeting signified by a minute.
I attended the monthly meeting in Philadelphia with some degree of satisfaction;
then taking Chester or Adams' meeting in New Jersey,
reached Burlington on first-day evening; the next day being the quarterly meeting,
at which I had some service.
After staying the youths' meeting, I went to a meeting on fourth-day at a school-house,
where several Friends met,
also many others who perhaps had not been at any place of worship for sometime,
and were easy about religion,
to whom it became my concern to show how disagreeable and loathsome that state was;
"`I know your works, that you are neither cold nor hot; so then,
because you are lukewarm, and neither cold nor hot, I will spew you out of my mouth.`"
It opened to me that a lukewarm condition, holding a profession of religion,
so as to take it ill not to be thought a Christian,
but at the same time remaining easy and not in earnest to experience the life, virtue,
and power of Christianity; not so cold as to forget the name,
nor so hot or zealous as to witness the life of true religion,
was very displeasing to the Almighty.
A good degree of power attended the opening, and in treating on that passage,
with much love to such lukewarm professors,
which reached and tendered several beyond expectation; but no praise to man,
though he may will or run, but to God who shows mercy.

At Chesterfield monthly meeting, my friend John Woolman met me the next day;
a raw company attending on account of a proposal or two for marriage,
which I suppose they expected to be there presented;
it was a time somewhat low and distressing.
The advice of the yearly meeting was not enough observed,
which is against allowing such as are not members of
our Society to sit in our meetings for discipline,
unless they are nearly related to the parties concerned,
of which that meeting was modestly reminded.
I was also grieved that matters were introduced too
much at the judgment or pleasure of individuals,
by reason that they are not in the practice of holding preparative meetings,
the service of which, was particularly recommended to their consideration.
I had some reward of peace in having attended this meeting.
We were next at a meeting in Trenton, with a few Friends whom the spirit of the world,
I thought, had much laid waste;
there seemed more openness towards a few of other societies present,
some of whom were tendered by truth's testimony,
which seemed to reach the witness in them.

At Bordentown meeting next day, many were made thankful,
the Divine presence being felt among us; from there John Woolman returned home,
and John Sykes accompanied me to Upper Springfield, where the meeting was large,
and through the Lord's mercy, open and satisfactory;
the testimony of truth flowing in his love towards the youth, many were tendered thereby,
the faithful were encouraged and the negligent warned.
I went to Burlington to attend that monthly meeting;
then to the burial of Margaret Butcher, at Mansfield,
which was a laborious painful meeting, composed of a mixed multitude,
yet something of an evidence attended truth's testimony,
so that the meeting ended with solidity.

From there I went to Peter Harvey's,
and was thankful for the enjoyment of a peaceful quiet mind, though poor;
next day was at Old Springfield meeting, which was slow and late in gathering,
dull and heavy in sitting, as will be the case,
wherever the life and power of religion are lacking,
or not carefully sought after and waited for, by those who profess it,
which was observed to them in the love of truth,
and in the simplicity and plainness thereof.
I left this meeting with a heavy heart,
not from a sense of any omission of duty on my part;
but lest they should too soon forget what manner of
persons they saw themselves to be in the light,
that discovers and answers the witness, as face answers face in a glass.
Taking meetings at Mountholly, Rancocus, and visiting the widow of Peter Andrews,
I was at a large meeting at Evesham on first-day following;
but the expectations of the people being much outward,
occasioned a painful deep waiting a considerable time, or at least I thought so.
At length I felt some pressure on my mind to stand up, which as I followed carefully,
Truth opened the state of the meeting to my admiration,
and I was enabled with an innocent boldness, to attend thereto in speaking,
which yielded me great peace after the meeting, and I was thankful for that opportunity.

Next day I attended Haddonfield monthly meeting,
at which were Samuel Nottingham and William Home,
whose company was comfortable and of advantage to the meeting.
I then visited the meetings at Pilesgrove, Alloway's Creek, Greenwich,
Lower Alloway's Creek, Salem, and one at Raccoon Creek, to which many sober people came,
not professing with us; also a large,
and I believe to some a satisfactory meeting at Woodbury,
the state whereof opened pretty clearly, the humble being instructed;
but I was sensible of an opposition to some part of
what I had to deliver to a self-righteous state,
yet through the mercy of our gracious Lord;
I left this meeting with an evidence of peace,
and an affectionate heart yearning towards them.
Went to Haddonfield to attend the quarterly meeting for Gloucester and Salem counties,
and from there to the general spring meeting at Philadelphia;
after which I returned home, having been out five weeks and three days.
After this journey I did not go much abroad for more than a year,
except to attend our quarterly meeting,
and the yearly and general spring meeting at Philadelphia.

In the year 1759,
I had drawings in my mind to visit a few meetings in Maryland and Virginia,
also the yearly meeting at West River; and having the concurrence of our monthly meeting,
I left home on the 28th of the fifth month, and next day was at Gunpowder meeting;
then at Elkridge, with a few Friends and persons not professing with us,
amongst whom there was an openness to hear the testimony of truth declared;
but for lack of a steady walking in the professors thereof,
it seems in a great measure laid waste.
That night I lodged at the house of a kind man; but natural affability in anyone,
unless it is sweetened by the baptism of the Spirit of Truth, is of little value.
On fifth-day I was at a new meeting house at Indian Spring, with a few Friends,
some of whom I fear, scarcely know what they profess.

Next day had a meeting at Samuel Plummer's, at Patuxent, to satisfaction;
and on seventh-day the yearly meeting at West River began,
which held until fourth-day following,
which was in the main the most open and satisfactory meeting I was ever at in that place.
I thought a disposition prevailed among the younger sort,
to attend to the discipline more closely than in times past.
Taking a meeting at Sandy Spring, I proceeded to Fairfax, about forty miles,
where I had a comfortable meeting on first-day,
for which the hearts of many were made thankful to the Author of all good;
the same day we had also a satisfactory opportunity in Mahlon Janney's family,
and the next day attended Monaquasy meeting in Maryland, where truth is at a low ebb,
through the conduct of some unfaithful professors.

Our next was a precious meeting with a few sincere Friends at Bush Creek;
and I went to a meeting at Pipe Creek next day, which was pretty open and satisfactory;
and to one the day following at Patapsco Forest, amongst a withered people.
Alas! to profess the truth and not possess it in sanctification of spirit,
makes meetings feel desolate.
From there I returned home to our monthly meeting, being absent nineteen days,
and rode near three hundred and fifty miles, Samuel England being my companion.

In this year I was engaged with my friend John Woolman,
in visiting some active members of our Society, who held slaves,
first in the city of Philadelphia, and other places; also in New Jersey;
in which service we were enabled to go through some heavy labours,
and were favoured with peace; Divine love in a tender sympathy prevailing at times,
with a hope that these endeavours would not be in vain.

In the second month, 1760, I informed our monthly meeting,
that in order to proceed in performing the appointment of the yearly meeting,
having also a draft in my own mind,
I had an inclination to visit some meetings up the river Delaware,
particularly the monthly meeting of Kingwood, in New Jersey;
and having the approbation of Friends,
I set out from home on the 26th of the fifth month following,
and reached the Bank meeting in Philadelphia the next day.
From there proceeded to the quarterly meeting for Bucks county, held at Buckingham,
where, though things were low,
the affairs of the church were transacted in a good degree of amity and peace.
It was a large meeting, there being a great appearance of young people,
some very hopeful, who in the love of truth were exhorted to come up in their places,
by learning discipline of the Author thereof, that is, the Spirit of Truth.
They were cautioned against that very unbecoming and hurtful practice,
which is too common, of going out after worship, and standing in companies talking,
when they should keep their places in the meeting,
which should quietly and solidly proceed on the business coming before it.
Heavenly love was felt by the tender in spirit, which I hope will be remembered by many.
The general or youths' meeting was large, open and satisfactory in the main;
for which the name of the Lord was praised.

Next day I spent in visiting a widow, and other aged and infirm Friends;
in the performance of which duty I had some satisfaction,
and on first-day was at Plumstead meeting, which was large and very comfortable;
the Divine presence being felt, the power of truth prevailed to the tendering of many;
but such favour being not of him that wills or runs, but of God that shows mercy;
to him belongs the praise of all, who is worthy forever.
In the evening I attended a meeting at a school house, near Samuel Eastburn's,
in which I had some service;
the states of many present being very clearly
opened before them in the love of the gospel,
which made deep impression on some who were much broken,
and I believe it would be as dew on their hearts,
if they would remain enough in the valley of humility.

I was the next day at Buckingham monthly meeting,
which in the time of business suffered much by
the prevalence of a talkative noisy spirit,
which darkens counsel in those who give way to it,
and leads into doubtful and trifling disputations.
I left that meeting with pain of heart,
in a sense that the time had been so lost that several weighty
matters could not be brought under consideration to advantage,
which were therefore continued until the next month.
Wrightstown monthly meeting on third-day was more satisfactory,
the spirit for discipline rather reviving,
and I hope a desire among the youth at least for an improvement.
It too frequently is the case,
that some of the elderly sort are so bigotted to their old forms and customs,
that they will scarcely trouble themselves to examine whether
these customs are agreeable to the testimony of truth,
or whether through inattention they have not swerved and fallen short
in various matters that now occasion difficulty in the churches,
which difficulty must be laboured under for a season by the baptized members,
who nevertheless, as they keep their places will grow stronger.

Accompanied by my friend Thomas Ross I attended the Falls monthly meeting,
wherein I was comforted from a sense that a tender people were among them,
though they felt a time of dearth,
whom the Lord would in his own time water as his peculiar heritage.
But this comfort was heavily ballasted by a secret fear attending me,
that there were among them some, who like the heath in the desert,
know not when good comes; who were easy in a dead form, and contented with a name,
neglecting to wait for that transforming power,
which would renew into the image and life of the Son of God;
to whom in the love and plainness of the gospel, I was constrained to clear myself.
The meeting for discipline was pretty open, and ended in a good degree of sweetness.
We went home with the wife of Joseph White,
who was then on a religious visit to Friends in Europe,
and had a comfortable season in the family with the children,
she appearing to be resigned in the absence of her husband,
her spirit being sweetened with the truth, in innocent quietude.

At Middletown monthly meeting the next day truth seemed to be low,
but we had some service in the discipline.
I came away with peace,
and the day following in company with Joshua Ely went to Jacob Birdshal's,
in Amwell township, New Jersey, and had a meeting in his barn, which was small;
there are few here who profess with us,
some of whom seem to have nothing more than the name.
Next morning we called at the house of an old professor,
he and his wife were both full of talk; I felt a desire to visit them,
and had a full time to clear myself in a close and plain manner, though in love to them.
After which I attended two meetings at Kingwood on first-day,
when truth favoured in opening the states of the people in mercy to many,
which may be of advantage if rightly remembered; then proceeding to the Drowned-lands,
so called, had a meeting with a few professors who seemed much withered;
then taking another at Paulin's Kiln to pretty good satisfaction,
returned to Kingwood monthly meeting, held at Hardwick.
Several hopeful young people belong thereto; the meeting was comfortable,
Friends rejoicing in the company one of another, and in the Lord for his merciful regard.
Next day I returned to Bethlehem, and from there to Gwynnedd meeting on first-day;
after which I rode to Uwchland, about twenty-eight miles, and from there home,
where I found all well, having been absent three weeks,
and rode about four hundred and sixteen miles in this journey.

Having a draft of love to visit the monthly and
particular meetings within our own quarter,
on the west side of Susquehanna River, with the concurrence of our monthly meeting,
I set out from home on the 17th of the tenth month, in company with my brother-in-law,
James Brown, who likewise had the approbation of Goshen monthly meeting for this purpose.

We visited the meetings at Pipe Creek, Bush Creek and Monaquasy, in Maryland;
in the first of which the Lord was pleased to favour in opening the state of Friends,
and tendering the hearts of many; the other was satisfactory,
and the last seemed to be a renewed visitation to a declining people,
several of whom were tendered through the gracious long-suffering of Infinite Goodness.
We were next at the preparative meeting at Fairfax, in Virginia; then at Goose Creek,
wherein truth owned our service to the comfort of the faithful;
then attended the meeting of ministers and elders, the monthly meeting at Fairfax,
and the first-day meeting there, and one that evening in Francis Hague's house.
Several disorderly walkers being present,
the Lord was pleased to open and give ability to speak to
their states in a measure of his heart tendering love,
reaching the witness in some.
Returning to the widow Janney's, we had a precious opportunity with her and children,
to our mutual satisfaction.

Our next meeting was at Potts', near the South mountain, which was open for doctrine,
several of other religious professions attending, who appeared loving and well satisfied;
then at Crooked-run, near the north branch of Shanandoah River,
in company with several other Friends from Pennsylvania,
some of us being a committee appointed by our quarterly meeting,
in consequence of the Friends living here having
requested that a meeting might be settled among them.
The opportunity was to satisfaction,
there being some young people who I hope will grow in the truth,
though some of those who are elderly appear too superficial.
From there we went to Hopewell preparative meeting,
also to a small meeting over the mountain near Jesse Pugh's;
then attended a select meeting at Hopewell, and one at the same place on first-day,
which was large and solid, many therein being much tendered, to the praise of the Lord,
whose mercy endures forever:
in the evening we had a satisfactory meeting at the widow Lupton's, near Winchester.

Next day we were at Hopewell monthly meeting, where we found considerable weakness,
as to the practice of the discipline,
on which account we had some labour to the comfort of the well-minded.
On our return we had meetings at Monallen, Huntington, Warrington, and Newberry,
in York county, Pennsylvania, and a seasonable opportunity with Friends in Yorktown;
from which I proceeded home with a thankful mind,
having travelled about four hundred miles in this journey.

In the spring of the year 1761,
having an engagement on my mind to visit Barbados and some of the adjacent islands,
I proposed the same to my brethren at home for their weighty consideration,
before I asked for their certificate, who after a time expressed their unity therewith,
and gave me a certificate, to which the quarterly meeting signified their approbation.

At our next yearly meeting I laid my concern before the ministers and elders,
when for anything that appeared, I had their unity and prayers.
I came home intending to proceed before the winter set in,
and attended our general meeting at Nottingham, in the tenth month;
but in a few days after was taken ill with a fever,
which with bodily pain and exercise of mind, reduced me to a very low and weak state.
But the Lord was pleased to give me inward strength,
influencing my mind with love to all men,
and great love to the members of our religious Society,
the state whereof I saw in a clear manner.
I so far recovered as to attend our quarterly meeting at London-grove,
in the eleventh month;
at which I had an opportunity to clear myself to my humble admiration,
and was inwardly comforted.
My concern for going to Barbados continuing,
I went to Philadelphia to inquire for a passage,
when my friends informed me of five vessels, three of which were nearly ready to sail;
but understanding that all of them were prepared with guns for defence,
I felt a secret exercise on my mind, so that I could not go to see any of them.
I kept quiet from sixth-day evening until second-day morning,
when I went to the meeting of ministers and elders,
where I had a freedom to let Friends know,
"`That I came to town in order to take my passage for Barbados,
but found myself not at liberty to go in any of those vessels,
because they carried arms for defence; for as my motive in going,
was to publish '`the glad tidings of the gospel,
which teaches love to all men,`' I could not go
with those who were prepared to destroy men,
whom Christ Jesus, our Lord and Master laid down his life to save,
and to deliver from that spirit in which wars and fightings stand.`"
I further added, "`If I had a concern to visit in gospel love,
those now living at Pittsburgh, or Fort Duquesne,
do you think it would become me to go in company with a band of soldiers,
as if I needed the arm of flesh to guard me;
would it not be more becoming to go with a few simple unarmed men?
I now tenderly desire your sympathy and advice.`"
One honest Friend said, "`Keep to the tender scruple in your own mind,
for it rejoices me to hear it;`" and several said they
believed it would be best for me to mind my own freedom.
I then begged that Friends would consider weightily,
whether it was right for any professing with us, to be owners, or part owners,
charterers, freighters,
or insurers of vessels that a Friend could not
be free to go passenger in on a gospel message.
As I returned to my lodgings, I felt so much peace of mind in thus bearing my testimony,
that I thought if my concern ended therein, it was worth all my trouble,
though at that time I did not think it would,
yet was quite easy to return home and wait until my way appeared more open.
As my concern went off in this manner,
I have been since led to consider that I could not have
borne that testimony so fully and feelingly,
if I had not been thus restrained.
"`The wisdom and judgments of the Lord are unsearchable, and his ways past finding out,
and happy are they who move at his command and stand steadfast in his counsel.`"

Our worthy friends, John Stephenson, Robert Proud, Hannah Harris and Elizabeth Wilkinson,
of Great Britain, being in this country on a religious visit,
attended our yearly meeting in Philadelphia this year,
which was large and favoured with humbling goodness,
and in a sense of the Divine presence, ended very solidly.
The services of these Friends, I think, have been great among us in this land,
both in their public ministry and in the discipline of the church;
and the remembrance thereof is precious I believe to
many whom the Lord is preparing for his work.

After this I spent a considerable time at and near home,
except attending the quarterly and yearly meetings,
and the general spring meetings as they came in course;
in the mean time being careful to frequent the meeting I belonged to.
A new monthly meeting being established at Uwchland, in Chester county,
it arose in my mind to salute Friends there with an epistle,
a copy whereof I sent to their first meeting in the first month, 1763, being as follows:

[.embedded-content-document.epistle]
--

[.salutation]
Dear Friends,

In the gentle springing up of gospel love and fellowship,
I salute you my dear brethren and sisters, and hereby let you know,
that it is my fervent desire and prayer that you may
individually attend to the gift of God in your own hearts,
and therein wait for the arising of his pure life and power,
that therein and thereby only,
the affairs of the church may be transacted to the
honour of Truth and your own peace and safety.
To speak in the church to the business and affairs of truth, by the will,
wisdom and power of man, however knowing he thinks himself,
will lead into its own nature, and in the end minister strife and contention,
and break the unity of the one spirit, wherein the peace of the church stands.

I beseech you to beware thereof,
and as I know there are among you those whom the Lord
by his Spirit and the gentle operation of his power,
is preparing for his own work,
mind your calling in deep humility and holy attention of soul;
for in your obedience only,
will you be elected and chosen to the work whereunto he has called you.
So shall you be made skilful watchmen and watch-women,
placed on the walls of Zion to discover the approach of an enemy,
in whatsoever subtle appearance, and enabled to give warning thereof to others.

May each of you stand upright in your own lots in the regeneration,
waiting for the pouring forth of the anointing of the Holy Spirit;
by the renewing whereof, a true qualification is given in the love of the Father,
rightly to oversee the flock and family of our God,
amongst whom there are some plants with you worthy of your care.

I should have been glad to have sat with you, in your monthly meeting,
from the sense of that love which I now renewedly feel to spring and flow towards you,
but cannot well leave home; I therefore, at this time,
in the pure refreshing stream thereof, again salute you,
and remain your friend and brother,

[.signed-section-signature]
John Churchman.

[.signed-section-context-close]
East Nottingham, First month 4th, 1763.

--

In the time of his illness in the year 1761, as before mentioned,
he uttered many weighty expressions,
some of which were committed to writing by a Friend who was present,
and being worthy to be further preserved, are here inserted:

In this sickness he was reduced very low,
and sometimes said it looked unlikely that he should recover;
in the fore part thereof he often mentioned his being in great poverty of spirit, saying,
that before he was taken ill, he felt such deep distress of mind,
that he thought he was a cumber to the ground,
and scarcely worthy to partake of the meanest necessaries of life,
that even bread and water seemed too good for him.

On the 4th of the eleventh month, four Friends being present,
he spoke in a very awful frame of mind, nearly as follows:

"`Such build on a sandy foundation,
who refuse paying that which is called the provincial, or king's tax,
only because some others scruple paying it, whom they esteem;
yet I have now clearly seen, as well as heretofore, that the testimony of truth,
if deeply attended to, will not be found to unite with warlike measures.
It will in the Lord's time be exalted above all opposition,
and come to possess even the gates of its enemies;
though it may appear mean and contemptible in the eyes of some now-a-days,
as the conduct of our primitive Friends did, in various respects in the world's view.
Whosoever continues to trample upon,
or despise the tender scruples of their brethren
in relation to their clearness concerning war,
will certainly find it a weight too heavy for them to bear.

"`My testimony on this account, so far as I have borne it,
yields me satisfaction at this time; and the painful steps I have taken,
both in public and private, to discharge my conscience in the sight of God,
in giving faithful warnings to my brethren and countrymen,
both in a civil and religious capacity, afford me comfort in this distressing season.
I have clearly seen, and the prospect at this time adds Divine strength to my soul,
that the God of truth is determined in due time to exalt the mountain
of his holiness above all the hills of an empty profession;
and all those who shall be admitted as inhabitants thereon, he wills to be clean handed;
and that they should become subject to the Lamb's nature in every respect,
and not shake hands with that nature which would tear and devour,
nor in any shape contribute to the price of blood.`"

At another time he said:
"`I have been led in the present dispensation to
behold the situation of particular Friends,
to whom I feel ardent affection, who seem to have given away,
or sold for this world's friendship,
the testimony they should have borne for the Prince of peace,
who is the High Priest of our profession; and for fear of breaking an outside unity,
which will surely come to be broken,
that the true unity in the bond of peace may be exalted,
have acted contrary to the former sight they had of their duty,
and are thereby become halt and dim-sighted in several respects.
These, though they still seem to desire it,
cannot attain to the spotless beauty of Truth, nor approach the top of the mountain.
I am afraid that some of them will never recover their former strength,
nor attain to that dignity the Truth would have placed upon them,
if they had been faithful; the situation of whom I have bewailed with anxiety of mind.
I have been from my youth up, accustomed to sorrow, and am a man acquainted with grief,
and now remarkably so; the lives of my brethren and of all men,
appear exceedingly precious in my sight.
It looks doubtful whether I shall ever see my friends in a quarterly meeting again,
yet if it be the will of Divine Providence, I much desire it; having heretofore,
through a timorous disposition, lest I should offend some,
and for fear of the frowns of elder brethren,
concealed some things which I should have declared.
If I should never more have a public opportunity, I speak thus in your hearing,
to let it be known that I am still a well-wisher to all men,
and that my integrity to the testimony of truth,
against all connection with wars and fighting, is now as strong, or stronger than ever.`"

On second-day morning, the 9th of the eleventh month, he said to this effect:
"`I have been led to see the necessity there is for
Friends to beware of the custom of drinking drams,
or strong spirits mixed.
It is my judgment,
that the less any of us accustom ourselves to the use of those spirits,
the better it would be for our constitutions in general.
I believe it is not consistent with the will of Divine Providence,
that the course of nature should be obstructed and changed,
and our animal spirits corrupted through the unnatural warmth of spirituous liquors.

"`From my present sense and feeling of that temperance
which is truly pleasing in the eye of heaven,
I have mourned that the use of strong drink should become so
prevalent amongst us who make so high a profession;
whose bodies should be temples of the Holy Spirit, and should not be defiled,
or tainted with any degree of intemperance.
In harvest there is generally plenty of refreshment,
which would keep the bodies of men strong and capable to perform hard labour.
Witness the health and strength of our forefathers in
the first settlement of this country,
when strong liquors were very little used amongst them.

"`Alas! how dimness has overtaken us, when we compare ourselves and our practices,
with the temperance and moderation of our forefathers
and the early settlers of this province!
How sumptuous now are the tables, how rich and costly the apparel,
the diet and the furniture, of many Friends even in the country;
but more especially in the city!
How is the simplicity and plainness of truth departed from,
and pomp and splendid appearances have taken their place!
And how much cost and time might be spared from needless things,
and applied to bettering our country and helping
to turn away the judgment which hangs over us,
in part occasioned by these things.

"`I desire that my grand-children may be brought up in a plain simple way,
accustomed to industry and some useful business; not aiming at great estates,
nor following others in that way.
Give them useful learning, and rather choose husbandry,
or some plain calling for them in the country,
than endeavour to promote them to ways of merchandise;
for according to my observation from my youth up,
the former is less dangerous and less corrupting.
I observed when I was in England,
that some of the greatest and wisest men in a religious sense,
were brought up at the plough, or in some laborious occupation;
where the mind is less liable to be diverted from an awful sense of the Creator,
than in an easy idle education.
How many great men there are, whose way of living is mean and homely,
in this world's account, so that they have little more than real necessity requires;
and yet they are rich in the best sense.`"

The next day being asked how he was, he said nearly as follows;
"`I have slept sweetly and seem much refreshed,
and though I feel myself very weak in body, I am full of Divine consolation,
having never before had such prospects of heavenly things.
It seems even as though my soul was united in chorus with glorified saints and angels,
both sleeping and waking.
I now believe I shall recover,
and that this sickness did not happen to me altogether on my own account.
My only way to recover is to be industrious and
diligent in what I believe is required of me;
I have many messages to deliver, both in public and privately to Friends,
who I see have missed their way,
and have in a great measure deprived themselves of the beauty with
which a humble abiding in the truth would have dignified them;
and to some of my elder brethren, for whom I feel an uncommon nearness of affection,
their lives never appeared to be more near to me,
and I dare not conceal counsel from them, whether they will hear or forbear.
I thought last night,
I had a clear prospect of the situations of many
within the verge of our quarterly meeting;
it seemed as though the inward states of particulars were opened to me in full view;
the pure life in the brightness of religion, never appeared to be more precious.
An uncommon earnestness attends my mind, for the recovery of the rebellious,
hypocritical, and backsliding professors of all ranks amongst us.
If I get to our quarterly meeting, which I believe I shall,
and can have time allowed me when there, I have tidings, important tidings,
as from a dying man, to many.
I have seen the mystery of the prophet laying three
days and three nights in the belly of the fish.
A wicked and adulterous generation are now, as formerly,
seeking for a sign to things spoken closely, but no sign shall be given them,
save the sign of the prophet Jonah.
Our Saviour's sufferings for mankind,
and afterwards descending into the bowels of the earth,
prefigured that his followers must, after his pattern, descend into spiritual baptism;
that they may rise again,
freed from the dregs of nature and from the corruptions of the creaturely passions,
before they can be qualified to see and suitably to administer to the states of others.
I have likewise seen the mystery of Ezekiel's sufferings,
and bearing the sins of the house of Israel for
the space of three hundred and ninety days,
which being accomplished, he was commanded to turn on the other side,
and to bear the sins of Judah forty days, for the corruptions of that princely tribe,
who should have been as way-marks to others.
My state has been for several years past,
my deep baptisms and painful sitting in our meetings, like bearing the rod of the wicked;
in which dispensation I have been sometimes ready to conclude with Elijah,
that the altars were thrown down and the Lord's prophets slain, and I,
a mean worthless servant, left alone, and that my life was sought also.
I have now seen the use of those dispensations to me, with the use of my late sickness,
whereby I am reduced to great weakness of body;
that I might be as a sign to this generation, and as with the mouth of a dying man,
utter tidings without fear of giving offence; tidings which I have heretofore concealed,
through a timorous disposition.

"`I have seen at this season that the Lord has preserved a living number in Israel,
who have not bowed the knee to Baal, or the god of this world.
I have also seen the condition of many who have worshipped strange gods;
and the corruption even of some who have assumed the station of ministers in our Society,
how they are deceived so far as to believe a lie; have seen lying visions,
and have caused the weak to stumble.
They have been speaking peace to the people in the Lord's name, when it was only a flash,
or divination of their own brain,
which has tended to corruption and putrefaction in the churches.
I have seen that many little ones have laid groaning as
under the burden and oppression of these things,
whose day of redemption draws near, when they shall be made by the Almighty,
as bright stars in the firmament of his power;
and those who are corrupt and settled on their lees, shall be punished.
In this dispensation I have abundantly witnessed the incomes
of that peace and love which pass all understanding;
neither my tongue nor capacity is able to set forth the bowels of compassion
which I livingly feel to flow towards the whole bulk of mankind;
and especially to my brethren in profession.
It seems as though no affliction would be too great to endure for their sakes,
if it might be a means to have some of them,
whose situation I have now been led to behold as particulars,
restored to their former greenness and spiritual health, from which they have fallen,
and dimness has overtaken them.
And though my outward man seems almost wasted, my spirit is strong in the Lord,
and in the inexpressible strength of affection,
I have found my spirit led from place to place over the country,
to visit the souls in prison: Yes, I have beheld the dawning of that precious morning,
wherein corruption shall be swept away from the church,
and righteousness and truth begin to flourish greatly.
The day seems to me to be at hand; and what if I say,
I have a degree of faith that some of the children now born may live to see it.
Through innocent boldness, my face seems to be as brass,
and in the openings of the vision of life, I think I could utter gospel truths,
and discover the mystery of iniquity, which I have seen, without fearing any mortal.
I may be raised to live a while longer, though to die now,
would be a welcome release to me.
Yes, I could not desire to live, but for the longings of soul,
and pantings which I feel towards the precious seed in many,
whom I have now been led in spirit to visit.
I have beheld their situation to be as lumps, taken out from the bowels of their mother,
the earth, though much hidden from the view of mortals;
and are tempering and fashioning by the Divine Potter, in different shapes,
for various uses; and I have seen that the Potter's power is sufficient to pick out,
and take away every little pebble of nature.
Many I have beheld in this situation, set by, as it were, out of sight to dry,
until all the dampness and natural moisture is removed from them,
not being yet fitted to undergo the operation of burning;
but when properly prepared and thoroughly dried, many will be brought to the fire,
burned and glazed, so that they may retain the liquor or wine of the kingdom,
with a sweet taste, without any degree of taint or nauseous smell.`"

On the 12th of the eleventh month, early in the morning, he spoke to this purpose;
"`I believe I must endeavour to go to our quarterly meeting,`" which began on the 14th,
"`although as to bodily strength I am very weak: there my mind is remarkably,
sleeping and waking;
there I hope to be relieved of some things which seem to remain like a fire in my bones.
I dare not forbear, I know it is the way to recover my strength outwardly,
and to be eased of that which is a heavy burden inwardly.
I see I must go, and believe I shall recruit,
and gain strength every day;`" which was the case accordingly.
He further said, "`My mind has for several days been attended with an uncommon sweetness,
the like I never knew for so long together, with a succession of soul-melting prospects.
I have freedom to relate what I had a sight of this morning before day,
as I lay in a sweet slumber;`" which was nearly in these words:
"`I thought I saw Noah's ark floating on the deluge, or flood,
with Noah and his family in it; and looking earnestly at it,
I beheld the window of the ark, and saw Noah put out the dove;
and I beheld her flying to and fro, for some time;
but finding no rest for the sole of her foot; I thought she returned,
and I saw Noah's hand put forth to take her in again.
After some time I thought I beheld her put forth a second time, and a raven with her;
the dove fled as before for some time,
and then I saw her return with a green olive leaf in her mouth,
as a welcome token of the flood's being abated.
I thought I saw also the raven fly to and fro, but he did not return;
and it came into my mind, this is a ravenous bird,
and seeks only for prey to satisfy his own stomach,
otherwise he might have returned to the ark with good tidings, or some pleasant token,
as well as the dove.
After a short space, I thought I beheld the mountain tops, and some of the tree tops,
beginning to appear above the waters, and I could perceive the flood abate very fast.
As the waters fell away,
I saw the trees began to bud and the greenness of new leaves came upon them,
and I heard the voice of the turtle and saw many
symptoms of a pleasant and happy season approaching,
more than I can now relate; and the prospect thereof ravished my soul.
I beheld the trees blossoming, the fragrant valleys adorned with grass,
herbs and pretty flowers, and the pleasant streams gushing down towards the ocean;
indeed, all nature appeared to have a new dress;
the birds were hopping on the boughs of the trees, and chirping; each in their own notes,
warbled forth the praise of their Creator.
And while I beheld these things, a saying of the prophet was brought fresh in my memory,
and applicable as I thought to the view before me:
'`The mountains and the hills shall break forth before you into singing,
and all the trees of the field shall clap their hands; instead of the thorn,
shall come up the fir-tree, and instead of the brier shall come up the myrtle-tree;
and it shall be to the Lord for a name,
for an everlasting sign that shall not be cut off.`"

"`When I awoke, the prospect remained clear in my mind, and had a sweet relish,
which now continues with me;
and the application of the vision seems to me in this manner:
The flood which appeared to cover the face of the earth,
is the corruption and darkness which is so prevalent over the hearts of mankind;
the ark represents a place of safe, though solitary, refuge,
wherein the Almighty preserves his humble attentive people, who, like Noah,
are aiming at perfection in their generation.
The dove sets forth the innocent, harmless, and loving disposition,
which attends the followers of the Lamb who are always willing to bring good tidings,
when such are to be had: the raven represents a contrary disposition,
which reigns in the hearts of the children of disobedience,
who chiefly aim at gratifying their own sensual appetites; the waters gradually abating,
the trees appearing, and afterwards budding, the voice of the turtle,
and the pleasant notes of the birds, all seem clear to me,
to presage the approach of that glorious morning,
wherein corruption and iniquity shall begin to abate, and be swept away;
and then every thing shall appear to have a new dress.
I am fully confirmed in the belief, that that season will approach,
which was foretold by the prophet, wherein the glory of the Lord shall cover the earth,
as the waters cover the sea; and in a sense of these things my soul is overcome.
I feel the loving kindness of the Lord Almighty,
yet waiting for the return of backsliders with unspeakable mercy;
and my soul in a sense of it, seems bound more strongly than ever,
in the bonds of gospel travail;
which travail I hope will increase and spread amongst the faithful,
for the enlargement of the church; that the nations may flock unto Zion;
which shall become an eternal excellency, even the joy of the whole earth.`"

He again expressed his having a prospect of the dawn of this blessed morning; and said,
"`The day-star is risen, which presages the approach of the morning;
I have seen it in its lustre,
and have a lively sense of that saying being again fulfilled in the new creation,
'`The morning stars sang together,
and the sons of God shouted for joy.`' I have heard their sound intelligibly,
and my heart is comforted therein.
The potsherds of the earth may clash together for a season,
but the Lord in due time will bring about the reformation.
The predictions of Archbishop Usher, mentioned in the preface to Sewel's _History,_
have come fresh into my memory, and nearly correspond with the sense I have,
that a sharp and trying dispensation is to come upon the professors of Christianity;
wherein the honest and upright hearted shall be
hid as under the hollow of the Lord's hand;
when rents, divisions and commotions shall increase amongst the earthly-minded,
and one branch of a family be at strife with another,
like the daughter-in-law against the mother-in-law;
and happy will it be for those who endeavour to stand
ready for the approach of such a dispensation.`"
