== Chapter VII.

[.chapter-synopsis]
* His visit to the quarterly meeting at Salem and the general meetings at Uwchland and Goshen, in 1764
* His attendance of the yearly meeting in Philadelphia, 1767, and the general meeting at Cecil in Maryland
* The death of his wife. His visit in Chester and Bucks counties
* To the yearly meeting in Maryland
* Also to several meetings in New Jersey, and some others in York county, Pennsylvania
* Also to Fairfax, etc, in Virginia.

In the spring of the year 1764,
I informed my friends that I had a desire to attend the quarterly meeting at Salem,
in New Jersey, and having their concurrence,
on the 17th of the fifth month I left home and went to Wilmington,
and next day in company with several Friends,
from there by water to our friend Joshua Thompson`'s, at the mouth of Salem Creek.
At the meeting of ministers and elders we were
comforted together through the goodness of the Lord.
On first-day there was a large gathering of a mixed multitude, and quiet,
the Divine power being felt and gospel truths preached, by the influence whereof,
many hearts were tendered;
though I thought the beauty and solemnity of the meeting were
a little marred by one Friend speaking too long;
to begin in the life and conclude in the power and life,
is becoming a minister of the gospel.

On second-day morning the meeting of ministers and elders was again held,
it was a precious instructive season in the love of Christ our holy Head,
by which the humble were united; afterwards we had a large meeting for public worship,
wherein the testimony of truth flowed freely;
the call to the ministry and qualification necessary to
preach the gospel being clearly set forth.
In humble admiration I could renewedly acknowledge, You are Oh Lord,
strength in our weakness, mouth and wisdom,
yes all things to your humble depending servants whose trust is on you,
waiting for your putting forth in the way, and gently going before them;
blessed be your holy name forever.
In transacting the affairs of the discipline, a spirit of brotherly love prevailed.
The youths`' meeting at Pilesgrove was also large and edifying,
the great Shepherd of Israel being pleased to stretch forth the crook of his love,
for gathering the straying youth from pursuing
after lying vanities and worldly pleasures;
ministering reproof to hypocrites and formal professors,
yet comforting his children and humble dependent followers,
to the praise of his own eternal name.
The meeting of ministers and elders sat again by adjournment,
when we had a uniting parting season; I returned to my friend Joshua Thompson`'s,
next day to a meeting at Wilmington, and in the evening home,
being thankful that I had been enabled to perform this small journey.

Having a strong desire to attend the general meetings at Goshen and Uwchland,
on the 8th of the sixth month, my dear wife and I left; home,
though I was very unwell with a cold taken in my return from Salem,
and a fever attending me every day.
We attended Uwchland meeting on first-day,
also one in the evening at the house of our brother Daniel Brown,
which was dull and exercising,
from a sense of the prevalence of a spirit which leads many into forgetfulness of God,
pursuing the vanities and pleasures of this perishing world.
Next day the general meeting at Goshen was very large,
and much disturbed by the going out and coming in of many;
but through Divine goodness it came to a better settlement before it concluded,
when solid Friends in the renewing of the Lord`'s comforting love,
were refreshed in him and one another; a visitation being continued to the youth,
the praise whereof belongs to the great Author of all good!

The general meeting at Uwchland on the day following was large,
and measurably attended with the ownings of truth, under the influence of which,
admonition and counsel flowed freely to the youth,
the Divine witness in several of whom was reached, and the name of the Lord praised,
who is forever worthy!

In these large meetings, as on all other such occasions,
it is necessary in order for a proper qualification to minister to the people,
humbly to wait to know the inward life and baptizing
virtue of the Spirit and power of Jesus Christ,
our all in all, without whose help we can never do his work to his praise,
but instead of gathering the flock,
we shall minister to their scattering from the true place of feeding.
After being at the preparative meeting at East Cain and a meeting at Uwchland,
we returned home thankful to the Lord,
who had mercifully supported us in this small journey;
both of us being weakly and indisposed in health.

In the ninth month, 1767, I attended our yearly meeting in Philadelphia,
which held a week; all the sittings whereof both for worship and discipline,
were through the overshadowing of Divine favour, instructive to the humble waiters;
and the testimony of truth,
particularly against the unjust and unrighteous practice of slave-keeping,
greatly prevailed.
Friends were fully cautioned against bequeathing by will, as slaves to their posterity,
the poor Negroes, their fellow creatures;
it being an unlawful act in the sight of the great and righteous Parent of all mankind.
This meeting concluded with a degree of awe and reverence,
under the sweetening influence of the Father`'s love.
I returned home to our general meeting at Nottingham,
which was held on the 4th and 5th days of the tenth month.

Having a strong desire to attend the general meeting at Cecil, in Maryland,
I sat out in company with several other Friends,
and reached the first sitting of the meeting, which was small and dull;
the public meeting next day was very large and attended with some satisfaction;
those of other societies who were there were mostly pretty quiet.
At the meeting of ministers and elders, the lack of solid elders being evident,
the consideration thereof was proposed to the quarterly meeting,
which was held in the afternoon of the same day,
when it was recommended to the monthly meetings
to observe the directions of the yearly meeting,
to choose well qualified solid Friends, for that weighty station.

The meeting for public worship was again large,
being attended by many of other societies, and my brother, William Brown,
was largely opened in doctrine to the edification of the auditory;
after which I had a short testimony tending to close the foregoing.
In the meeting for discipline I had occasion to lament that there
were too few who feelingly understood the weight of such meetings,
or were clean handed to move therein,
either to their own profit or the help of their brethren;
yet there are a few who seem to be under a preparation for the work,
and I hope will grow in their gifts.
On third-day morning business began again, and ended as well as I expected.
I thought the Lord was mercifully pleased to open
considerable instruction to such among them,
who had ears to hear and hearts disposed to receive it.
The meeting for worship held that afternoon, was not so large as on the other two days;
the service thereof lay weightily on me,
and I had a full opportunity to relieve my mind towards the people,
in opening to them the nature and ground of spiritual worship and true prayer,
also the true call and qualification for gospel ministry,
declaring what it was to live off the gospel, in opposition to a forced maintenance.
Truth favoured and the people were solid, several being much reached;
the meeting ending to satisfaction, with humble thanksgiving in many hearts to the Lord,
whose mercies through Christ Jesus, are to his people yes and amen forever.

[.asterism]
'''

His wife being under many years`' affliction with a cancer on her head,
which was now so greatly increased as to require his daily affectionate attendance,
confined him mostly at home until after her decease, which was in the seventh month,
1770.
She was a steady exemplary Friend; concerning whom the monthly meeting of Nottingham,
gives the following testimony:

[.embedded-content-document.testimony]
--

"`Our friend, Margaret Churchman, was born of believing parents,
William and Esther Brown, who lived at Chichester, in the county of Chester,
in Pennsylvania; on the 13th of the first month, 1706-7,
her father removing with his family into Maryland, near Susquehanna,
died before she was ten years old.
In the twenty-third year of her age,
she entered into the marriage state with John Churchman, of Nottingham,
and being religiously inclined from her childhood,
became a diligent seeker after that bread which nourishes the inward man,
and thereby grew in religion.
About the thirty-fourth year of her age,
it pleased the Lord to put her forth in the ministry,
in which she was frequently exercised to the comfort
and edification of the churches where she visited,
in this and the Southern provinces,
being delivered in a degree of life and gospel sweetness in pertinent expressions.
She was an example in plainness, a diligent attender of meetings,
and a humble waiter therein; serviceable in meetings of business,
having a good sense of discipline,
with a becoming zeal to support the testimony of truth in its various branches,
and useful in the weighty service of visiting families.

"`In the latter part of her life she was for
many years afflicted with a cancer on her head,
which she bore with remarkable patience, resignation and innocent cheerfulness,
attending meetings to the admiration of many who knew her disease.
Notwithstanding various applications,
her malady so increased that she became too weak
to attend meetings sometime before her decease,
yet she retained her love to truth and Friends to the last,
and in the sixty-fourth year of her age, being a minister about thirty years,
departed this life, on the 28th of the seventh month, 1770,
and was buried on the 30th in Friends`' burying ground, at East Nottingham,
attended by many Friends and neighbours,
at which time we had a solid satisfactory meeting.

"`Given forth by our monthly meeting held at East Nottingham,
the 27th of the seventh month, 1771, and signed on behalf thereof, by,

[.signed-section-signature]
"`Samuel England, Rebecca Trimble, Clerks.`"

--

Having an inclination to attend Chester quarterly meeting,
also some meetings within the verge thereof,
with the concurrence of Friends I sat out on the 1st of the second month, 1771.
Attended New Garden monthly meeting next day,
in which the love of our merciful Father was measurably felt,
to the comfort of the humble in heart, and on first-day was at Birmingham;
next day had a meeting in the house of Richard Downing, at Milltown,
with people of various sorts, and the Lord was pleased to assist with wisdom and ability,
in measure, to divide his word in reproof, counsel, admonition and caution,
to the praise of his own name.
On third-day at Pikeland was a pretty full meeting, though a very cold day,
Truth was felt to be near us;
a profitable opportunity was had also in the family of the widow Meredith,
who being weakly, did not get out to their meeting.

Next day had a cold ride to Nantmell, where was a large full meeting,
and I believe beneficial to many present,
by the tendering goodness of the blessed Shepherd of spiritual Israel,
the crook of whose heavenly love is still stretched forth to his sheep,
who are not yet acquainted with the true fold of rest and safe feeding place;
his own works praise him.

Uwchland monthly meeting on the day following was a laborious season,
yet through Divine favour made comfortable to the weary travellers,
who had to rejoice together in a participation of the consolation of Israel,
and therein to worship His name who is worthy forever.
Goshen monthly meeting was also laborious; when former experience is fed upon,
or the love or honour of the world and fleshly ease takes place,
a spirit grows up in the church, which cannot judge for God and his truth;
for the judgment is his, in whose fear his children are made to rejoice,
when his presence is known, and his humbling goodness manifested to his people.
On first-day I was at Middletown meeting,
in which there seemed to be a tender visitation and call to the youth,
to acquaint themselves with the God of their fathers,
his love being measurably witnessed among us.
The quarterly meeting for Chester, held at Concord, was solid and edifying,
through the extending of the heavenly Father`'s love to the children of his family.
From there I went to Wilmington, visited some of my acquaintances,
and had a comfortable sitting in the family of David Ferris,
his son Benjamin being ill in a consumption.
I also attended the monthly meeting, which though a searching time,
was I believe to the comfort and edification of many,
the uniting love of Truth being experienced to
rest on Friends in the time of the business;
after which I went to the monthly meetings at Center and Bradford,
and from there to our quarterly meeting at London-grove.
Then returned home, having great peace in performing this journey,
and in being favoured with ability, felt a degree of reverent thankfulness to the Lord,
who is all things to his servants, who truly abide in nothingness of self;
he is worthy of all obedience and honour forever.

On the 21st of the third month,
I left my habitation in order to attend our general spring meeting at Philadelphia;
in my way called at Wilmington, and was at the burial of Benjamin Ferris,
before mentioned.
Our spring meeting was to me very comfortable in a sense of
the living presence of the holy Head of the church,
in which his true children were edified,
strengthened and mutually comforted one in another; blessed be his name forever!

At this meeting, the brethren, both ministers and elders,
apprehend it their duty in the love of Christ,
to appoint such who are willing to give up their names
to attend the several large or general meetings,
which come in course in the ensuing summer before our yearly meeting,
to which they are expected to give some account of the meetings so attended by them,
and feeling a draft in my mind to be at that at Duck Creek,
I gave in my name to attend it.

On my return from Philadelphia I sat with
Friends at their week-day meeting in Wilmington;
which through the continued goodness of the Lord,
was in some measure a profitable season, I hope to many.
Here I felt a strong desire to see the Friends together,
who are owners of the grist-mills lately built at and near Brandywine;
and upon notice thereof, they met the same afternoon at the house of Daniel Byrnes,
when I had an opportunity to discharge my mind in an affectionate manner,
of what had impressed it towards them,
which they appeared to receive in a degree of the same love;
and as I believe it came from the Author of all good, who is alone worthy of praise,
a blessing may attend that opportunity if rightly remembered.

On the 26th of the fourth month, being accompanied by a Friend and neighbour,
I went to Duck Creek, and was at the monthly meeting there the next day, which was heavy,
occasioned by the prevalence of a formal, lukewarm, worldly spirit,
over many of the professors belonging thereto,
but through the long-suffering and continued mercy of God,
there seemed to be a renewed awakening visitation to some.
The meeting on first-day was very large,
the Lord being mercifully pleased to open the states of many in a particular manner;
and in a measure of his holy heart tendering power, which reached the witness,
several were humbled, and the meeting ended with thanksgiving,
prayer and praises to the Lord who is worthy forever.

On second-day the meeting was not so large, occasioned by a fair being near;
nevertheless it was a season in which the doctrine and mysteries of
the kingdom of Christ were largely set forth to the people,
by the influence of the spirit, and in the love and wisdom of the holy High Priest,
who is all in all to his people.

We had also three select opportunities with the ministers and elders,
among whom there was great apparent weakness;
the reasons whereof were plainly made known to them,
from the sense given in the love and fear of Him,
who will not own and unite with such as are defiled;
which plainness we had a hope would be profitable.

Next day several of us were at George`'s Creek, which meeting is much declined.
Where the love of the world and its alluring vanities prevail on the professors of truth,
their affections are drawn from God, they grow slack in attending meetings,
and are a bad example one to another.
It was a hard meeting, but through the love of Christ,
a measure of gospel anointing enabled to open to
them their states in great love and plainness,
which seemed to affect some;
may it be remembered with reverence before Him who is the Author of all good,
and worthy of all praise forever!

Soon after my return home,
feeling my mind engaged to attend the quarterly meeting in Bucks county,
with a few meetings in Philadelphia quarter, I set out on the 26th of the fifth month,
accompanied by Samuel England, and on the third-day of the week following,
was at the Bank meeting in Philadelphia, which was comfortable.
On fifth-day at the quarterly meeting at Buckingham,
and next day the general youths`' meeting, which was large and divinely favoured.
Then visiting several indisposed Friends, on first-day I attended Plumstead meeting;
and in that week the several monthly meetings of Buckingham, Wrightstown,
the Falls and Middletown, also a public meeting at Makefield;
was on first-day at Bristol, from which I went with my friend James Thornton,
to their afternoon meeting at Byberry, had an appointed one at the same place next day;
and in that week visited the several neighbouring meetings,
one of which was a general youths`' meeting at Horsham, large and instructive,
wherein the love of our heavenly Father was felt by his truly depending children.
Then taking meetings at Gwynedd, Providence, Richland, Oley, Exeter, Maiden Creek,
Reading, and on first-day at the Forest; I rode from there to Uwchland,
and on second-day had a meeting at Milltown, in the house of Robert Valentine.
Then proceeded home, having rode about three hundred and seventy miles in this journey,
in which I was favoured with health, and held travelling beyond my expectation.
At the gentle drawings of Truth I left my habitation,
having little prospect of much before me,
but was preserved in a quiet resignation to the Divine
will to do whatsoever should appear my duty,
beseeching the Lord to enable me to watch against every appearance of
self in the great and pure work of declaring the gospel to the people,
and have great cause to be humbly thankful,
that the Lord was pleased to own my service beyond expectation,
to the exaltation of his own truth; blessed be his name forever!

In the tenth month following, I went to the yearly meeting at Third-haven, in Maryland;
the meetings for worship held three days, and each of them were very large,
and many gospel truths were delivered in the love and power thereof,
by which the witness of God was reached in the hearts of many of the people,
and Friends comforted and made thankful to the Lord,
that he was pleased to own us with the overshadowing of his heavenly love.
On fourth-day morning the affairs of the discipline were finished,
when we had a parting meeting, which through Divine favour was a precious time to many.
I had never been at the yearly meeting when held at this place before,
and now witnessed my heart enlarged in the love of the gospel,
to declare the truth among the multitude of people who professed the Christian name,
and to remind them of their conduct and dress,
how different it was from that of those who
formerly suffered martyrdom for their religion,
as professed by the members of the church of England, so called,
who own the reformers as their predecessors.

Feeling a draft of love in my mind towards some meetings in New Jersey,
particularly at Egg Harbour, and having the concurrence of my friends at home,
I set out on second-day the 1st of the sixth month, 1772,
and taking in my way a meeting at Haddonfield, and another at the house of my friend,
Thomas Evans, which through the presence and power of the Searcher of hearts,
was made profitable to some present; reached Little Egg Harbour on seventh-day.
Next day attended the yearly meeting,
in which the love of the gospel was felt to flow towards a loose, raw,
uncivilized people, who appeared to attend there more out of curiosity,
than from a reverent thoughtfulness of worshipping Almighty God.
In the afternoon of the same day the continuance of Divine
favour was remarkably evident towards the inhabitants,
for which the Lord made the hearts of his sensible children thankful to himself,
who is the Author of all good.
The meeting on second-day was also very large,
in which the true children of the family were comforted
in Christ Jesus the Lord and holy Head of the church,
by the anointing virtue of whose precious name and power,
they were made to rejoice in the company one of another.
Parting with many valuable beloved Friends, I went over the bay,
to the upper meeting on Great Egg Harbour shore, which was large, considering the notice.
I was comforted in knowing for whose name sake I was made willing to leave my company,
and turn that way,
the Lord being pleased to own my service by the
inspiration of a degree of his heavenly wisdom and love,
to speak to the states of those present; blessed be His name who is worthy forever.

I went home with my friend Joseph Mapes; next day attended the lower meeting,
which through Divine favour was a precious season; then passed over to the cape,
and next morning was at a meeting at the upper house,
where many not of our Society attended, to whom the doctrine of the gospel flowed,
in describing the nature of pure and undefiled religion, and wherein it consisted;
the people were still and quiet.
In the afternoon of the same day I had a meeting at the lower house,
which is eight miles down the cape; this was a heart tendering time,
for which Friends were made truly thankful;
I thought it seemed like to be my last visit to these parts.
From there I went to Cohansey, forty-five miles, to Mark Reeve`'s,
where I rested the next day, being very weary and almost overcome with hard travelling.
On first-day I was at Greenwich meeting, and in the afternoon at Alloway`'s Creek,
which was very large, many of other societies attending;
the doctrine of truth flowed to them in a measure of the love thereof.
Next day the meeting at Salem was held in the court house,
the meeting house being taken down, and a new one being built.
On third-day I was at the upper meeting near Alloway`'s Creek;
which through Divine Goodness was an instructive time to some seekers.
The passage treated upon was our Lord`'s description of the pharisee and publican,
who went up to the temple to pray;
the great difference in the form of their addresses was opened in a clear manner,
by the spirit of Him who gave forth that parable, to my humble admiration,
which was cause of reverent thankfulness; they who were sensible being encouraged,
and the conceited formalists rebuked.

From there I went to John Davis`',
had a comfortable opportunity with some indisposed Friends in his family;
then taking meetings at Pilesgrove, Upper Greenwich and Woodbury,
was on first-day morning at Haddonfield, and in the afternoon at Newtown,
which last was laborious, though I believe being blessed to several present,
was thereby made profitable.
That evening I went over to Philadelphia weary in body, but cheerful in mind,
being sensible of a degree of thankfulness for
the continued favour of my Lord and Master,
who had been to me a quiet habitation and secret support in this journey.
After staying two days, and on each attending meetings in the city,
I took Wilmington meeting in my way home,
having travelled about three hundred and fifty miles, attended about twenty meetings,
besides having several comfortable opportunities in families.

Being under an appointment with other Friends of our quarterly meeting,
to visit Friends of the monthly meetings of Warrington and Fairfax,
I set out on the 7th of the tenth month, and taking a meeting with Friends in Yorktown,
we were at Warrington on first-day; then visited the several meetings of Newberry,
Huntington and Monallen, in which Truth owned our service in a good degree;
our labour of love appearing to be kindly received, I hope may be useful.

On first-day following five of us were at Pipe Creek meeting; then at Bush Creek,
Monaquesy, Fairfax, Goose Creek and Southfork, wherein the Lord was pleased,
in his customary goodness and mercy, to magnify his own name,
who is worthy of all praise forever.
After a seasonable opportunity with Friends held
in the house of Abel Janny at parting with them,
we returned to Fairfax meeting on first-day,
where under the influence of the Divine presence,
the testimony and doctrine of truth flowed freely to the people;
in a humble sense whereof,
praises ascended to His holy name who is over all worthy forever.

Several of our company now returning homewards, three of us not being easy yet to return,
two of us went to visit a Friend who lay in a languishing condition,
which I believe was serviceable,
the love of our heavenly Father being in some degree felt among us.

On third-day we had a meeting at the Gap, so called, among a raw people,
where Divine Goodness measurably favoured the opportunity;
on the day following we attended Fairfax preparative meeting;
the two next days we visited some sick Friends,
and on seventh-day were at the monthly meeting, which was in the main satisfactory.
On first-day the meeting was thought to be the largest ever held at this place,
and the gospel being preached in the love of it, tendering the hearts of many,
the meeting ended in humble thanksgiving to the holy Author of all good.

Next day in company with several Friends of Fairfax, I attended a meeting at Monaquesy,
where some came who did not make religious profession with us,
which was an instructive tendering season, through the Lord`'s goodness.

After a meeting at Bush Creek, and another at Pipe Creek, I travelled to Gunpowder,
and attended the quarterly meeting for the Western shore of Maryland,
likewise the general meeting for worship on first-day,
at which were several not of our Society, whose hearts were reached by the love of Truth.
Next day I had a meeting at the Little Falls, and from there returned home,
and after staying three days, I went to our quarterly meeting at London-grove,
the two last days of which afforded some comfort and satisfaction.
On the 14th of the twelfth month I went to Wilmington, on which day Margaret,
the wife of John Perry, was buried, after a short illness.
I spent part of the evening in his afflicted family to satisfaction;
staying in the town two days, I attended their monthly meeting,
and thought there was a lack of more members deeply baptized for the work,
which appears necessary in the church at that place.
Deborah, the daughter of David Ferris, being in a declining consumptive state,
and wasting fast, I visited her to my satisfaction,
she appearing to be in a resigned humble frame of spirit,
was an exemplary young woman whom I esteemed.
Then going to Center and Hockesson meetings, I was at New Garden on first-day,
which I thought through Divine favour, an instructive profitable meeting to myself,
and perhaps to some others; the subject which opened was the necessity of not leaning to,
nor following, any man,
but of attending to the pure motion and secret influence of
the Spirit of Truth manifested in the heart,
in the meekness and purity of the wisdom from above.
It was by this the churches were gathered,
and the members preserved in the unity of the one blessed Spirit,
and perfect bond of peace and good order.

I next attended our preparative and monthly meetings,
after which was confined mostly at home for about a month by a fever,
during which time my mind was often much humbled
under a sense of the prevalence of a dull,
lukewarm spirit, as to the life and power of truth;
earthly mindedness and the cares and cumbers concerning the things of
this present life having drawn the minds of many into death.
I never more clearly saw the necessity there was for us who profess the truth,
singly to attend to the gentle instructions of the holy Spirit, who only does,
and ever will, lead and guide into all truth,
and preserves from those errors and failings which are so abundantly evident among us,
whereby our hands are weakened in respect to a
careful exercise of the discipline of the church.
