== Appendix: Peter Gardiner In Scotland

[.offset]
+++[+++This further account of Peter Gardiner`'s journey is taken
from John Barclay`'s _History of Friends in Scotland:_]

In the year 1694-5,
the Friends in Scotland were visited in the love of the gospel by Peter Gardiner.
Some few and extraordinary passages, relative to his journey so far north as Yorkshire,
have already appeared in print in the pages of John Churchman`'s valuable Journal.
After some search, the author of the present volume^
footnote:[that is, John Barclay]
has ascertained, that Peter Gardiner,
or Gardner, for his name is spelled both ways in the original documents,
lived not far from Castle Hedingham, in Essex, perhaps within the borders of Suffolk;
which may explain the substitution of one county for the other,
in some of the records about to be referred to.

With regard to his movements among Friends in Scotland,
we have but a few scattered particulars.
The first to be adduced, relates to his visit at Aberdeen,
and is mentioned by the Friends there,
in the following terms:

"`We had at this monthly meeting,
3rd of eleventh month, 1694-5,
the acceptable and comfortable visit of two English Friends, Peter Gardiner, in Suffolk,
and James Leech, in Berwick.`"
At the next monthly meeting there is a more extended notice of the former of these,
by way of testimony to the goodness of the Lord, in thus favouring his poor instrument,
and the congregation at large.--
"`Our dear Friend, Peter Gardiner,
mentioned to have been at the last monthly meeting,
was eminently attended with a singular gift from God,
in travailing for and bringing forth several young plants among Friends`' children,
into a public ministry, about the middle of last month: particularly Robert Barclay,
Robert Gerard and Margaret Jaffray, whose mouth was first opened:
as well as he was the instrument of awakening several
other young ones by a very tender visitation,
which yet continues among them: And, O that it may continue, and _they_ in the sense of it,
to the end of their days!
As also, about this time,
the blessed God of our life was graciously pleased to give us a new,
fresh and large visitation,
in abundantly pouring out his Spirit and life among us in our gatherings;
and some more mouths were opened among elders,
particularly dear John Forbes of Aquorthies,
as also Jane Molleson.`"

A confirmation of the above,
may be seen in the language of the Friends of Ury meeting, on the like occasion.
They speak of Peter Gardiner as being
"`an honest and faithful man, of a weighty and discerning spirit.`"
"`He had great service for truth hereaway with good success, in several places,
particularly at Aberdeen and Ury, and Montrose;
where many were wonderfully tendered and broken before the Lord,
and several mouths were opened in testimony and prayer; particularly at Aberdeen,
Robert Gerard, James and Timothy Forbes and Margaret Jaffray; at Ury,
Robert and David Barclay, and their sisters Christian and Catharine,
their aunt Jane Molleson and Joseph White; at Montrose, Jane Bettie,
wife of Robert Bettie.`"

In further illustration
of the truth and import of the last mentioned circumstances,
it is pleasing to be able to produce an interesting,
though rough draft of this devoted labourer`'s services in the neighbourhood of Ury;
but especially in the family of "`the Apologist,"` whose widow then resided on that estate,
with her seven children, the eldest of whom, Robert, has been already spoken of.
It will not have escaped the recollection of the reader, how beautifully George Fox,
in his sympathetic address to this bereaved widow,--after setting
forth the consolations which flow from a union with the Lord,
as the Husband and Father of his people,
endeavours to stimulate her _to do the day`'s work,_ to put on his strength,
and to hope for his blessing on a faithful discharge of her duty,
as _a spiritual nursing-mother_ over her household.

Indeed,
he goes further; and subjoins his fervent prayer,
that her children may be established upon the Rock, Christ Jesus,
and thus be favoured of the Most High,
through the fervent exercise of their surviving parent.
But in proceeding to describe the successful issue of such labour,
it may be well to pause--and hold up to view _one means,_ among others, which she used,
by way of laying open the ground of the hearts of her
tender offspring to the genial rays of Divine Light.
We are informed by a Friend, who, about this time, passed several days under her roof,
that "`when her children were up in the morning, and dressed,
she sat down with them before breakfast,
and in a religious manner _waited upon the Lord;_`"
"`which pious care,`" he adds,
"`and motherly instruction of her children when young,
doubtless had its desired effect upon them; for, as they grew in years,
they also grew in the knowledge of the blessed truth; and since that time,
some of them are become public preachers thereof`"--John Gratton`'s _Life._
Thus cherished and watered,
did Peter Gardiner find this group of young '`olive plants,`' when he entered
their abode.

"`Upon the 16th of the eleventh month,
1694, it pleased the Lord to send him to Ury; having come by Aberdeen, Kinmuck,
and also Kingswells; in which last place he was made instrumental in the Lord`'s hand,
in bringing forth Andrew Jaffray`'s eldest daughter in a public testimony.
Afterward, in a meeting at Jane Somervill`'s, at Aberdeen, he was under a great exercise,
and said, he felt _the Life stopped_ in some there, and could not get forward,
until the _Seed was at liberty;_ after which,
he was again brought forth in a living testimony,
to the refreshment of all the meeting.

"`When he came to Ury,
which was on the third-day of the week,
(Andrew Jaffray, David Wallace and Robert Gerard accompanying him from Aberdeen,)
he had a meeting there on fourth-day.
From there he went to Stonehaven on fifth-day, being accompanied by most of them of Ury;
and there he and Andrew Jaffray had, each of them,
a good opportunity among the people that came into the meeting.
From there we came that night to Springhall, +++[+++a house on the estate of Ury;]
and had there a good meeting; only he said he felt _the Life stopped_ in some there,
who would not give up to the Lord`'s requirings.
The same night, after supper, he had a blessed opportunity with Robert Barclay,
David and Patience Barclay, John Gellie, David Wallace and Robert Gerard;
where we were all so mightily overcome, that we were made to cry out; and Robert Barclay,
+++[+++aged twenty-two years,]
was opened in a few living words of exhortation to the young generation there present,
which reached and melted our hearts in a wonderful manner.
He said,
it was himself who had occasioned the life to be stopped in the foregoing meeting,
by not giving up to the Lord`'s requirings; and so,
he concluded in a few living words of prayer.
After this they retired to rest.
Robert Barclay and Robert Gerard had a remarkably comfortable night,
neither of them minding sleep much.

"`Next day,
which was sixth-day, we had a blessed meeting among the children;
where Christian Barclay, the younger, +++[+++aged fourteen years,]
had her mouth opened in prayer, to the refreshment of us all.
That same day we had a more general meeting at Ury; where Friends at Stonehaven,
and those also about Ury attended.

"`On the
seventh-day we had another blessed morning meeting among the children;
and the first-day of the week following,
we had a good meeting about the middle of the day,
where there was more people than usual;
and Robert Barclay bore a living testimony among them.
Life so went along with him in it, that it reached the hearts of many of them,
and astonished others;
his testimony being much to this purpose:--That the Lord had given them line upon line,
and precept upon precept, one visitation after another, to the reaching of many of them;
exhorting them to take up the cross and despise the shame,
and so become fools for Christ`'s sake; that thus,
they might think nothing too dear or near to them, in comparison with Him.
And further he told them,
he believed it would be the last visitation of the Lord to some of them;
and advised them to turn in time, before it was over:
for the Lord had now raised up _the third generation_ to
bear a testimony for his truth among them in that place.
In that meeting was also his aunt Jane Molleson`'s
mouth opened in a few words of testimony.
That same night we had a blessed meeting at Springhall; where David, aged twelve years,
Catharine, aged sixteen years, and Christian Barclay, the younger, bore, each of them,
a testimony to the truth: yet, notwithstanding all this, our friend, Peter Gardiner,
could not obtain ease, but felt _the Life stopped_ in one there,
and at last named the person and desired him to _clear himself;_ and so John Chalmers,
their schoolmaster, aged about nineteen years,
afterward an acceptable minister in Dublin, stood up,
and said a few words by way of testimony.
Then Peter ended the meeting in prayer,
and came away easy.
That same night we had a good little meeting together in the school room.

"`Next morning he had his farewell meeting at Ury;
and so he, together with Robert and David Barclay, took his journey.
But as we were parting at the end of the garden,
Robert Barclay had some living words by way of testimony,
to those who had accompanied us there.

"`We came to Montrose that night;
where, after we had rested awhile, we had a little meeting.
Next morning we had a meeting among ourselves.
About the middle of the day, we had a meeting of all the Friends of the town;
and some other people came in: both Peter and Robert Barclay preached on that occasion.
We had also another meeting that night, where Peter fully relieved his mind.
Robert and David Barclay both declared the truth among them,
also John Gellie had some words of prayer.
The substance of the testimonies borne in that meeting,
were much to this purpose:--That none should sit down in Zion at their ease,
but that they should travail for the prosperity of the truth _in themselves and others;_
and that none should love the world or the things of it too much,
nor be covered with any other covering than the Spirit of Truth;
and that a profession of the truth would not do,
__till persons came to the life and possession of it.__
Next morning we had a blessed farewell meeting;
and so parted from each other in much tenderness of heart.
Peter Gardiner, David Wallace and their companion,
went towards Edinburgh.

"`After they were gone,
Robert and David Barclay, John Gellie and Robert Gerard, had a precious meeting together,
where Robert Bettie and his wife were present.
They returned to Ury that night, a little after nine o`'clock.
Next day we had a blessed meeting among the children.

"`The day following,
being the 25th of the same month, we had a glorious meeting, where Patience Barclay,
aged nineteen years, was opened, both in testimony and in prayer,
to the refreshing of all our hearts.
We held another good meeting among the children the day after; where James Forbes,
being then at Ury, had some words of testimony.

"`And so,
the Lord God, as he has begun a good work, will carry it on,
_if we be but faithful to him,_
over all that the enemy or his instruments can do to hinder it.
Oh! that we may think nothing too dear to part with, for Him;
but that we may give up all freely for Him,
if he please to make use of any of us as instruments in his hand;
and that our eye may be unto Him, and so abide faithful unto the end:
which will be of more value than all the perishing pleasures and
transitory enjoyments of this world.

[.small-break]
'''

With
regard to the application of these facts to our own day,
and to individual experience, it may truly be said,
"`This is the Lord`'s doing, and it is marvellous in our eyes.`"
Do we not see, in them,
the accomplishment of one of the most prominent among the standing miracles foreordained,
respecting these gospel times?--"`And it shall come to pass in the last days, says God,
I will pour out my Spirit upon all flesh;
and your sons and your daughters shall prophesy:--and
on my servants and on my handmaidens,
I will pour out in those days of my Spirit; and they shall prophesy.`"
And again, another ancient language,
which has equal reference to more modern periods:--
"`Out of the mouths of babes and sucklings you have perfected praise.`"
It is hoped, however, that none will be inclined, in perusing the above statements,
to cast these things from them; taking up the conclusion,
that these __"`marvellous things`"__ do not concern them.
For assuredly,
__"`Those things which are revealed, belong unto us and unto our children.`"__
The example of such as have listened and heard, and answered the call of the Lord,
to give up their hearts to his disposal and direction, that he may work in or by them,
altogether according to his own good pleasure,--most certainly,
these examples speak forth the inviting language,
__Follow us, as we have followed Christ:__
they form one link in that chain of evidence,
in mercy continued down, even to us of the present age,
through the long line of patriarchs,
prophets and believers of every degree--that God is most favourably inclined,
to draw near and to dwell with all who diligently seek
him,--that he will richly reward them,
even in this life,
with the lifting up of the light of his countenance,--
that he will dignify all who trust in and obey him,
with the manifestations of his love and power, and even make them, in one way or another,
instruments of his glory for the good of souls.

[.small-break]
'''

Peter Gardiner,
proceeding on his journey through the other meetings of Friends in Scotland,
on his way homeward, arrived at Carlisle: from this place, as it is supposed,
he wrote the ensuing epistle,
but a very short time before he was taken with his last illness.
It affords some clear indications of a sound and living faith, simplicity of love,
a heavenly meekness and gratitude,
which were now fast ripening for a better state.

"`It is thought fit,`" observe the Friends of Aberdeen,
"`here to insert our dear friend and brother Peter
Gardiner`'s last salutation of love to this meeting,
by way of epistle, a little before he laid down the body;
it having pleased the Lord to remove him a little after, by the small pox, at Carlisle,
as he was returning homeward,
which paper follows--he having been so notable an instrument hereaway:`"

[.embedded-content-document.epistle]
--

This is the tender salutation of my love to Friends in general,
belonging to Aberdeen.

My dear and loving Friends,
which are near and dear to me in the everlasting truth of my
God!

In the love of God,
with which our souls have been refreshed together--in this love,
does my soul dearly salute you all;
hoping these few lines may find you all in good health, as, glory to my God!
I am at this time;--and I have had a prosperous journey--glory be to the eternal God!
Though my inward exercises have been _very great,_ yet, this is matter of great joy,
that the work of my God is going on.
For the Lord is pouring out of his Spirit in a glorious manner,
__in the west of Scotland:__--there are three come forth in a +++[+++public] testimony,
to the great refreshment of the souls of many.
Therefore, dear Friends,
let us labour together in the work of our God.

And I beseech you all,
in the love of God,--which I do at this time feel to spring towards you,
do not _despise the day of small things;_
for whosoever despises the day of small things _in themselves or others,_
a withering day will _certainly_ come upon them.
Therefore, dear Friends, cry mightily unto the Lord on behalf of your children;
for I do believe, that the Lord will pour out his Spirit upon them,
and make them very glorious,
as they give up in obedience unto him:--for I feel the love of God very large,
towards you and your children.
And I was glad to hear of the sweet stream of life,
which I heard ran among you since I came away.

So, dear Friends, in a fresh stream of life, does my soul dearly salute you all,
desiring the continuance of your prayers for me:
so I remain your friend and brother in the Lord,`"

[.signed-section-signature]
Peter Gardiner.

--

[.offset]
The only remaining memorial which has come to
hand respecting this faithful follower of a self-denying and crucified Redeemer,
is that conveyed in a letter from John Bowstead, a Friend of Carlisle,
to Francis Stamper of London.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Aglionby, 12th of Third month, 1695.

[.salutation]
Dear friend, Francis Stamper,

By these you may understand,
that I received yours from London, the 30th of first month, and it is now before me;
and your request therein I hereby answer in the following
lines.

Our dear friend,
Peter Gardiner, made a very sweet and heavenly end,
to the general satisfaction of all present; for the Spirit and power of God was with him:
and at several times in his sickness, he spoke many seasonable and weighty words;
of which I take some, as follows:--On the fifth day before he departed this life,
I was sent for by some Friends of the city of Carlisle;
and when I came into the room where he lay sick, I asked him how it was with him?
He said, Ah, John!
I am sick in body, but the Lord reigns gloriously in Zion:
his power is over all his enemies.
And, often using the word John, as I sat by him, he said, Ah,
John! there is a terrible day approaching this nation,
the weight of which bowed my spirit as I came along--I saw it
before I left the kingdom of Scotland--Oh! it bowed me,
it was even like death unto me.
So he lay still a little time, and I asked,
how it was with him?--for I felt him under an exercise of spirit;--and I asked him,
if he would have me write his will?
Yes, said he, and what you do, do quickly.
So I wrote it, and read it to him,
and it satisfied him much.

Then sitting in silence a little while,
I was moved of the Lord to prayer:
after me Peter Gardiner prayed very powerfully,--That
the Lord would preserve his people together in unity,
and would spare and overshadow them with the wing of his power,
until the storm be passed over;--or words to that purpose.
And the power of the Lord being over all, I think all that were in the room,
were melted and broken into tenderness; and some that were fallen back from the truth,
being present, were also tendered,
and made to confess that the Lord was with him,--and so he was.
So lying quietly for a little while, there came into the room one that was not a Friend,
but under convictions in his heart.
Peter Gardiner asked me, as I sat upon the bedside by him,
Who that was that came into the room?
There being many, and most of them Friends, I said, This is a Friend.
Ah! said he, it is no Friend; is it not such a one?
so called him near,--and it was so.
Peter Gardiner was so full of the small-pox, that he could not see at that time.
He then spoke to the young man, and said, '`You have no peace in your lying down,
nor in your uprising; therefore, I charge and warn you in the name of the Lord my God,
that you speedily return, and draw near unto the Lord, while you have a day afforded you.
For now is the day of your visitation, and the Lord is still striving with you;
and if you do not return, you will repent, when time will be too late with you.
I tell you, you would be heir of two kingdoms,
but will never obtain them both;`'--with many other weighty words to particular Friends,
which would be too tedious here to mention.

[.offset]
A copy of his last words to Friends in his own country and elsewhere,
I here send you, as follows:

[.salutation]
"`Dear Friends,

"`Inasmuch as it has been
my lot to be concerned in the service of truth,
and to have a portion among the people of God, I can bless his name,
that he has thought me worthy to have a name among them that are living;
for I have sweet peace with Him, that is, the Redeemer of Israel,
and am now waiting for my Pilot to conduct me to my long home.`'

[.offset]
To his wife thus:

[.salutation]
"`My dear wife,

"`In the fresh springs of
life that flow forth from my Father`'s presence,
do I dearly salute you, and our dear children and Friends, with desires in my heart,
that grace, mercy and peace, may dwell plentifully in and among you,
unto your lives`' end!
Farewell!

[.signed-section-signature]
"`Peter Gardiner.`"

[.offset]
This, at present, with my love to yourself and Friends; I rest your friend,

[.signed-section-signature]
John Bowstead.

--
