[quote.epigraph, , Daniel 11:33]
____
And they that understand among the people, shall instruct many.
____

[quote.epigraph, , Daniel 12:4]
____
"`Many shall run to and fro, and knowledge shall be increased.
____

== To the Reader.

In the perusal of the following pages thou wilt receive a pious man`'s plain
account of his beginning and progress in the weighty work of religion,
and in a life devoted to promote the cause of
righteousness and the real happiness of mankind.

Having experienced the spiritual baptism which is essential to salvation,
and abiding in a state of watchfulness and humility, he became,
under the Lord`'s anointing,
a well qualified instrument for the instruction and
edification of others in the way of godliness.
By attending to the gift of gospel ministry committed to his trust,
and performing the duties required of him, he witnessed a growth from stature to stature,
and became an upright elder and father in the church,
being an example to the believers in word, in conversation, in spirit,
in faith and charity.

As the ensuing narrative will be likely to come under the
observation of many to whom he was either little known,
or wholly a stranger,
it seems proper to make known the estimation in which
he was held by his brethren in religious society,
who have given a full testimony of their Christian unity and fellowship with him,
and that his life and conduct adorned the doctrine of the gospel.

The monthly and quarterly meetings who were for many
years partakers of his pious example and labours,
testify, that:

[quote]
____
"`Although he was of a weakly constitution, and often infirm,
especially in the latter part of his life,
yet he appeared to be much devoted to the service of truth and the good of mankind,
and gave up his time for that purpose, when he apprehended it was required of him,
being favoured with a sufficiency of outward things.
We believe he stood loose from the world and its connections, not seeking,
but refraining from opportunities which he might have had to get outward riches.
He visited neighbouring yearly, quarterly, and other meetings of Friends at times,
to his last year, and was truly useful in the discipline of the church,
having a valuable gift in that respect,
and was a good example in a diligent care to attend all
the meetings both for worship and discipline,
to which he belonged.
He was cautious of being forward in his public appearances,
and for the most part exampled us to silence in our meetings at home,
especially in the latter part of his time; yet when he did appear in testimony,
we think it may be truly said his doctrine dropped as the dew,
being lively and edifying to the honest hearted,
though close and searching to the careless professors,
as well as to the profane and hypocritical.

"`The elders who have ruled well are to be accounted honourable,
and the remembrance of the fatherly, diligent, humble, upright, honest,
and self-denying example of this our deceased friend,
as also his various services in our meetings and neighbourhood, remain fresh,
and are of a pleasant savour to many minds.`"
____

In confirmation of the truth of which memorial concerning him,
many others of his brethren in various places, can freely subscribe.

His deportment was grave and reverent, and his judgment sound and clear,
in matters of a spiritual or temporal nature.
His disposition being cheerful,
he sometimes discovered a turn of pleasantry in conversation,
which being circumscribed within due limitations,
rendered his company innocently agreeable and instructive.

Being deeply sensible of the weight and solemnity of the gospel ministry,
he manifested great circumspection and care,
that it might be preserved pure and unblemished from mistaken,
or false appearances in himself or others.
In the exercise of his gift, his declarations were plain, familiar, and concise,
accompanied with a fervent concern that his fellow believers and all others
might be brought to the sure knowledge of the teachings of the Holy Spirit,
given to direct and lead into true devotion of heart, and the practice of self-denial,
consistent with the doctrine and precepts of Christ Jesus our Lord,
for the prevalence and enlargement of whose peaceable kingdom, he was earnestly engaged.
With a degree of propriety he might have adopted the language of an
eminent minister in the early age of the Christian church,
"`Knowing that shortly I must put off this my tabernacle,
even as our Lord Jesus Christ hath shown me;
moreover I will endeavour that you may be able after my decease,
to have these things in remembrance; for we have not followed cunningly devised fables,
when we made known unto you the power and coming of our Lord Jesus Christ.`"

What he has written is recommended to thy perusal and consideration,
in which if thou art seriously attentive, and not superficial,
thou mayest under the divine blessing, receive profitable instruction in righteousness,
which is the intent of the publication.

[.signed-section-context-close]
Philadelphia, Ninth month, 1779.
