== Chapter IV.

[.chapter-synopsis]
* His visit to Great Britain, Ireland and Holland, from the year 1750 to 1754, with observations on the state of our religious Society in the course of his travels.

On the 4th day of the fourth month, 1750, being the second of the week,
we left Philadelphia, accompanied by several of our relations and friends to Chester,
and went on board the ship Carolina, Stephen Mesnard, commander, bound for London,
where my brother, William Brown, and myself, took leave of them.
We went out to sea in the afternoon of the 6th of the same month, and had a good passage,
in which I was not seasick, though my brother was most of the time.

We landed at Dover on the 6th of the fifth month,
being just five weeks from the time I left my own house,
and we had to rejoice with humble thankfulness, that during the passage,
we were careful to keep our meetings in the great cabin twice a week,
in which we felt the presence of our great Lord and Master, and therein were comforted.
On the day we landed we had a meeting at Dover to good satisfaction,
then took passage in a stage coach to Canterbury the same evening,
rested there on seventh-day,
and on first-day sat with Friends in their morning and
afternoon meetings to some satisfaction;
though I had little to say to them, I thought there was a tender people in that city,
and William Brown had an open time.

Next morning taking our passage in a stage coach, we reached London the same evening,
and continued in and about the city until the 21st of the sixth month,
in which time I wrote letters to my wife and particular friends in Pennsylvania,
and was several times at each of the meetings in the city.
I sat mostly silent, under a great exercise of mind,
from a sense of a too forward ministry,
which rather disturbed the solemn quiet thereof than
ministered instruction to the humble waiting children,
of which number I thought there were many in that city;
though it seemed delightful to those who loved to hear words eloquently delivered,
and to have the itching ear pleased, yet in heart were libertines, and in practice,
disorderly walkers.
I sometimes thought,
that my silent sitting was so ordered for an example to
others for a more steady waiting in their own gifts,
to know life to arise into dominion in meetings.
My exercise increased so, that my sleep seemed to depart from me,
and I remained as one sealed up as to ministry,
nor had I freedom to go from house to house to dine, or to make many acquaintance,
and I was therefore censured by some as singular and narrow.
At length I felt great enlargement of heart towards other societies,
though my mouth was shut towards our own, and for a time,
it seemed as if I must go and have meetings among those who did not profess with us.

One day, as I was walking towards Ratcliff fields for the air,
the draught of affection flowed so strong towards some in high stations in government,
that I concluded,
I must declare the way of life and salvation through Christ Jesus our Lord among them,
feeling a greater openness toward them than to Friends; but making a stand,
I secretly cried,
ah Lord! what then will become of the family whom thou drewest me hither to visit.
After a little while, that charge came into my mind very fresh,
"`Go not into the way of the Gentiles, and into any city of the Samaritans enter ye not;
but go rather to the lost sheep of the house of Israel,`" which brought great sweetness,
and an increasing heart-yearning for and love to the household, and made me acknowledge,
good art thou oh!
Lord God, for thy mercies endure forever and ever.
I remembered that Nehemiah quietly viewed the state of Jerusalem by night;
and I saw that if I had any service to do in London, the time for it was not yet come.
I also remembered what came into my mind at the second meeting I was in after my landing,
in which I had but a few sentences to speak, and the motion of life ceased,
and I sat down, as I have always found it safe to do,
and felt inward poverty and weakness, yet a quiet and attentive mind.
My brother, William Brown, had good service and an open time among the people,
at which I admired, and said in my heart, he is fit to be sent abroad; but alas!
I am one of the meanest servants that was ever sent over the sea to preach the gospel;
when this gentle caution came before me, "`Mind thy own business,
and be faithful in thy gift,
thou hast a great journey before thee and thy store is small;
live therefore frugally and spend carefully, and covet not another`'s,
and thou shalt not want what is convenient for thyself,
and something to spare to the needy,`" I desired with an humble heart,
to be preserved in patience and meekness,
becoming a disciple of my great Lord and Master,
and therein to wait for renewed instruction and ability
to labour without repining in mine own gift,
however small.

In a few days I felt some openness towards the west of England, and informed my brother,
William Brown, thereof, who, after a little pause, told me that his way opened eastward.
On consideration of the matter,
we concluded it was best for each of us to mind the pointings of truth,
though in some cross to our own wills; for this prospect seemed to part us;
and if we should endeavour to go together for a time, and then part,
some might judge there was a dislike, or want of unity between us,
and on communing with some of our friends, they were of the same mind;
so in much love and affection we took leave of each other.

Understanding there was a yearly meeting to be held in
Somersetshire for several of the western counties,
and having drawings to attend it, I left London on the 21st of the sixth month,
in company with my friend John Hunt, at whose house I lodged, and John Pemberton,
who came over sea with us on account of his health,
and had a meeting that day at Staines, which was pretty good and open,
next at Basingstoke, and so on to Salisbury and Shaftsbury.
The last two were dull meetings,
which is often the case where Friends are not careful to live near to truth.
We reached Ivelchester, the place where the yearly meeting began,
on seventh-day in the evening, the 25th of the month;
on first-day we had two meetings in the town-hall, and many people being there,
meetings were held at the market cross in the street, at the same time.
I sat silent that day;
on the next there was a meeting of ministers and elders in the morning,
in which I had some remarks to make respecting ministry;
there were also two public meetings, one of which was dull, the other more open,
and on third-day two meetings rather better, when the yearly meeting ended.
Some meetings being laid out for me, John Hunt returned to London,
but John Pemberton concluded to go with me a few days,
and his company was kindly accepted of by me, he being a sober, well inclined young man.

We went to Ilminster, in which the good presence was witnessed much to my comfort,
for I saw that the Lord was near,
and helped me in my gift by opening the state of the meeting;
blessed be his name for ever.
I also had an evening meeting at Chard, and next day at Yeovil,
which was large and open for doctrine; then at Sherborne, on the edge of Dorsetshire;
from thence we went to visit the wife and children of Jonah Thompson, at Compton,
he being in Pennsylvania on a religious visit; I had good satisfaction in the family,
and tarried there a day.
Then went to the meetings at Long Sutton, Puddimore, Grinton, Glastonbury,
Shipton-mallet, and Frome, in which I had mostly close and plain service;
yet not without a degree of the sweetness and power of truth,
in a sense whereof I was often made humbly thankful to the Lord.
Proceeding to Bath, was at the forenoon and afternoon meetings there,
and had an evening meeting at Caleb Tyley`'s, which were owned by truth;
but there is a want of weighty solid Friends in this place,
which is much frequented on account of the waters.

From thence we went to Bradford and Pickwick meetings; but not being clear at the first,
I returned, and had an evening meeting there, to which many came,
and it ended to satisfaction.
Having a desire to see Friends by themselves,
and something on my mind in a close manner to the Society;
when I stood up and began to speak, the house was soon almost filled by others,
who would wait without, setting some one to watch when there was any thing spoken.
Upon their coming in, the subject in my view closed,
and an opening in a doctrinal way presented, and my mind turned to it,
and I believe it was to the satisfaction of some seeking people present.

After I sat down, finding no ease respecting my concern towards Friends,
I informed the people that the public service of that meeting was now over,
but I had a desire that the members of the meeting would stay a little while;
on which a Friend went to the door, and when the others had gone out, shut it,
and the Friends mostly kept their seats.
In a little time, the state of the meeting came freshly before me again,
and I had an opportunity to clear myself in a very plain manner,
showing that the greatest enemies to the truth were the professors of it,
who did not observe the instructions of the grace of God in their own hearts.
For although the doctrine thereof when declared by qualified instruments,
was clear and powerfully convincing,
having the love and sweetening evidence of truth with it,
reaching the witness in their hearts;
yet when the eyes of such were turned to behold the
steps and conduct of the libertine professors among us,
they were stumbled by their example, and such were an offence to the little ones,
and their portion is hinted at by our Lord, when he says,
"`But whoso shall offend one of these little ones who believe in me,
it were better for him that a millstone were hanged about his neck,
and that he were drowned in the depth of the sea.`"

From thence we went to Westbury and Lavington meetings,
and to the quarterly meeting for Wiltshire, held at Devizes,
which began on the first-day of the week, by two meetings for public worship,
and one in the evening for ministers and elders, and next day for worship and business.
I could see no time or room to clear myself to advantage for want of more stillness;
the service of meetings may be hurt for want of silence,
and the minds of people become too unsettled to understand and hear to profit;
in a sense whereof, I left this place with a heavy heart, and went to Chippenham,
Corsham, Charlcot and Melksham meetings.
Besides these I had three evening meetings, one at Pickwick,
in a school house belonging to Thomas Bennet, with his scholars and others;
one at John Fry`'s, of Sutton Benjar, and the other at Samuel Rutty`'s;
some of which were good meetings.

Leaving Wiltshire, we passed through Bradford and Bath,
and came to Bristol on the 22nd of the month, where I tarried until first-day,
the 7th of the eighth month, constantly attending their meetings as they came in course,
and visiting several families as truth opened my way.
My spirit was bowed very low in this city,
under a sense of a declension and falling away from truth, into pride, high mindedness,
and the spirit of the world, and a conformity to the vain customs and fashions thereof,
of which I frequently made mention amongst them.
I was at their two weeks`' meeting for business,
and the quarterly meeting for inspecting the affairs of truth,
and laboured much to encourage them to hold weekly meetings for ministers and elders,
in order to inquire how meetings for worship were attended by public Friends,
and whether their ministry was acceptable,
and the lives and conversations of ministers and elders
correspondent with their doctrine and profession,
which care they had dropped for sometime.
I was at sixteen meetings in this city, and one at Frenchay,
and visited Anthony Purver`'s boarding school at that place,
and being easy to leave Bristol for the present, we went to Chewmagna, in Somersetshire,
and had a religious opportunity in John Hipsley`'s family,
and the next day a meeting at Portishead, an evening meeting at James Players`',
then to Claverham, Sidcot and Mark, some of which were good meetings.
A few elderly Friends here live near truth, and there was a visitation to the youth,
several of whom appeared tender and growing in religion;
though many professors are seeking after the gain, love and friendship of the world,
not enough considering that godliness with contentment, is the best gain.

Our next meeting was at Bridgewater, then at Taunton,
and we were comforted together with Friends in their morning and afternoon meetings;
in the divine presence there is life, and the living are made able to praise the Lord,
who is worthy.
From thence passing to Minehead, Milverton, Wellington, Spiceland, Columpton,
having a meeting at each place, we came to Exeter, in Devonshire,
and attended three meetings there on first-day,
in each of which I had something to offer;
but was much depressed under an apprehension of
the prevalence of a deistical spirit over some,
which, with the indifference of others about religion,
and a light forward zeal in some others, without the deep, inward,
baptizing knowledge of truth,
occasioned the pure and ever blessed power thereof to be at a low ebb in that city.
When the children of the Lord know him, their Redeemer,
to live in them by his heavenly power, they also live thereby,
and feelingly know his truth and precious testimony,
and by this knowledge are influenced with a holy, humble zeal,
in love and meekness to work in his vineyard, the church,
to the honour of God and the edification and restoration one of another.

Leaving Exeter, we went to Topsham and had a dark dull meeting, and at a Friend`'s house,
one who, as I understood, could not spare time to attend the meeting,
asked me if I was ever in New-England,
and whether I could inform him what sort of a country it was, adding,
I have heard people say that the corn, that is wheat, will not ripen there,
but is smitten with a rotting mildew, which blasts the wheat in the ear.
I suddenly felt that I had need of being careful in answering, but knew not why.
I answered with caution,
that I had seen wheat in that country which looked to be well grown,
but in the ear where grain should be,
there was little else but a black smut in form of a grain.
I have heard, said he, that it would bear full, good wheat formerly,
and what can now be the cause why it is blasted, didst thou ever hear?
I related to him a passage I had heard, viz:
Two persons had a curiosity to see the old prison,
from whence those Friends who were hanged at Boston for
their religious testimony and principles,
were led to execution, and an inhabitant of the town, going with them,
brought them to the prison.
One of the men said to their guide,
'`Is this the old jail where the Friends lay who were hanged?`'
An old woman who sat knitting at the door,
though not spoken to, answered, yes it is, and we feelingly know it,
for a curse has been on the land ever since,
so that it will not bear wheat without a blasting,
and we are beholden to other colonies for bread.
He replied with an air of jesting, "`I have heard so, but I believe nothing of it.`"
I told him we might observe,
that the Almighty sometimes manifested his displeasure on a people or nation, by famine,
the sword, or pestilence, for their transgressions,
if we had a belief in the Sacred Writings of the Old Testament.
He said it could not be, that the Almighty who is love in perfection,
and in himself infinitely happy for ever, should delight in severity,
and take vengeance on man the workmanship of his hand;
some who are narrow in their way of thinking might believe such things, but for his part,
he had ideas more noble of the Deity, than to believe such notions.
I perceived he was a Deist, and did not regard the Scriptures,
and that it would be vain to say much to him;
having often thought it was very difficult to
say any thing to reach those low free-thinkers,
who exercise themselves in the wisdom which is from beneath,
and dwell safely in their own imaginations and conceits,
whose communication is often infectious to others,
and to be perceived in the meetings and neighbourhoods where they reside.

From thence we went to Bovy, Newtonbushel, Totness and Kingsbridge.
At the last, after the morning and afternoon meetings,
we had one in the evening with Friends selected, which was to satisfaction.
Hearing of one family that lived many miles from any meeting, I had a desire to see them,
and went thither.
I let the Friend know, that I came there on purpose to see him and his family,
and should be glad to have them come together and be still a little while,
desiring it might be soon, for we intended to go that night to Plymouth.
He said it would not answer them at that time,
his children being employed in pressing out cider.
I let him know, that I hoped I should not detain them long,
and if they lightened the press, the cider would not run over;
but could not prevail with him, though I informed him, that I had left all my business,
and had come some thousand miles to see my friends in this nation,
and hearing how remote he lived from meeting, had a particular mind to see him.
He replied that he should be glad it had suited them,
but could not put his business by at that time.
With a heavy heart I left his house and went to Plymouth,
where we had a meeting next day; then to Germains, Liscard, Loe, Austil and Denny`'s,
in Cornwall, at which last place the people are mostly employed in the tin mines,
and we had a pretty good meeting, a visit from a Friend being acceptable to them,
and they willing to leave their business, though poor people.
From thence we proceeded to the Land`'s-end, intending to take the meetings on our return,
and were at Penzance meeting on sixth-day.
At this meeting my companion, John Pemberton, spoke a few words in way of testimony,
tender and broken, being the first time,
and I thought had a good degree of the savour of truth attending.

On seventh-day we went to visit an ancient Friend, sick and bed ridden,
near the Land`'s-end, where formerly there had been a meeting;
returned in the evening to Penzance;
on first-day had a meeting at Marazion in the morning, and at Penzance in the evening.

We then turned eastward, and attended a meeting at Falmouth,
and five others in this county of Cornwall; then passed through Devonshire,
taking a meeting at Oakhampton, and twelve others in Somersetshire,
some of which were large and open.
Many seeking people came to the meetings at Bridgewater,
and I hope some of those opportunities were
through divine favour profitable to some of them;
and not being easy in my mind to leave this county without being at
the quarterly meeting for business to be held at Glastonbury,
I returned thither,
and was concerned to lay before Friends the
declining state of the Society in that county,
and to exhort them to put the discipline in practice,
that the church might be cleared from disorders which caused reproach.
It was thought by Friends to be the most solid quarterly
meeting which had been held in that county for many years.

From thence we went to Cain, in Wiltshire,
and were at their meeting on first-day the 16th of the tenth month,
where we met our friend and countryman, Daniel Stanton, from Philadelphia,
in the course of his religious visit, and were glad in each other`'s company,
though the meetings both forenoon and afternoon were but dull;
the people looking for words, were disappointed.

The next day we went together to a monthly meeting at Chippenham;
the meeting for worship was held in the meeting house;
at the conclusion of which Friends rose and went out.
I asked them where they were going, for I felt very uneasy,
they said to do the business of the meeting,
and feeling a strong engagement to be with them
while they transacted the affairs of the church,
I followed them, though it rained very fast.
They went into a spacious house where a room was prepared for the purpose,
and a good fire.
I sat down with them, though sorely distressed;
they seemed to do the business in a formal ready way;
I endeavoured to press them to weightiness of spirit,
that they might feel the state of the Society,
and the need there was to put the discipline in practice,
for religion was at a low ebb in that county.
They seemed not to understand me,
and indeed I found but little room or openness to say much to them;
they soon finished their business.
When I rose up and moved for going away,
they informed me that Friends staid to dine where the business was transacted,
and that the Friends of the house would think it very strange if I went away.
They told the woman that the Friend was going away; she met me in the hall,
and said I must not go before I took dinner; I told her I should,
for that I had not freedom to stay to eat or drink in the house; she asked me why?
I pressingly desired her to inquire of the truth in her own heart,
and she might find the cause, so I went away, and a Friend followed me out,
and showed me the way to his house where I left my horse,
and there I found Daniel Stanton and my companion,
who went not to the meeting for business.
Daniel informed me, that he followed us to the door, but could not go in,
for he thought he felt the life of truth struck at, or trampled upon in that house,
and therefore returned to the other where we had left our horses,
and John Pemberton with him.
I was glad that he had such a sense,
and he expressed satisfaction that I did not stay to dine, so we dined together,
after which Daniel went westward, and we towards London,
taking several meetings in our way, and arrived there the 31st of the tenth month,
and staid in the city until the 25th of the eleventh month.

I carefully visited all the meetings, in great awfulness,
being bowed in spirit under a sense of a forward ministry,
and sat chiefly in silence among them.
I also attended their meetings for discipline; namely, one quarterly meeting,
the monthly, two-weeks, second-day morning meetings, and meeting for sufferings,
and was in much heaviness of mind,
having a sense of a great neglect in some who were active members,
in not waiting for a true qualification to act for the
honour of God and edification of the church;
nevertheless there is a remnant who are concerned to seek his honour,
and to wait for the influence of his divine spirit and power, to whom I was, at times,
concerned to speak by way of encouragement.
To transact the weighty affairs of the church in as light and
easy a manner as men commonly buy and sell in a market,
will always rather bring death over a meeting than life.

We left London on the 26th of the eleventh month, and went to Chelmsford, in Essex,
and the next day sat with Friends in their forenoon and afternoon meetings,
to pretty good satisfaction, through the goodness and power of the Lord,
whose presence was measurably felt among us to the praise of his ever worthy name.
Taking meetings as regularly as we could, we visited that county in twenty-four days,
and had twenty-three public meetings and some family sittings.
My service for truth in this county was in a close plain way, mostly with but few words;
for it often appeared to me, that there was a greater desire to hear,
than to put in practice those things they were exhorted to, for which I often mourned,
and had a strong sympathy with the few sensible, baptized Friends amongst them.

We then passed to Ipswich, in Suffolk,
and had a meeting with Friends there to some satisfaction,
there being a tender sincere remnant among them; and taking the east part of the county,
we had ten meetings, and visited several indisposed Friends to good satisfaction.

Then went to Yarmouth, in Norfolk,
and after attending their meetings in the morning and afternoon on first-day,
had a large satisfactory one the same evening,
many of the people of the town coming to it; then going to Norwich,
we tarried with Friends there about a week,
in which time I had four meetings in that city, and one at Lammas, near it;
and also visited divers indisposed Friends, and had satisfaction therein.
Intending to visit all the meetings in Norfolk county,
a Friend undertook to lay them out for me, and made a list of them,
of which he gave me a copy,
and told me it was the way to take the meetings with the least travelling.
I felt a strait in my mind,
which I had always found safe for me to attend to until I saw a way open,
and being thoughtful about it, I desired him to inform me,
what meeting bore most to the north-east from that place;
he told me it was North Walsham.
I desired him to begin there, and name the meetings most regular afterwards,
and I would tell him if the list felt pleasant as he went on; he then proceeded,
and we readily finished one which was easy to me.
I desired him to set down the distances as he had done in the other,
and on comparing them, we found the last to be at least three miles less riding;
he seemed to be pleased, and said it was not the usual way of taking those meetings.
I was willing to lay out nine, but told him,
I was not easy to venture the giving public notice further,
that perhaps the weather might be difficult.
He said there would be a general meeting in a few days,
when Friends from many meetings would be together,
and likely to have full notice very easily given for a few meetings further,
which he thought I had best leave to him;
so we went forward to North Walsham and had a satisfactory meeting,
and taking the meetings in course,
came to the quarterly meeting of ministers and elders at Norwich.

The Friend who laid out the meetings informed me,
that if I had taken them according to his first list,
I should have interfered with a public Friend at several, who was then on a visit,
and he thought there was a hand of Providence in turning me;
for as we were both strangers,
we should have been straitened through a tender regard to each other`'s service;
he likewise let me know,
that he did not remember that their quarterly meeting began the next day
after the meeting beyond which I told him I was not free to appoint any,
and that having sent the list to a Friend to
publish at the general meeting before mentioned,
he had been obliged to attend that meeting to stop the
notice respecting the few meetings he talked of,
otherwise I should have missed the quarterly meeting,
and he thought it would teach him to be more cautious in future.
I mention this occurrence with a degree of reverent thankfulness and humility,
with no other view than to encourage those ministers
who are called forth to visit the churches,
diligently and innocently to attend to the motion of truth,
which the more we are humbled and inwardly quiet, the clearer it is understood and felt;
but as this is instruction for ourselves,
it is safer for us to treasure it up in our own hearts,
than to make it too cheap by talking thereof to others.
This quarterly meeting,
both in respect to public worship and transacting the affairs of truth,
was held to satisfaction, through the Lord`'s favour,
who will be near to them that diligently seek him, blessed be his name for ever!

Then taking Elkingham meeting, we went to Thetford, and had a meeting with Friends there,
both which were distressing, from a sense of the prevalence of a ranting spirit.
Here it appeared expedient to lay out meetings for the ensuing week,
in order that suitable notice might be given;
and as they were named to me in course by Friends,
I felt a remarkable desire to see the Friends of one certain meeting by themselves,
at or near the eleventh hour of the day, although quite a stranger to their situation,
numbers, or state; and a Friend being present belonging to that meeting,
I requested her care about it, and then went to Edmondsbury,
and attended the meetings there on the first-day morning and afternoon,
which were in the main satisfactory; and in the evening had a meeting with a sick Friend.
In this town there is a considerable number of hopeful Friends.

We then went to Ratlesden, Bardwell, and through Livermore to Brand,
the place where I had the desire to see Friends by themselves, as before mentioned,
and coming to the Friend`'s house whose wife had been entrusted with the notice,
I asked her if it was not time to go to the meeting, she said, thou must ask my husband,
appearing to be distressed.
I asked where he was, she replied in his warehouse, and sent for him;
he coming after a while, I suppose about twelve o`'clock,
I asked him the time of the meeting, he answered at six in the evening, to be sure.
I told him that I had informed his wife of my desire that it should be at eleven;
he replied, she said so, but I thought it would be dishonourable,
for few only would attend it at that time,
for the people of that town were chiefly such as were obliged to do their day`'s work,
which would be finished at six o`'clock in the evening,
when the house would be nearly full.
I told him, I did desire to see Friends by themselves,
and supposed they could meet at any hour;
he granted that they could have met at the time proposed;
but said he was a man of a more liberal spirit than to want to eat his morsel alone,
but was desirous his neighbours should partake with him,
and thought it his duty to endeavour to inform and help those whom he
apprehended were backward or ignorant in the performance of their duty;
and he said that the end and intent of ministers going forth was to publish the gospel,
and he thought, to the more the better.
I let him know that it was necessary for those
who were called to the work of the ministry,
to know also to whom they were called, or otherwise they might be mistaken,
and go north instead of south, or to a different nation or country; he answered,
that he believed if they were rightly called,
the spirit would inform them where they were to go.
I replied very well, and when they are come to the right place,
the spirit would let them know what they have to do; he said, I believe so too.
Whereupon I told him,
if I knew the language of that spirit that called me from my native land to Old England,
it was the same that inclined me to see the Friends of that town by themselves,
and afterwards if I felt an enlargement of mind,
could have proposed a public meeting with the town`'s people in the evening.
And why not one opportunity for both?
he queried, adding,
"`for I should be willing that all the town
might hear what thou canst have to say to us.`"
I then said to him,
"`if a certain great person on whom thy prosperity in
all things temporal did absolutely depend,
should in singular kindness to thee,
send a messenger to acquaint or advise thee of some matter
relating to thyself in thy own particular conduct,
in which thy prosperity, peace and interest would, without thy immediate care,
be nearly affected,
wouldst thou judge it prudent to say to the ambassador of such a friend,
deliver not thy message to me,
until I call my neighbours and the people of the town to hear it,
and so expose thy own weakness to thy disadvantage, without benefit to thy neighbours?
Consider it carefully, my heart yearns to the professors of truth in this town,
and it seems to me that my business at present was only with them,
and as I can not have an opportunity according to my freedom and desire,
I shall hold myself excused.`"
He answered, if nothing but a meeting with Friends will do,
we must send them word to come together as soon as they can;
I told him that would now by no means do; for he was at present so chafed in his mind,
that he could not hear to much advantage.
He then asked me what end would be answered by my coming there?
I told him to detect such heady unsound members as he was,
that thought it dishonourable for a few Friends to meet together to worship God,
though their number was more than two or three, to whom the promise was.
He said, then what will become of the meeting?
I let him know he must look to that, who had without orders appointed it,
and so left him and went to Mildenhall,
where a Friend told me he was at the meeting aforesaid, when public notice was given,
and it was on this wise; "`Friends and neighbours! please to take notice,
that a Friend from America desires a public meeting here on Wednesday next,
at six o`'clock in the evening;`" which circumstance I
did not know when I was at his house.
On the whole I had inward peace in my observations and conduct to this man,
and many Friends rejoiced; for several had been overborne by him to their grief;
and I was since informed, that he laid the matter to heart, and was often heard to say,
that he would not serve any Friend so again.

We had many meetings in this county, and passing into Cambridgeshire,
had eight meetings therein, and I thought the life of religion was low in general,
though there are a few tender Friends in several places;
we then went to meetings in Huntingdonshire, Northamptonshire,
Bedfordshire and Hertfordshire,
in which it was mostly my lot to point out to Friends the
danger they were in of losing the pure savour of truth,
for want of humbly attending to the dictates thereof in their own hearts,
which had already occasioned a dwarfishness among the professors in those parts.

Several Friends met us at Waltham Abbey, from London, with whom we went to that city,
in order to attend the yearly meeting, which began on the 26th,
and ended on the sixth-day of the week, the 31st of the third month, 1751,
and in the several sittings thereof,
both for public worship and the transaction of the affairs of truth, was thought,
by many, to be the most weighty and solid meeting that had been known for many years;
which was cause of humble rejoicing and deep thankfulness to many Friends,
in that the Lord had vouchsafed his heavenly presence in wisdom and power,
to the praise of his sacred name.

Several Friends staying in the city after the meeting was over,
we had a large and satisfactory one on the seventh-day of the week, and I tarried,
attending divers meetings until the 6th of the fourth month; then went to Chelmsford,
and sat with Friends in their morning and afternoon meetings on first-day;
and from thence to the yearly meeting at Colchester; but being taken ill of a fever,
was prevented attending more than one sitting of that meeting;
yet through mercy was resigned, and had peace.
Staid their meeting in that town on the fifth-day of the week,
and the next day set forward with my brother, William Brown,
John Griffith and my companion, in order to attend Woodbridge yearly meeting,
which began on the 17th of the month, and although the fever had not left me,
I was enabled to attend every sitting of it,
which was a large and solid meeting throughout, and friends were refreshed together;
praised be the Lord! whose mercy is great to his people.
My companion, John Pemberton, went with my brother to some adjacent meetings,
but I staid the week-day meeting in this town,
which was through divine favour satisfactory.
We met again at the yearly meeting at Norwich, in a few days,
which concluded to satisfaction,
and Friends were made truly thankful to the Lord for this additional favour;
we spent a few days longer at this city, and attended their monthly meeting; after which,
having a desire to visit a few meetings in company with my brother, William Brown,
where ranterism seemed to prevail, he having the like concern,
we took a monthly meeting at Wimondham, also the meetings at Matssil and Ellnigham,
in which we were concerned to use great plainness to
clear ourselves on account of that ranting spirit.

Then went to Wareham, and had a precious meeting with the few Friends of that place,
and to a very large general meeting at Downham, many of other societies being there;
and it became my concern to recite the words of our blessed Lord,
"`Search the Scriptures, for in them ye think ye have eternal life,
and they are they which testify of me,
and ye will not come to me that ye might have life;`" from whence I
had to show them the danger of trusting to information and knowledge,
whether by reading the Scriptures, or hearing them preached,
and neglecting to attend to the in-speaking voice of Christ immediately in the heart,
which is the only sure interpreter of the Scriptures,
leading those who attend to his instruction, in the sure way to life eternal.

Then parting with William Brown, we went to Wisbich and Thornyfenn, in Cambridgeshire,
and taking meetings in Lincolnshire, we passed into the East-riding of Yorkshire,
in which we had twenty-four meetings, and taking eight in the county of Durham,
we came to Shields, in Northumberland, New Castle and Alnwick Abbey, and reached Kelso,
in Scotland, on the 1st of the seventh month, where we met Susanna Fothergill,
on her return home.
We attended the morning and afternoon meetings at Kelso, on first-day.

Alas! truth is here at a low ebb,
and feeling my mind not to be clear of Friends in this place,
I desired to have a select meeting with them, which Susanna and her companion attended,
and we had an opportunity of clearing ourselves of Friends there,
who had much fallen from the simplicity of the pure truth, into the modes,
fashions and customs of the world, in their dress, language and manners;
and truth owned our service with a degree of its divine authority; blessed be the Lord,
the God of truth!
We then went to a meeting at the house of John Cristy, at Ormston,
to which many people came and behaved quietly,
and the doctrine of truth opened pretty freely to them.
From thence to a meeting at Edinburgh, in which I had a sense that silence was best,
apprehending the people had been too much fed with words.
After sometime one stood up,
and spoke of the excellence of resignation in ministers to speak,
or contentedly to be silent; to be anything, or nothing,
as the Lord was pleased to order.
A secret distressing fear attended my mind,
that he was not enough inwardly engaged to distinguish
the order and motion of the Spirit of Truth,
from the busy imagination and will of the creature, unsubjected to the Divine Spirit.
I found a concern to show the nature of true resignation,
and the low humble quiet that attended the minds of ministers, or hearers,
who had come to the real knowledge of it;
the desire of such was turned unto the Lord only for heavenly
instruction and an inward evidence of the life and motion of truth;
for want of which, true gospel ministry was sometimes obstructed,
and the reason of silence not fully understood.
After I sat down, the same person again stood up,
and in a flow of words and a zealous tone, said that weakness, or the want of experience,
led people to mistake both their own and the condition of others;
as he appeared to me to be actuated by a confident, ranting spirit,
my mind was greatly exercised after the meeting.

I remained at this place the two following days, being detained by rainy weather,
and attended the meeting in the morning of first-day, at which I sat silent;
but the same person spoke some time in words very encouraging to the auditory,
as if all was well with them, which tended to increase the exercise of my mind,
having a very different sense of the state of the meeting.
I again attended their meeting in the afternoon,
when the same person seemed as if he intended soon to stand up;
but feeling the testimony of truth strong against that forward ranting spirit,
and the sense thereof being weighty upon me, I endeavoured to keep under it in patience,
and soon the concern of that person began to diminish, and he to be drowsy,
after which I had a favourable open time to clear my
mind of the exercise that had been upon me.

Next day we passed over the Frith about seven miles broad, landed at Kinghorn,
and rode to a town called Cowper,
and the day following reached the house of one who esteemed himself a Friend,
near Montross, where we endeavoured to have a meeting, but he would not allow it,
alledging, that it would do his people, or servants no good, and as for himself,
he thought he knew as much of the truth as we could inform him.
Indeed he seemed so whole and self-righteous,
I thought it would not avail to say much to him.
We were informed by a person who accompanied us a few miles, that this man,
in his younger years, had a public testimony to bear for the truth,
but had for a long time left it off, as he worded it,
and now his men servants must not approach him with their heads covered.
"`If the light in you become darkness, how great is that darkness.`"

From thence we went to Ury, the seat of Robert Barclay, grandson to the Apologist;
but had no meeting until we came to the Old-town, near a mile north of Aberdeen,
which was through the goodness of the Lord, somewhat strengthening.
From thence went to John Elmslie`'s, at Old Meldrum,
and on first-day morning attended Killmuck meeting,
and in the evening one at Old Meldrum, to which many people came,
and through divine favour, these meetings were satisfactory.
The next day we had a select meeting with Friends,
of whom there are several here who are tender and valuable, and we parted in love.
Going to Kingswells, had a meeting there with many Friends and others,
truth owning the service, which was cause of humble rejoicing.
Continuing at and near Aberdeen,
we had a large meeting on first-day at Robert Barclay`'s. Although the
descendants and children of Friends who were as bright stars in their day,
may value themselves on the worthiness of their parents,
yet if they do not love and serve the God of their
fathers with a perfect heart and an upright mind,
he will not own them with his heavenly presence, but they will be as unsavoury salt.

We set forward on our return towards England, taking two meetings in our way to Glasgow,
where, on first-day, we had also two which were large, open and satisfactory.
Many tender inquiring people came, who behaved well, and in the evening of the same day,
we had another with those called Friends, by themselves,
having a concern to lay before them the need
they had to look to their ways and conversation,
that they might be as lights and good examples among the people in that place,
who were seekers after the truth,
and not give them occasion of stumbling through an evil conduct.
We went to Carlisle, in Cumberland, Morehouse, Scoby, Solport and Kirklington,
in most of which meetings truth seemed to be professed,
but too few had the life thereof in possession, which occasions hard dry meetings.

We rode to Cornwood, in Northumberland,
and lodged at the house of a man who had been for several years of a disorderly conduct,
and much given to the excessive use of strong drink,
until he had very much impaired his constitution.
But it pleased the Lord to open his understanding,
and make him acquainted with his blessed truth, whereby he was made free from that evil,
and received strength to forsake his old companions.
His joining with Friends was a great grief to his wife, who informed me,
that through prejudice for a time,
she would rather he had continued his former course of living, than to become a Quaker,
until observing the sweetness of his temper and
the recovery of his health in some degree,
with a solid and sober conduct,
she was made to believe in the power by which he had known such a victory,
and joined herself in the same religious profession; they appeared to be steady Friends.
I would to God that all tipplers and drunkards would
turn to that great Prophet who is in Israel,
that they might by him be cleansed from that leprosy of sin!
We had a comfortable meeting the next day in his house,
with his neighbours and some Friends; and on first-day were at Allendale meeting,
where are some solid Friends, though others much tainted with a spirit of ranterism,
which is a confident, self-righteous spirit, and very hard to be won upon.
After having a meeting at Aldstinmoor, we passed to the meetings at Penrith,
in Cumberland, Terril and Strickland, which is in a corner of Westmoreland.
It was with some difficulty we had the meeting at Terril, a man of that place saying,
he thought it needless, or questioned whether it would be to advantage,
as most of their members had been at Penrith meeting.
But after the meeting,
he desired I would not think hardly of him for endeavouring to discourage me,
owning that he was mistaken.
I cautioned him to be more careful in future,
how he discouraged such who had come so many thousand miles to visit them.

Having meetings at divers places in the week following,
I travelled in great pain and anguish of mind, from a sense of the prevalence of a dark,
deistical spirit over many of the professors of truth,
of which concern the Lord was pleased to give me strength and
understanding to clear myself both in public and private;
there is no power but his, that can enable his servants to do his work,
and is over all the powers of satan.

On the next first-day we were at Holme meeting; in the forenoon I sat silent,
one of the stock of the old ranters was there and very troublesome,
accusing many Friends, no doubt falsely;
and in the afternoon meeting I had not much to say,
believing that ranting spirit is rather fed with words, and delights in contention.
I found it my place to exhort Friends to retire deeply inward in all their meetings,
humbly waiting to be admitted into the heavenly presence,
to know their place of feeding to be out of the reach of such ranting spirits;
for if they suffered their own spirits to rise or resist their ill usage,
the meeting would be the more disquieted.
Our next meetings were at Allonby and Broughton,
from whence I went home with our friend Christopher Wilson, to his house at Graysothen,
and the next day attended the burial of a young man at Pardsay Hall,
and the day following, the burial of a young woman at the same place,
both of which meetings were very large and solid,
and I hope through Divine goodness profitable to many.

The first-day of the following week, we were at two meetings at Whitehaven,
in both which I had some service under the influence and owning of truth.
We put up our horses at a Friend`'s house, who had been used to lodge public Friends,
but I was not free to tarry there, being burthened with the manner of his entertainment,
which was with a superfluity and grandeur, no way becoming the simplicity of truth.
After showing my dislike therewith, I went to the house of John Harris, at Highfield,
his wife being with us, and rested there a day, the weather being exceedingly rainy.

Then going to the meetings at Cockermouth, Isel and Graysothen,
we returned to Cockermouth and had a meeting with Friends by themselves, that is,
without giving public notice, which was through divine favour to good satisfaction.
Resting another day with our friend John Harris,
we went to meetings at Pardsay Hall and at Keswick,
at which last I was concerned to exhort the few
Friends there to keep up their week-day meeting,
having a fear they were very slack on that account.
We lodged at an inn, where we had the company of some of those Friends,
and in particular one who was a public Friend.
Some of them said if he would attend the week-day meeting,
they believed the rest of them would; which gave me occasion to observe to him,
that he did not example well, and ought to be more careful,
as he had a public testimony to bear for truth.
He replied that he was obliged to be industrious to support his family;
but at last confessed, that "`He did not like to sit with so few Friends,
for none else would come on a week-day, and it was very dull and poor sitting,
and he liked to sit in meetings where there were many assembled,
for then he had something to say, so life did arise and all were comforted and edified.`"

It appeared that he had greater satisfaction in preaching,
than in humble silent waiting to experience the
worship which is performed in spirit and truth,
to edification and comfort.
I told him that I feared he was too much a stranger to
pure religion and the nature of divine worship.

From thence we went to Hawkshead, in Lancashire,
and had an evening meeting there in a Friend`'s house,
and next day were at the Hight meeting, and then at Swarthmore,
where George Fox formerly lived.
Though it had been famous for the prosperity of truth, it is now at a low state there.
We went to Kendal, in Westmoreland,
where we attended their two meetings on the first-day of the week;
and after taking some other meetings in the neighbourhood, returned to that town,
in and about which we tarried several days,
and visited more than twenty families and attended ten public meetings,
many of which opportunities were made precious through the
goodness and great condescension of our Lord and Saviour.
In the school of our friend Thomas Rebanks, I had an extraordinary meeting;
where many young folks not of our Society were reached by the power of Truth,
which was comfortably over all, praised be the Lord for ever.
In the course of our visiting families here, during our silent sitting in one of them,
my mind was much taken up in thinking of a watch,
and the several wheels and movements thereof,
until I was grieved at such trifling thoughts, as I esteemed them,
when suddenly there appeared something instructive therein, and I had a freedom to say,
the several parts thereof seemed to represent the
excellent faculties and gifts bestowed on man.
Though the wheels, etc., of a watch were truly made, and placed in their proper order,
yet there must be a main-spring to give them motion;
so the gifts and faculties of men must have their
main-spring and cause of motion to every good work,
a zeal to the honour of the Lord their Creator,
and a fervent holy desire to answer the end of their creation;
and as there is a regulating spring to a watch,
so also there should be the true knowledge of
God and of themselves experienced in his light,
to preserve from going too fast, knowing by his heavenly instruction, that no wisdom,
zeal, strength or ability,
will enable to do the Lord`'s work to his honour and the good of man,
but that which God giveth.
In order that a watch may answer the end intended by its maker,
there is a visible face and hands to discover the inward motion, thereby showing time;
so it is needful that a man should be a co-worker with
the spirit and gift of grace in his heart,
that others beholding the light thereof might be taught to glorify God,
and in his light so to number his days and walk in his fear, as to die in his favour.
As a zeal for the cause of truth and a fear of falling short of duty,
may at times prompt man to rush on too fast,
it is needful that he should wait in humble reverence to feel the love of God,
and the influence of that knowledge and wisdom which is from above,
and experienced by those who are spiritual,
that the end of all their labour may be in the spirit of
meekness to restore those who are overtaken in error.
In order that men may dwell in that which gives ability
to labour with success in the church of Christ,
it is needful that their minds should be enclosed in the bosom of truth,
in humble retirement, to be preserved from the various tumults, cumbers,
cares and temptations of the world,
which would otherwise clog their minds and deprive them
of their true spiritual sense and motion.
So in a watch it is needful that all the inward parts, which are so curious,
should be enclosed from damps, vapours, motes and dust,
otherwise it would thereby be deprived of its motion and become useless for keeping time.

My intent in this relation is to show the infinite
condescension of Him whose mercy is over all his works,
to instruct the children of men, each as it were, in his own tongue or language,
suitable to his understanding; the man being by trade a watch-maker.
He seemed to be tenderly reached, and we parted in a degree of sweetness;
it was the Lord`'s doing and marvellous to me, praised be his holy name for ever!

Being clear of Kendal,
we took leave of Friends in much affection and went to a general meeting at Brigflatts,
in Yorkshire, and to visit our friend Alice Alderson,
who had been on a religious visit in our country with Margaret Cowpland,
whom we had before seen at Kendal, where she lives.
Alice was glad to see us,
and we found her tender in spirit and strong in her love to Friends.
After attendig meetings at Ravenstonedale and Grisedale,
we rode to our friend John Burton`'s, who with his companion William Backhouse,
had also been in our country on a religious visit; we rejoiced to see him,
and were comforted by his grave conversation and conduct.

We then went to a meeting at Dent,
which was large and favoured by the overshadowing of truth,
through the loving kindness of our Lord, who is worthy of all praise for ever!
Taking several meetings in Lancashire,
and tarrying two days with our friend William Backhouse,
which was an acceptable rest to us, the weather being very cold,
the ways bad and we weary, we came to Lancaster,
and had an opportunity of visiting our friend Lydia Lancaster,
who several years past had visited our country;
her faculties of mind and love to Friends appeared fresh and strong.

From thence attending some other meetings in that county,
we went to our friend Samuel Fothergill`'s, at Warrington,
where we continued from the 2nd to the 14th of the first month, new style, 1752.
He and Susanna his wife, being tender and kindly affectionate,
we were refreshed in their company, having several meetings in that town and at Penketh,
some whereof were made precious by the ownings of truth.
After many other meetings in this county and Yorkshire, we reached Richmond,
and had a meeting with Friends there,
and next morning set forward with a guide for Masham, in order to attend a meeting there,
of which Friends had previous notice.
The distance was nearly sixteen miles, the days short and roads deep and miry;
after we had road five or six miles, I desired our guide to mend his pace,
fearing we should be late.

A little further on we came to a place where the roads parted,
and he taking the left hand I became uneasy, and asked him if he perfectly knew the way.
He said he thought he did.
I let him know my being in doubt about it,
and desired him to inquire of a man we saw in a field at some distance;
but he rode on yet faster.
I told him that I was persuaded we had almost turned our backs on the way we should go,
at which he smiled; but when we had gone about a mile,
seeing a man by the way-side at work, I asked him if that was the way to Masham;
he replied, nay, you have left it and must go back,
unless your horses can leap over ditches, you may then save a mile,
and pointing over a field showed us a moor, on the other side whereof our right road was.
Our guide set forward, we followed with some difficulty over the ditches,
and he rode on a gallop and soon left us.
My mind inclined me to vary from his course, and espying a gate, called to him,
pointing to it and proceeded thither, on which he turned and came up,
but said he believed we were wrong.
I let him know that my mind was easy to go that way,
and in a while we came into a road at a public house, which he knew to be right.
We just reached the meeting in time,
which through divine favour was profitable and edifying.
I mention this passage with no other view than to
encourage Friends to be inward in their minds,
and to regard the secret sense which the pure Spirit of
Truth sometimes gives on particular occasions:
for want of an inward stillness and attention thereto,
the way is often missed in more respects than one.

At Masham we lodged at the house of John Kelden,
who related to me something that passed between
a knight of the shire and one of his tenants,
a member of our religious Society, as follows, viz:

[.discourse-part]
__Landlord.__--So John, you are busy?

[.discourse-part]
__Tenant.__--Yes, my landlord loves to see his tenants busy.

[.discourse-part]
__Landlord.__--But John,
where was you that you was not at your quarterly meeting at York the other day,
I saw most of your staunch Friends there, but you I missed?^
footnote:[The assizes are held at York, always at the time of the quarterly meeting.]

[.discourse-part]
__Tenant.__--Why thou knowest I have a curious landlord,
who loves to see his tenants thrive and pay their rent duly,
and I had a good deal in hand that kept me at home.

[.discourse-part]
__Landlord.__--Kept you at home!
You will neither thrive nor pay the better for neglecting your duty, John.

[.discourse-part]
__Tenant.__--Then I perceive my landlord was at quarterly meeting, how didst thou like it?

[.discourse-part]
__Landlord.__--Like it!
I was at one meeting and saw what made my heart ache.

[.discourse-part]
__Tenant.__--What was that?

[.discourse-part]
__Landlord.__--Why the dress of your young folks, the men with their wigs,
and young women with their finery, in imitation of the fashions;
and I thought I would try another meeting, so next day I went again,
and then I concluded there was little difference but the bare name,
between us whom you call the world`'s people, and some of you;
for you are imitating us in the love and fashions of the world as fast as you can;
so that I said in my heart, these people want a Fox, a Penn and a Barclay among them,
and so turned from his tenant.

[.small-break]
'''

I thought it would be a pity that the true and solid remark of this man should be lost,
understanding that it was rather expressed in pity than derision.

From Masham we proceeded to visit many other meetings in this county,
and called to see good old John Richardson, who was strong in spirit,
though feeble in body, and nearly blind through age, being about eighty-seven.

Finding a draught to visit Friends once more at Scarborough,
we were there on first-day the 15th of the third month, and had peace in my own mind,
having done what I thought was my duty; but from a sense of the prevalence of pride,
which had occasioned a great poverty as to true
religion among the professors of truth in that place,
I left them with an aching heart,
and went on our journey in order to attend the quarterly meeting at York,
taking meetings in our way.
The several sittings of this quarterly meeting were in the main satisfactory,
but not having time fully to clear myself, I did not leave York quite easy;
after which having had a number of meetings,
we attended the quarterly meeting at Lancaster,
which began on the fifth-day of the week with a meeting of ministers and elders,
and was comfortable; next day was the meeting for public worship and the discipline,
wherein we were made to rejoice together and praise the
name of the Lord who is worthy forever.
Went to Kendal quarterly meeting, which was satisfactory and very large;
then set out for the quarterly meeting for Cumberland, held at Carlisle,
which began with a meeting of ministers and elders;
next day were held two public meetings, and the day following a meeting for discipline,
which ended in the afternoon with another for worship;
and going home with Christopher Wilson,
we were at a good meeting at Pardsay Hall on first-day.

My mind had been for sometime drawn towards Ireland, and being desirous to lose no time,
we went to Whitehaven, several vessels being there for Dublin;
but on viewing them I had no freedom to take a passage, at which I was much straitened.
Turning my mind inward, Ireland was hid from my view, and going to the house of a Friend,
we sat a while still,
and I had freedom to let Friends know that I had no prospect
but the vessels might go their voyage with safety,
and did not decline a passage on that account; but feeling a full stop in my mind,
had no freedom to proceed any where at present,
save to return with our friends John and Hannah Harris, to Highfield.
We therefore returned with them, and attended Pardsay Hall monthly meeting,
where I had freedom to propose that Friends
would enter on the service of visiting families.
They informed me that some years before they had nominated Friends for that service,
but meeting with some discouragement, they had not performed it;
and being about to turn over the book to see who were then appointed,
considering it was a long time since,
they concluded it was better to proceed to a new choice,
but seemed at a stand about naming Friends.

I had a freedom to let them know, that although I was a stranger,
I could point out some who I believed would
answer the service if they would submit to it.
After a solid pause, a Friend said, As our Friend has the matter before him,
I am free that he should choose for us; to which I replied,
that being a stranger to their members,
one might be chosen who was under some impediment,
and therefore it would be safer for the meeting to choose;
but perceiving they were at a loss, I pointed out a few Friends in great fear,
with a single eye to the sense which I did believe truth gave me,
and the clerk took their names;
a Friend said he believed it was the truth which had made the choice.
I then mentioned, that if they could soon enter upon the service,
I found a freedom to accompany them therein, if Friends had unity therewith,
which several expressed,
some women Friends being also named by their meeting to join in it.
Before the service was much proceeded in,
a heavy concern came upon me from a secret sense I had,
that one of them was under the censure of some,
by which I feared her service would be laid waste, unless it could be removed.

Although I had no intimation of any thing of the kind from any person,
I became heavily exercised,
and at length requested a Friend to invite the man and his wife to dine with him;
who I apprehended were uneasy with the woman,
and I desired her and her husband to come to the same house in the afternoon,
who accordingly came, and thus the parties met unexpectedly to each other.
I was humbled under the weight attending my mind,
and no others being present except the Friend and his wife at whose house we were,
I ventured to let them know the exercise I had been under some days,
from an apprehension of a difference, or prejudice subsisting between them,
which if not removed would devour like fire,
by which I believed they were already much affected.
As I had not received information, more or less, I might be mistaken,
and did not desire they should say any thing on the subject before me,
but honestly confer on it between themselves first, and if it was so, remove the cause,
and if nothing was amiss, then to let me know,
that I might be warned to be more cautious in future.
I then left them and walked by myself about an hour,
when the man of the house called me in, and they told me I was not mistaken,
for there had been an hardness subsisting for sometime,
which they hoped was now done away.
But when in the course of our visit,
we came to the house of the Friends who had been uneasy, I felt it as fresh as before,
and told them I did believe they were not easy
that the Friend should go on in the service;
to which one of them answered, if she judges herself to be clear and others are easy,
I have no objection.
I asked what others were meant.
The man replied, her husband and relations; and as the matter rested upon me,
it appeared that endeavours ought to be used for reconciliation
before we could with satisfaction proceed on our visit.
Believing the Lord had secretly engaged me,
I hoped he would accompany and bless the labour for the restoration of peace,
which in a few days he was pleased to accomplish, and then we proceeded more cheerfully,
and I think I may say that the Lord was with us,
to the praise of his great and eternal name, who is worthy for ever.

We visited the families of Friends in Whitehaven, Broughton, Cockermouth, Pardsay Hall,
Eaglesfield and Graysothen, and others more remote,
and had several profitable public meetings in those towns and places adjacent.
Having spent about seven weeks within the verge of Pardsay Hall monthly meeting,
and finding my mind clear, we went to Whitehaven and took passage in the ship Globe,
James Grason master, for Ireland, on the 8th of the sixth month, 1752, new style,
and parting with our dear friends in much love,
set sail about the fifth hour in the evening,
and landed at Dublin on the 11th of the same month,
and were kindly received at the house of Samuel Judd.
As I was going there, this secret hint was presented to my mind, "`Live retired,
and be not suddenly acquainted with any man.`"
After dinner our kind landlord said,
I do not well in that I have not informed Friends of your arrival, they will blame me.
I answered, let us first know that we are here, we have just come from sea and are weary.
We had a troublesome passage by contrary winds and heavy rains, John Pemberton,
my companion, having been very sea-sick, and myself a little so.

The next day we attended Sycamore-alley meeting,
where we had the company of Susanna Hatton, who had been in America with Ruth Courtney.
We were at eight meetings in Dublin,
also at a monthly meeting and a quarterly meeting for their young people,
in which I was deeply concerned on account of the
prevalence of pride and the world`'s fashions,
which was declared to them in the love of truth;
and the Lord was pleased to favour several of the meetings by his heavenly presence,
to the praise of his holy name.

Leaving this city we went towards the north:
at Drogheda there is a meeting house belonging to Friends,
but they are there so declined, we could not have a meeting to satisfaction.

We therefore went on to a meeting with a few Friends at Rathfriland, then to Monallen,
where the meeting was comfortable; and on first-day had two meetings at Lurgan,
at which place pride and a worldly spirit much prevail.

Taking meetings at Newton, Lisburn, Hillsborough and Ballinderry,
the last of which was a large good meeting; we had one at Antrim,
where the savour of truth seems much lost by the few professors there.
We then passed on to Grange meeting, which was very dull,
through the prevalence of a worldly dark spirit,
and from thence to a meeting at Ballynacre, and to Colerain,
where we had a satisfactory opportunity with some of the town`'s people,
who came to the meeting out of curiosity.
I felt no freedom to express the sense I had of the state of Friends then,
and as the meeting broke up, I stepped to a young woman, a Friend,
who lived near the meeting house,
and desired her to step forward and turn the few Friends in there, as she knew them,
and let the others go by, which she readily performed.
When we were all set down,
it soon felt to me that if I delivered my concern in general terms,
the intended end would not be answered, being in pain for their good,
and close matters spoken might be taken by those to whom they least belonged;
and being greatly humbled, I was desirous to be rightly instructed,
not knowing their names, to speak to them separately.
The Lord, who never fails those who humbly trust in him,
showed me where and with whom to begin, and so to the next;
and mine eye being fixed on the person to whom I directed my speech,
each knew what was delivered to them in particular,
and I hope the opportunity was beneficial; for I had great peace.
When the Friends were gone, I asked the young woman, who seemed in some surprise,
what ailed her; she said that several were very exactly told their condition,
and feared they would judge her for an informer.
I told her she need not matter that, as she knew herself to be innocent.
I mention this occurrence as a remarkable kindness from
the merciful Lord to the children of men,
for their help and instruction,
and that his servants may be encouraged to wait upon him for
instruction to discharge their duty as faithful stewards in his sight,
who knows the secrets of all hearts,
and taught his servant in old time to know the wife of Jeroboam,
though she feigned herself to be another woman.
Blessed and magnified be his holy name, who is over all worthy for ever and ever!

Taking meetings at Toberhead, Charlemont and Ballyhagan,
we attended the men`'s meeting at Lurgan,
having a great desire to sit with Friends there in the management of their discipline,
which was adjourned to this time at my request.
It began with a meeting for worship, men and women being generally together,
at the conclusion of which,
the men went into the room where the meeting for business was usually held;
when after sitting sometime in silence, a leading Friend said,
this is only an adjourned meeting, and bid the clerk enter it,
and they might adjourn to the usual time to do their business,
when it would be more select.
The meeting sat a while without proceeding any way,
and I asked them what was meant by the words,
"`more select,`" observing that if any persons
were present who had not a right to sit there,
they should withdraw; they knew their own members.
If they meant the Friend who came with us, he was a neighbouring Friend and an elder;
and I esteemed myself a proper member of their meeting,
as I came to visit them with the concurrence of my brethren at home,
and had certificates from them,
wherein I was recommended to Friends in Europe and elsewhere,
and if I did anything among them worthy of censure, I should submit to their dealing.
I therefore desired them to go on with their business,
for I had come thither with a concern to see how the affairs of the church went on.
Without more debate or much reply they proceeded, and to my surprise,
things of disorder had lain several years without proper dealing with various offenders,
such as drinkers of healths, some that had been at cockfightings and races,
and one or more marriages out of the order of truth;
which gave me an opportunity to clear myself fully of the
concern that had for some days lain with weight on my mind,
which I believe was acceptable to some secretly pained Friends,
however contrary to some others.
I left the place with a peaceful mind,
and thankful to the Lord who had given me an innocent
boldness to assert my right of membership;
for I believe if we had not been there, the meeting would have been thought select.

We then went to Ulster province meeting at Ballyhagan, which held two days;
the elders and other concerned Friends here inquire into the
state of things among their members in the province,
and it was in the main a satisfactory meeting.
From thence we went southward, taking meetings at Castleshane, Coothill,
Ballyhais and Old Castle, and to Ballymurry, in Connaught,
having a meeting in a barn at Gailey, with a few Friends,
it being the only one kept up in that province, except at Athlone,
which we likewise attended, and came to James Clibborn`'s, at the Moat of Granoge,
where we also had a meeting.
I had travelled every day for more than a week with a fever on me,
occasioned as I thought by a cold taken by lying in damp beds, and was now very unwell,
but sat the first-day meeting.
Next day my illness became very violent,
so that Friends thought I should lay my body there, and sent for an apothecary,
who bled me, which somewhat allayed the fever, and I fell into a sleep,
when I began to bleed again, which brought me very weak,
that I was awakened at midnight with great drops of sweat on my face, and sickness.
Calling my companion, who watched with me, we found that I had bled much,
the orifice in my arm being very large and not carefully bound up.
My kind landlord and his wife being anxious about me,
had prevailed with the apothecary to lodge in the house, who being called to me,
on his coming I desired him to peel a bladder and apply
a thin piece of it about as broad as a half-penny,
on the wound.
He asked for what; I told him he would see, and when it was applied,
I requested him to hold his finger on the piece over the orifice,
so as to stop the blood, until the plaster dried and stuck,
which it soon did and it bled no more; he said that he had not seen the like.
Next morning a physician of the town came to visit me, and feeling my pulse,
I asked him what he thought of me?
He making no answer, I said,
"`Be not afraid to tell me, for I am not afraid to hear;`" he replied,
"`That is happy for you;`" by which I supposed he thought I should not recover.
He said I was in a deep consumption, and he visited me daily for a week,
and could hardly believe I should recover, though I told him I believed I should.
He still judged my cough to be consumptive, and at length told me, if I did recover,
to go home as soon as I could,
for that the Lord was more merciful than to
require such an one as I was to travel as I did,
and that I had already acted as a madman,
to travel so long time with that fever before I lay by.
I asked him,
if he was master of a vessel at sea which had sprung a leak that could not be stopped,
what he would do?
He replied, endeavour to make to the next port for a dry-dock,
to unlade and search out the leak.
Why doctor, said I, this is just my case; I saw no place to lay by until I came hither,
at which he laughed, and wished me well.
I think I never was reduced to so weak a state in so short a time,
which might be occasioned by my great loss of blood; but the Lord was pleased to heal me.

I gathered strength to admiration, and on first-day sat the meeting,
which was comfortable, and continuing to recover, though not fit to travel,
I tarried until fourth-day and attended their monthly meeting.
Understanding they had been endeavouring to visit families,
but were backward in beginning,
I told Friends I had a freedom to accompany them in the
work for a few days for their encouragement,
and we accordingly went with them to a few places to good satisfaction,
and Friends received strength to go on with the service.

Taking an affectionate leave of our kind landlord James Clibborn and his wife,
who is grand-daughter to Robert Barclay, the Apologist, we went to meetings at Birr,
Kilconnermoor, Cashell, Killcommon, Glonsmell, Youghall,
and so to Cork on the first-day of the week,
where we also attended the men`'s meeting for discipline, and visited the women`'s meeting,
which were both to some good satisfaction.

Then going to Bandon,
we returned to an appointed meeting at Cork for parents and their children;
and having strength given me to clear myself, it was, I hope profitable to many,
being a large meeting.
At Malo, we had a seasonable opportunity with a family of Friends,
thence to the province meeting for Munster, held at Limerick,
the public and select sittings of which and for the discipline, ended comfortably;
and after attending the week-day meeting, we went to a meeting at Ross,
and returned to Limerick.
Being unwell with a cold, we tarried their meetings on first-day,
which were large and satisfactory, and in the evening had one with a sick Friend;
and taking three meetings in our way,
we proceeded to Leinster province meeting at Mountmelick,
which began on the sixth-day of the week with a meeting of ministers,
the next day for worship and the discipline,
and on first-day morning was a large and precious meeting.
In the afternoon the town`'s people came in and it was a good satisfactory meeting,
though not so large.
Friends being mostly gone home.
We had a meeting next day at Tullamoor, and returning to Mountmelick,
had a satisfactory one with the children in James Gough`'s school.

After the week-day meeting in this town, we went to Ballacarrol,
Ballanakel and Cooperhill, having a meeting at each;
then to Catherlough monthly meeting on first-day, and the next day to Athy;
then to Ballitore, which was through Divine goodness, made profitable,
and we had also a satisfactory meeting with the scholars in Abraham Shackleton`'s school.
After a meeting at Newton, we went to Samuel Watson`'s, at Killconner, whose wife,
late Abigail Bowles, had been on a religious visit in America several years before.
She was now near her end, but sensible and in a good frame of spirit,
and greatly rejoiced to see us,
and we were mutually comforted in a sense of the Lord`'s presence,
for which his holy name was praised.

We went to Waterford, and sat with Friends in their morning,
afternoon and evening meetings on the first-day, in all which,
having cleared myself honestly,
my spirit mourned under a sense of formality among the people,
and a deadness to the pure inward life of religion.
Taking meetings at Ross, Lambstown, Wexford, Randal`'s mills, or Castlesaw,
Cooladine and several other places, we came to Wicklow,
at which meeting many soldiers attended, who behaved well,
and truth owned the service in a good degree.
I have observed where the soldiers came into our meetings,
they were an awe to the rabble and loose people, who are sometimes apt to be rude.
We went to Dublin, in order to attend the national half-year`'s meeting,
and were kindly received by our old landlord, Samuel Judd and his family.

Leinster province meeting began on second-day, the 6th of the eleventh month,
and on third-day the national meeting, which held four days;
the several sittings thereof being in general attended with a sense of Divine goodness,
and the testimony of truth ran strong against hypocrisy, covetousness, libertinism,
and pride among the professors thereof;
but in a consolatory stream to the humble and contrite children of the family,
in a thankful sense whereof the name of the Lord was praised,
who is worthy for ever and ever!

We tarried a few days longer with Friends in Dublin,
and then went to meetings at Baltiboys, Timahoe, Rathangan and Edenderry,
and a religious sitting in John Pim`'s family at Nurney.
Returning to Edenderry, attended their monthly meeting,
where having a concern to visit some families of Friends,
we went to most of them in that town, and to the house of a widow in the country,
where we had a good opportunity with her and her children.
I asked the Friend who accompanied us,
whether there was any other Friend`'s house to which we had not been;
he said he thought not.
My mind had a draught to some house, and I pointed toward it,
he then said he believed he knew where; so we went to the place,
and the family being called together,
I inquired whether there was not another belonging to the house, and was told there was.
As soon as he came, I knew it was the man whom my mind was concerned to visit,
and something I had to express reached and tendered him very much,
he being exceedingly wild and fashionable, and did not love to attend religious meetings,
but truth now reached him.
On the first-day following I saw him at Edenderry meeting,
where the visitation seemed to be renewed to him;
I afterwards heard that he continued to be sober and thoughtful,
and I was thankful to the Lord that he was pleased to
condescend in mercy to gather the outcast of Israel.
Being clear of this place, I returned to Dublin,
and having a concern to visit the families of some who made profession of truth,
but were disorderly in their conduct--we began that service,
being accompanied by several Friends, and the Lord was pleased to own the work.

During our stay we were careful to attend all the
meetings in this city for worship and discipline,
one of which was a quarterly meeting for the youth,
in which many were tendered by the love of God,
through Jesus Christ our Lord and Saviour.
We visited about sixty families,
in most of which the Lord was pleased to favour with authority to set the
testimony of truth over the heads of the corrupt disorderly professors,
and to influence with understanding to divide the word and
counsel of truth to the different states of those we visited;
in an humble sense whereof, let my soul obey and adore Him who is alone worthy for ever.

As I apprehended the women`'s meeting to be deficient in doing
their part as true helps in the exercise of the discipline,
and a proper care over the flock and family of the Lord,
a weighty concern attended me to express in writing my sense
of what was the proper business of women`'s meetings,
which I showed to the men friends,
and had their concurrence to lay it before the women`'s meeting,
in order for their encouragement and practice in the wisdom of truth;
and it was afterwards sent to the women`'s meetings throughout the nation.

The vessel in which we came to Ireland being ready to sail,
and the master desirous of our company to return with him,
I felt so clear and easy that I intended to go;
but when he sent us word to come on board, I was more inclined to stay that day,
and went to meeting, being first-day, and he sailed.
But meeting with contrary winds and dark weather,
he was obliged to put back into Dublin harbour after about a week`'s fatigue;
my being withheld from embarking,
I thought was a remarkable kindness and favour from my great and good Master;
praised be his name!
We had afterwards several good meetings,
in some of which it became my concern to recommend silence by example,
of which they stood in much need; and on the 23rd of the first month, 1753,
after having travelled in Ireland thirteen hundred and fifteen miles,
and had one hundred and thirty-four meetings, besides many family visits,
feeling my mind to be fully clear, we went on board a ship of Whitehaven,
Allen Wilson master, having in much love taken leave of our friends.
After a short, but rough passage of about twenty-three hours, we arrived at Whitehaven,
with hearts humbly thankful to the Lord who had preserved us;
the master saying that he had not known the like for twelve years,
although he had sailed between the two ports very constantly.

Next day after our arrival, our friend John Harris, of Highfield,
with whom we had left our horses, brought them to us and we went home with him,
visiting the meetings in the neighbourhood; several of which,
particularly the last at Pardsay Hall, were large and precious opportunities,
and I thought I could perceive that my former
painful labours among them had been blessed,
for which I was truly thankful to the holy Head of the church,
and the Master of the assemblies of his people.

From thence we went to Lortonhall and had an evening meeting with the people of the town,
to which came the priest and most of his hearers;
and although the craft and conduct of the hirelings were set forth,
all was quiet and it ended well.

From thence we went to Kendal, and staying a general meeting there,
proceeded to others in Yorkshire and Lancashire, and to one we had appointed at Coin,
where are no members of our Society, and though a poor dark town in respect to religion,
the people behaved soberly, and many were tendered by the gentle,
yet powerful reaches of Heavenly goodness.
I may say, that in riding through some towns in England where no Friend dwelt,
I felt a secret salutation of love to the inhabitants, though as a seed yet ungathered;
but my present business in general was to the children of the family,
that when it shall please the Lord to open the eyes of others to behold Zion,
no stumbling-block may appear to offend beholders, or dim her heavenly beauty.

At Halifax we had a large open meeting, and divers others in Yorkshire,
until we came to Sheffield, where we visited some families to our satisfaction,
and after attending two meetings in Derbyshire, returned to John Haslam`'s,
and again to Sheffield, and sat their morning meeting on first-day,
and in the afternoon attended the burial of Ellen Atwick, a Friend of good repute,
to which many people came, and I had a favourable opportunity.
I went to Blythe, in Nottinghamshire, and had a meeting,
and several in other towns this week, and reached Rawcliff, in Yorkshire, on first-day.

On the night before, I had a dream which much affected me;
"`I thought I heard a kind of melody and singing at my left hand, whereupon I said,
what do ye rejoice at?
But it continuing, I said,
your singing is somewhat like David`'s rejoicing before the ark, but I see it not.
I then heard a voice on my right saying, the ark is in the land of the Philistines,
where it was taken through the wickedness of the priests and the sins of the people,
who removed the ark from Shiloh to strengthen them in battle.`"
I awoke and was under some exercise for a time, concluding it was ominous,
but saw no further, until we went to meeting in the forenoon,
where I soon heard a kind of tuneful sighing, which kept increasing;
and turning my head to discover from whence it came, found it to be at my left hand.
After a while a person stood up and spoke a few sentences of
extraordinary enjoyments which were to be felt.
My mind was pained, and after he sat down I stood up and said, "`What are ye doing?
and what do you feel to occasion this rejoicing?`"
and should have proceeded to have told them my thoughts,
but instantly my dream came into my mind,
and so with little addition I sat down very sorrowful.
After the meeting I went to dinner, but could not eat much or be cheerful.

At the afternoon meeting we had the same tune until my spirit was afflicted;
but labouring to know that quiet which is not easily disturbed,
I received strength in a loving frame of mind to inform them,
that I feared they were mistaken in their states and conditions, for that death reigned,
and it was rather a time of mourning.
As truth arose in some good degree, that formal spirit became dried up;
and in the evening having the company of the chief singer among them,
I had a freedom simply to relate my dream to him,
with a desire that he might examine whether the ark enclosing the pure testimony,
was preserved safe amongst them; which shut up further conversation.
In a few days after, an intimate friend asked me how I fared there;
I repeated to him my dream, and he told me it was very significant,
for that a withering had taken place in that meeting,
and that man had several children who were
married to persons who did not profess with us;
and being treated with as a parent,
he said it might be a means of increasing the meeting,
if those they married came to meeting with them,
and discouraged Friends from dealing with them, lest it should prevent them.

Then taking a meeting at Selby, we proceeded to the quarterly meeting at York,
which continued two days, and was a good meeting.
Here we met my brother, William Brown, to our mutual comfort,
after a separation of nineteen months; we soon parted again, he going towards Lancaster,
and we to several meetings in Yorkshire and some in Lincolnshire.

In some places I observed the form to remain and life to be wanting,
and in others the professors of truth are too generally declined from both.
True life gives birth to a true form;
but the mere form will never produce the life of truth.
From thence we went to Retford and Mansfield, in Nottinghamshire,
and at the last town had two meetings, one of which was with Friends by themselves;
for it did not always appear convenient to deliver too publicly,
those things which tended to the reproof of some disorderly walkers in the family,
lest it should rather harden than restore and heal,
especially where their conduct did not occasion open reproach.

Taking a meeting at Broughton, we went to Nottingham,
and had three meetings there on first-day; next at Oxham,
with a few Friends who were glad thereof, being sometimes missed by travellers;
and the day following we had an appointed meeting at Nottingham to satisfaction.
In this place they are troubled with some ranters,
who force themselves into meetings for discipline.
Friends were exhorted to keep up the testimony
of truth in the meek humble spirit thereof,
in which its dominion will stand for ever.
We spent some time in visiting meetings in Leicestershire, taking one at Oakham,
in Rutlandshire, where some innocent Friends live,
and I think it is the only meeting of Friends in that county.
At Boswellstreet we had a meeting with some who had been lately convinced,
but had not yet known a true establishment in humbly waiting for the power of truth,
to give a solid growth in pure religion.

The same evening we had a meeting at Coventry to good satisfaction;
and the week following came to Dudley in Worcestershire,
where we lodged at James Payton`'s,
whose sister Catharine was preparing to go on a religious visit to America.
Staying the meeting on first-day in Dudley,
we went to others in this county and Warwickshire, and came to Eaden in Northamptonshire,
to which meeting many people came, some of whom were very unruly,
but the power of truth prevailing, it ended quietly,
praised be the Lord who is all sufficient for his own work.
At a meeting held in an evening at Chipping-Norton there were many tender young people,
to whom I felt a salutation in the love of truth;
but before I thought it safe for me to stand up,
a young man not much like a Friend stood up,
and began to exhort them to be faithful in
discharging whatsoever the Lord required of them,
and how eminently he would be with and qualify them for his work,
as though they were all appointed to enter upon some extraordinary great service.
My mind was much grieved,
for I thought it would be more suitable for them deeply to
retire and wait for the virtue of truth and sap of life,
to experience a growth in grace and the knowledge of God,
that they might be prepared to work out their own salvation.
To expect a young tree to produce abundance of fruit before the
branches are come forth and spread with strength to bear it,
is not reasonable.
The words, "`sit down,`" passed through my mind for some time,
and at length I spoke them so that he heard, which I perceived by a small stop he made;
but going on again, I said prithee friend sit down, which he did.
I felt that my saying so, surprised the people and perhaps offended some,
and that it would be in vain to deliver what was on my mind,
so expressing a few sentences only, I sat down very sorrowful, and the meeting ended.
I was informed by a Friend at our lodgings,
that he was one lately come from the Methodists,
which I before apprehended by his appearance.
On going to bed I was much concerned lest it should hurt him,
and deeply sought to know whether I had not spoken to him in a selfish spirit,
because he had taken the time of the meeting appointed on my account,
and feeling love towards him,
I prayed in spirit that the Lord would be pleased to preserve him from harm thereby,
and that if I had done wrong,
I might be made sensible of rebuke for my future instruction;
when in great calmness I understood that it would not hurt him.

After a meeting the next day at Sibbard,
a woman Friend who was at the meeting the evening before,
desired me to send by her a message, or write to the young man,
for she was fearful he would go beside himself;
I told her that when I spoke to him I thought myself right, and knew what I was about;
but now I could not see what to do at present, and to act by her direction was dangerous,
so we parted, and in about a week after,
a Friend let me know that there was no danger of his receiving hurt,
but hoped he would be benefited.

Taking a few meetings on our way, we arrived at London on the 7th of the sixth month,
and next day attended Grace-church street meeting,
and in the following week the yearly meeting, which was comfortable and solid,
divers weighty matters being therein proposed
for consideration from several of the counties,
which tended rather to benefit.
In the management of the affairs,
there appeared in some a disposition to oppose what they thought to be new,
notwithstanding the same things appeared very expedient to others,
who from their views thereof, might urge their sentiments rather too strongly.
A prospect of the Lord`'s servants truly disciplined, armed and qualified for his work,
and of such who equip, arm and arrange themselves, and move by their own direction,
was presented to my view in a dream one night during the time of this meeting;
"`I thought I beheld two armies set in array against each other,
one of them well armed with swords and muskets;
the other had no weapons for their defence,
but a charge given them by their general to keep their ranks,
and gently to march directly forward as he should lead,
no man reaching forth his own hand to defend himself.
They joined in battle,
and when one of the unarmed soldiers was borne hard upon by his opponent,
he reached forth his hand at arms length, when a sword took off one of his fingers,
and the blood sprinkled on several of his fellow soldiers;
whereupon knowing the orders given, I cried out,
if that hand had not been so stretched out, this wound would not have been received,
and so I awakened.`"
On the morrow I was fully convinced that in transacting the affairs of truth,
the honour of God should be our only view, with a single eye to his direction,
and self made of no reputation,
which will be a shield against all reflections and personal censures.
It so happened,
that a valuable zealous Friend being strongly reflected on as a prejudiced party,
and a little warmed thereby, made an over hasty, and perhaps too warm a reply,
which is apt to stir up warmth in those who
depend on no other guard than their own armour,
and with their own strength use a selfish weapon; by this unguarded reply,
the Friend brought a reproof on himself and some others,
that were united in the cause of truth.
The victory belongs to the Lamb for ever, who when he was spit upon and reviled,
did not again revile.

After staying in London and attending the Peel meeting on first-day,
and the meeting of ministers and elders on second-day morning, we went to Chelmsford,
and rested a day or two with our friend John Griffith,
attended their week-day meeting and a general meeting at Easterfordkelvedon,
and proceeded to the yearly meeting at Colchester,
which held three days and was a time of Divine favour.

Then going to Ipswich and to a monthly meeting at Woodbridge,
we continued there on first-day, and on the next began their yearly meeting,
which held until the fourth-day of the week, in all eight sittings,
some whereof were large and very good.
No praise to him that willeth, or to him that runneth,
but to the Lord alone that showeth mercy.
There being a marriage at the meeting on fifth-day, I had an open time,
wherein I had to set forth,
that as man in the beginning was taken from the earth by the hand of the Lord,
and a life breathed into him different from the earth, by which he became a living soul,
and stood in the image and liberty of his Creator,
but falling from the heavenly image and liberty therein through transgression,
he is now of the earth, earthly in his love and liberty,
so he must be separated from the earthly low estate
which stands in the transgression and death,
by the regenerating Word of power, and transformed by the renewing of his mind,
will and affections, and placing them on heavenly objects.
For as the potter separateth the clay from the other earth,
and tempers it by itself before he formeth and maketh a vessel thereof,
so must man by the operation of the Heavenly hand, be tempered, wrought, prepared,
and freed from his own stubborn will, and made submissive to the Heavenly will,
that he may not be marred on the wheel,
but bear the turning of the Heavenly hand until he be formed a vessel to honour.
But if the will of man does not become subject, but stands in rebellion,
the Lord who said,
"`My spirit shall not always strive with man,`" hath power over the clay to
reject that which will not be wrought into a vessel for honour,
and suffer it to be marred in its own stubborn will.
When an earthly potter hath formed a vessel for use, he carefully setteth it aside,
until it be prepared to bear a further operation,
to harden and glaze it for the use for which it is made;
if man should put even water into an earthen vessel formed for that use,
before it is hardened and prepared by fire,
he would both mar the vessel and expose that which was put therein.
Let not such therefore who have known the Heavenly hand so to prepare them,
that they are willing to be whatsoever the Lord would make of them,
marvel if the Lord should be pleased to set them by a while for the trial of their faith.
If the earthly potter`'s vessel should crack in drying, it would be marred,
so if these vessels of the heavenly Potter keep not the
word of his patience in this their drying season,
to prepare them for the operation of the heavenly fire and furnace,
in which the Lord will sanctify and fit his vessels for the use of his holy sanctuary,
they will also be marred;
but otherwise they will come forth vessels of honour in his house.
I thought this was a remarkably good meeting,
the praise thereof belongs to the Lord alone.
We had also a select meeting with Friends,
and visited several families in the town to satisfaction, truth owning us together,
and after a good opportunity at a Friend`'s house in the country on our way,
we went to Norwich and attended their meetings on first-day.

The yearly meeting began the next, and ended on fourth-day,
after seven sittings generally large and satisfactory,
through the overshadowing of Divine goodness.
I continued in this city several days after,
visiting families and steadily attending their meetings,
and had some open satisfactory opportunities.
My way now opening for Holland we went to Yarmouth, several Friends accompanying us,
and on the 26th of the seventh month, embarked on board the ship Three Brothers,
Richard Smith master, my companion John Pemberton, being willing to continue with me.

On the first-day of the week following, we landed at Rotterdam and lodged at an inn.
Next morning feeling my mind drawn forward, we went in a stage wagon to Turgow,
and from thence in the track-skute to Amsterdam in the evening,
the metropolis of South Holland,
and were conducted to Friends`' meeting house at the Three-hooks, in Princes`' street,
in which Michael Laars and his sister lived, and were kindly received,
and rested the next day.

I found a concern to visit the families of Friends in this city,
in which service we spent most of the week to our satisfaction, John Vanderwarf, jr.,
being interpreter; we also attended their week-day meeting,
in which Peter Linders was interpreter.
On first-day following, the meeting in the morning was pretty large,
and many people came to that in the afternoon, some of whom behaved rudely;
but truth came over, and they were stilled, and seemed to depart satisfied.
We continued here until their week-day meeting again,
which many not of our Society attended, and it was to general satisfaction,
I then felt my mind drawn towards North Holland, and taking passage in the track-skute,
passed through several towns and arrived at the city of Hoorn,
where we were met by our friend Cort Hendricks,
who took us in his wagon to his house at Twisk, in North Holland, the same night.
Here finding the like concern, we visited the families of Friends,
and had a meeting with them in the evening.

Next day we went to Abbey Kirk, a village about two miles distant,
where about five or six families of Friends live, whom we visited.
Friends generally seemed to receive our visits kindly, except one family,
where I was concerned to open that saying of our dear Lord,
"`Except your righteousness exceed the righteousness of the scribes and pharisees,`"
etc for I was much burthened under a sense of a self-righteous,
exalted spirit; and in opening that passage,
was also led to speak of the parable of the pharisee and publican,
who went up into the temple to pray, which probably touched the heads of that family,
and I felt a strong opposition in them,
and perceived the passage was not pleasing to our interpreter;
I could not shake off my burden, yet was preserved quiet in my mind,
having honestly done my part.
Returned to Twisk, where the meeting was held for both villages,
and on first-day morning was pretty large.
Friends being generally there; but our interpreter had most of the time,
so that he was too far spent to interpret much for me.
Several not professing with us, attended in the afternoon,
and I had a satisfactory time with them early in the meeting,
when an awful sense of truth seemed to be over us,
after which our interpreter had something further to say.
I have often lamented the increase of words,
and a repetition of former experiences without the renewing of life,
which disposition seems to prevail in too many,
burdening the sensible members in our Society.

As we sat this evening in a Friend`'s house at Twisk, two elderly women came in,
professors of truth, but very talkative.
I had seen them several times before, and been burdened with them,
and now had something to speak to them;
but feared such plain dealing would be too strong for our interpreter,
who appeared to be very sociable with them;
therefore I delivered my mind without singling them out, several others being present.
These women took it to themselves, but not in such a disposition as I desired,
being disturbed; they followed us to our lodgings,
and made their complaint to our interpreter,
bidding him ask me if I took them to be such persons as I had described; if so,
they desired to know what I had to accuse them with?
At first it put me to a stand, but being still,
I soon thought it was providential that they thus gave me an opportunity to
clear myself of the burden I had borne on their account.
I told them that to enter into particular charges was not my business,
but was free to let them know that I had been in pain
on their account from the first time I saw them,
and that if I had a true sense of their states, they were not such as they ought to be,
but had lost the savour of what they professed to enjoy, and could so freely talk of.
I told one of them that I took her to be dark and ignorant of her own state;
and the other, that she was too light and chaffy in her spirit,
and that they both wanted the true clothing of the Lord`'s children,
which is humility of heart and reverence of spirit,
which would season all their conversation and conduct,
that they would not be stumbling blocks to their neighbours, as I feared they were.
I also told them, that I believed when I spoke as I did at the Friend`'s house,
it belonged to them, in which I was now confirmed, for had they been sincere hearted,
they would have borne it without flinching;
but they had shown that their sore places were touched,
and I dared not to lessen the weight of what was then said, but desired them,
to receive and ponder it well; for I was sure it was delivered in love,
and believed it to be a visitation to them in their old age.
This being interpreted to them,
they spoke something to the interpreter which I did not understand;
then one of them said she had yet love in her heart for me:
I told her I had nothing but good will towards her, and so they went away.
Afterwards the interpreter told me he had known these women many years;
that I had a true sense of them, and he had delivered my words honestly,
and hoped they would do them good.

We next had a meeting with Friends of Twisk by themselves,
in which we were favoured with the savour of truth, the sincere hearted being refreshed,
and the disorderly warned to be more careful.
After taking some refreshment,
we hastened to attend another meeting appointed for us at Abbey Kirk in the afternoon,
which was held in the house where I felt the opposition before mentioned.
I soon was sensible of some matter in my mind to divide to the people;
first to a low afflicted state, and things opened pretty clear,
and were interpreted readily.
But proceeding to the other states, I felt the current obstructed,
and the force of my sentences evaded,
and had a sense that the minds of the Friends of that
house were shut up against what I had to deliver.
I forbore going on, and the interpreter soon began and continued to speak nearly an hour.
When he had done, I felt a great weight on my mind,
and desired him to interpret a few sentences for me; he did not seem very free to do it,
saying, "`Let it be short then.`"
The substance was, "`That I had come in love to see them,
and was in no way prepossessed or informed concerning any person or case among them;
yet found they were shut up against what I had to deliver.
Nevertheless, I could not be easy without letting them know that I did believe,
unless they humbled themselves, and were stripped from that self-righteous wholeness,
wherewith they had clothed themselves,
they never would grow in the life of true religion;
but would be as stumbling blocks to the sincere hearted among them.`"
I went out of the house and returned to our lodging,
not having freedom to stay there longer.
Our interpreter, who tarried with them after we were gone,
told me that they supposed a certain Friend who had been in Holland sometime before,
and spoken very closely to them, had informed me concerning them;
and I thought the interpreter also favoured that sentiment,
which made me not to wonder at the opposition I had felt both in him and them.
I told him, until that time I never knew that the Friend whom they thus judged,
had been there, and that I had never heard of their names, nor the name of the town,
until I came with him, and desired him to give it in charge to a Friend of Twisk,
who was present with us, to let those Friends know from me,
what I then said of my innocency.

Feeling myself now pretty easy respecting that place, we returned towards Amsterdam,
accompanied by two Friends to Hoorn, where no Friends now live,
though formerly there were some, and at times meetings have been held there.
I had thoughts of having one; but being under discouragement,
had almost concluded to proceed on our way; but in walking through the city to the skute,
which was to set off for Amsterdam in a few minutes,
I felt my mind affected with a sense that my great and good Master was near,
and desired with earnest breathings to know his will,
and if he would be pleased to be with me, I was willing to do the same,
as he should require and enable me.
I then felt such a stream of love towards the inhabitants,
that I was convinced there was a visitation to them,
as though the Lord would in his own time gather a people there.
I had not disclosed my mind to any one, although I felt a draught back;
but seeing a young man in the street,
I desired the interpreter to ask him if he thought we could have a meeting in that town,
to which he readily answered that he believed we might, and taking hold of my baggage,
said, if we would please to return to his house,
he would endeavour to procure a place and acquaint the people, which he very punctually,
and with great speed performed.
We met about four o`'clock in the afternoon at the house of Cornelius Olyslager,
and had a good opportunity with a friendly people,
several of whom were reached and tendered by the virtue and savour of truth,
which spread freely; for which the Giver of all good was reverently praised,
who is worthy forever.
The people departed in much love, and we returned to the young man`'s house,
where we were affectionately entertained that night;
we should have been glad to converse with the people,
but could not understand their language,
yet had a sense that they were satisfied with the meeting.

Accompanied by this kind young man, Derrick Meschaert, our landlord, to the trackskute,
we took leave with tears on each side, and arriving at Amsterdam,
sat with Friends that afternoon in their week-day meeting to satisfaction.
We then visited the remainder of Friends`' families in this city,
and were comforted therein, the Lord being pleased to own our labour,
and I pray it may be blessed to them.
On first-day morning we had a large solid meeting, at which were several strangers,
particularly two young men, Italians, who behaved well;
also many of the citizens who had never been at a Friends`' meeting before.

The afternoon meeting was also large,
but some of the lower sort who came to gaze out of curiosity, behaved rudely;
yet it ended better than I expected.
There seemed to be an openness in many to hear
the testimony and principles of truth declared;
but it is a dull way to speak by an imperfect interpreter.

On the 22nd of the eighth month was held what they call their yearly meeting,
which was attended by several not of our Society;
but it has little more than the name of a yearly meeting,
the discipline of truth being much lost.

Feeling some concern still to continue on my mind towards the Friends at Abbey Kirk,
where I was sensible of the opposition before hinted,
I had freedom to write them a letter;
but on considering that the Friend and his wife to whom I wrote were persons of note,
I was fearful that their resentment might hurt some others;
and having a tender concern towards the sincere hearted,
it was with me to prepare the way by writing an
epistle to Friends of the meeting at Twisk,
to which those of Abbey Kirk belong; both which I got a Friend of Amsterdam to translate;
that to the meeting I sent immediately, that it might be read on a first-day,
and directed the other to be sent soon after.

That to Friends at Twisk, was as follows:

[.embedded-content-document.epistle]
--

[.salutation]
Dear Friends,

The honest and sincere hearted amongst you, I salute in gospel love;
and as I believe there is a small remnant who are
desirous to witness the peace of God in your hearts,
and a sure hope of receiving the answer of well done at
the conclusion of your time in this world,
mind the instructions of the Spirit of Christ Jesus in your own hearts,
for it is this which leads into all truth; it shows unto man,
of what sort the thoughts of his heart are,
and it witnesseth against every bad word and action.
The Spirit of Truth hath taught the children of God in all ages;
it was by this spirit that our worthy elders were led from the lo-heres and lo-theres,
which are in the world; and established on the true foundation.

The revelation or teaching of the Spirit of God in their own hearts,
upheld them under sore afflictions and outward sufferings from the powers of the earth;
and by this they were preserved in the unity of the spirit, in the bond of peace.

Dear Friends, beware of letting out your minds after the doctrines and teachings of men,
who have not the Word of life committed to them to preach in the love and power of truth.
For if ye do, ye will be unstable and wavering,
and a wavering man is as a wave of the sea,
tossed to and fro with every contrary wind of doctrine.
Neither look you too much to the example one of another,
but wait to receive in yourselves a sense of what ye ought to do and to join with,
and what ye ought to be separated from,
then will you be able to judge what you hear and see;
because you have the Spirit of Truth in your own hearts; for that is the true rule,
judge and guide, which leads into all truth.

Since I was with you, I have often thought that you will never grow strong in the truth,
nor teach the principles thereof one to another,
until you be obedient to its teachings in your own hearts,
and act and behave in all things according to
the pure witness thereof in your own selves;
this makes living, sound, steady members,
zealous both of love and good works in themselves,
and amongst their brethren and sisters.

Dear Friends, be careful to meet together,
and admonish those who fall short of their duty herein.
And when you are assembled, wait on the Lord with a mind turned inward;
and if ye wait in faith and patience, the Lord will be found of you,
and reveal himself in the midst of you, to your comfort and consolation.

With sincere desires that every good thought and secret
inquiry after the knowledge of God in each of your hearts,
may be strengthened and blessed, I remain your affectionate friend,

[.signed-section-signature]
John Churchman.

[.signed-section-context-close]
Amsterdam, 23rd of the eighth month, 1753.

--

A copy of my letter to the Friend and his wife, here follows:

[.embedded-content-document.letter]
--

[.salutation]
My friends,

I have had an exercise on my mind ever since I came first into your house,
to visit your family, which was on the 11th instant.

I came an entire stranger, free from any information from man concerning you;
but as soon as I came into the house,
I felt the innocent life of truth and pure seed of the kingdom oppressed in you.

Our dear Lord said, "`Learn of me, for I am meek and low of heart.`"
His spirit in us, if we take heed thereto, will teach us to be meek and low in heart.
At this day his teaching is the same,
and will remain to be so to all his followers forever.
Oh may you be humble, for it is the humble that the Lord teaches of his ways;
and the meek he guides in judgment.
But from the whole and self-righteous, who are wise in their own eyes,
and prudent in their own conceit, the Lord will hide the mysteries of his pure wisdom.

To the babes who are truly changed and born from above,
and those sucklings who are weaned from the breasts of the world and its wisdom,
and are leaning on the breast of Christ their beloved,
desiring the sincere milk of his word, that they may grow thereby,
the Lord will reveal true knowledge and wisdom from above.
This wisdom is pure, peaceable, gentle, and.
easy to be entreated, and those who have the same in possession,
have the seasoning virtue of truth; they have salt in themselves,
and are therefore preserved in peace and unity with the pure truth,
and also one with another.
Such professors who know and receive the most holy faith,
they know the same to work in them by love, to the purifying of their hearts.
These are Jews inward, circumcised in heart, true Israelites indeed,
in whom there is no guile;
and their righteousness exceeds that of the scribes and pharisees.

I heartily wish that you may, in your old age,
be concerned to know the life of pure religion;
a sense of the want thereof in your family, burthened my life whilst I was in your house,
which was the reason why I could not be free to eat and drink with you.

In order to discharge myself towards you, have I written these few lines,
desiring that you may examine yourselves, and see if there be not a cause;
and in the love of truth, which leads us to deal plainly one with another,
I remain your real friend and well-wisher,

[.signed-section-signature]
John Churchman.

[.signed-section-context-close]
Amsterdam, 23rd of the eighth month, 1753.

--

We continued with Friends in this city and attended their two meetings on first-day,
and in the evening had an opportunity with several to satisfaction,
for our love rather increased.
Next morning feeling my mind clear of Friends in Holland,
I was easy to return towards England, and accompanied by several to the skute,
we took leave and went to Turgow by water; from thence by wagon to Rotterdam,
in all about forty-two miles.
There are no members of our Society in this city;
we went to see the meeting house and had some thoughts of having a meeting;
but being the time of a great fair, which occasioned a concourse of rude people,
there was no prospect of having one to advantage.

John Vanderwarf, Jr., came with us to Rotterdam, with whom we parted in much love,
early on fourth-day morning, the 29th of the eighth month,
and went on board the same ship which brought us hither;
it having made a voyage to England and back since.
We sailed with a fair wind down the Maese to the Briel, before noon,
when it becoming contrary, we lay at anchor until first-day morning; then proceeding,
we passed over the dangerous sands and to sea,
and arrived at Yarmouth about one o`'clock the next day,
and had a meeting with Friends the same evening.
In this journey to Holland, we travelled by sea and land about five hundred miles.

From Yarmouth we went in a chaise to Norwich, where Friends were rejoiced to see us,
and we were thankful for our safe return;
and being concerned to spend some more time among them in this city,
we visited a few families and attended their monthly meeting,
also their two meetings on first-day, which were dull and heavy;
the minds of the people being too much outward,
I found it my place to recommend silence by example, more than by words,
in both those meetings.

Next day I went to visit Hannah Lucas, a school mistress, who was newly convinced;
she was in a low state of mind, and our visit was to mutual satisfaction,
being comforted together.
At their week-day meeting on third-day,
I had a seasonable time to discharge my mind towards Friends in that city,
in which I was led to deal plainly with them.
They are a loving people to strangers and each other;
but there is a want of weightiness of spirit,
and of a proper care in the exercise of the discipline of the church.

Before going to Holland,
I was several times at the shop of a barber in this city to be shaved.
The second time I was there, I had to wait awhile for my turn, he having no assistant;
and when others were gone out,
he told me he was sorry I had to wait and hoped he should have my custom,
and that if I would come on Saturdays and Wednesdays in the forenoon, I need not wait;
but in the afternoon others came.
I asked him what days of the week those were which he called Saturday and Wednesday?
He seemed to wonder at my ignorance, but knew not how to tell me otherwise.
I said, I do not read in the Scriptures of any days so named.
He replied, that is true.
For what reason then, said I, dost thou call them so?
Because it is a common custom, said he.
Suppose then, said I,
that we lived in a heathen country among infidels who worshipped idols,
should we follow their customs because common?
He replied, by no means.
I then said, if I have understood rightly,
the heathens gave the days of the week those names.
I never heard that before, said he, pray for what reason?
I answered, they worshipped the sun on the first-day of the week,
and named it after their idol, sunday; the moon on the second-day of the week,
so came monday; and the other days after other idols, for they had many gods;
third-day they called tuesday, after their idol tuisco; and after the idol woden,
they called fourth-day Wednesday; and fifth-day after their idol thor,
they called thursday; from friga, friday; and after saturn they called the seventh-day,
Saturday.
As I believe in the only true God and Jesus Christ whom he hath sent,
and expect eternal life by no other name or power, I dare not, for conscience sake,
own the gods of the heathen, or name a day after them;
but choose the names which the days were called by,
when the Most High performed his work of creation, viz: first, second, third, and so on,
which is Scriptural, most plain and easily understood.

He seemed affected with the information,
and I desired him to inquire into the matter for himself,
and not to think I designed to impose upon him.
The next time of my going to his shop,
he showed me some papers whereon he had began to learn algebra,
and asked me how I liked it.
I said it might be useful to some,
but that I could take up grubbing or follow the plough without studying algebra,
as he might also shave a man, etc., without it;
besides I found it a more profitable and delightful study to
be quietly employed in learning the law of the Lord,
written in my own heart, that I might walk before him acceptably.

On my return from Holland to Norwich, a man ran to me in the street,
putting a paper into my hand, and immediately left me,
whom I soon found to be this barber.
The letter contained an innocent childlike acknowledgment to me for my freedom with him,
as is before mentioned,
in language rather too much showing his value for me as an instrument;
and believing him to be reached by the love of truth, and in measure convinced thereof,
I thought it best to leave him in the Lord`'s hand for further instruction,
to learn by the immediate teachings of the holy Spirit,
that his love might be centred on the true Beloved of souls;
for want whereof many are hurt, looking outward and growing in head knowledge,
seeking the esteem and friendship of man, from whom we are to cease,
his breath and life being stopped at the Lord`'s command.

I mention this passage with a view to stir up my friends of the same holy profession,
to let their language be the language of truth to all men, in purity of spirit,
and not to name the days of the week or months, after the heathenish idolatrous customs;
saying for excuse, that they to whom they speak best understand them,
and that it saves further explanation,
which excuse is far from a disposition apt to teach,
and letting the light of truth shine as they ought.
"`Neither do men,`" said our blessed Instructor,
"`light a candle and put it under a bushel; but on a candlestick,
and it giveth light to all that are in the house.`"
Nor doth the Lord enlighten his candle, that is the spirit of man,
with the pure knowledge of truth, that we should cover it,
either with an easeful disposition to save ourselves trouble,
or hide the work thereof under the bushel of worldly saving care,
after the gain and treasure of this world; but that it may stand on the candlestick,
and thereby crown those who are thus favoured with the holy light,
that as a city set on an hill they cannot be hid.

The corrupt language of you to a single person,
and calling the months and days by heathen names,
are esteemed by some to be little things;
but if a faithful testimony in these little things,
was blessed in the instance before mentioned,
even to the raising an earnest inquiry after the
saving knowledge of God and his blessed Son,
whom to know is eternal life;
perhaps such who baulk their testimony to the
pure talent of truth given them to profit withal,
may one day have their portion appointed with the wicked and slothful servant.

After the last mentioned meeting I found my mind easy to leave Norwich,
and went with Richard Brewster and wife to Wymondam that evening,
and next day to Edmondsbury.
Feeling an engagement of mind, we staid at this place eight days,
attending their several meetings and monthly meeting,
which is composed of five particular meetings; where,
under a sense of a forward formal ministry, my soul mourned and was clothed with sorrow.

Next day we had a precious meeting,
and the same evening another with the ministers and solid Friends;
in which it became my concern to set forth the
care they ought to exercise over each other,
and how necessary it was to deal plainly with those who did not keep their places:
truth owned us together, and I believe the opportunity will be remembered.

My mind being drawn towards Wales, my companion, John Pemberton,
who had been with me three years, having travelled together in much love and unity,
inclining to go towards London, we parted in the same love.
Accompanied by my kind friend, Richard Brewster, I went to Henry Gray`'s,
at Godmanchester, in Huntingdonshire, and the next day to Wellingborough,
in Northamptonshire, and was at their meetings on first-day, the 23rd of the ninth month,
which were heavy, for want of more faithful inward labourers;
that evening I also had a sitting with a sick Friend.

Next morning several Friends coming to take leave of me,
I had an opportunity to remark to them the reason that
their meetings were so dull and cloudy;
for I thought I clearly saw there was a neglect
among them of putting the discipline in practice,
where disorders were evident; and that this neglect had caused them to suffer,
which would still continue and increase,
until they set the testimony of truth over the heads of such who by disorderly walking,
had brought a reproach thereon.
The Friends were affected, and acknowledged they believed it to be the case amongst them.
We parted in tenderness, and I proceeded on my journey with the income of solid peace,
and after riding thirty-seven miles, reached Banbury, in Oxfordshire,
and the next day Eatington, in Warwickshire, where I met with my friends,
Richard Partridge and Mary Weston, of London, and we were truly glad to see each other,
spending the day together,
and had a meeting with Friends in the evening to our mutual comfort.

We went in company to Warwick and Coventry, and at the meeting at the last place,
which was comfortable,
I thought I sensibly felt the benefit of the painful
labour I had been exercised in when there before.
Richard Partridge returning to London,
Mary Weston went with me to the quarterly meeting at Leicester,
which began with a meeting of ministers and elders,
and one for worship and discipline was held the same day;
the service in which lay heavy upon me, and truth favoured,
the power thereof being felt to the comfort of many.
I wish that season may not be forgotten by the members of that meeting.
On the first-day following I went to a general meeting at Badgeley,
and had an evening meeting at Polesworth.
I next went to Allen England`'s, at Tamworth,
and had a satisfactory opportunity in his family,
to which I had felt a drawing in my mind for some time;
but did not know that it would fall in the way to the quarterly meeting at Stafford;
which I attended, and there met my friend Joshua Toft.
In company with him I returned to Ridgeley,
and next day had a meeting at the widow Morris`'s, and another that evening at Uttoxeter;
from thence to Leek, and after a favoured meeting went home with Joshua to Hargate,
where after resting one day, had another meeting at Leek,
and an opportunity with some Friends at Joshua Strangman`'s, I had a degree of peace.

Accompanied by Joshua Toft I went to a general meeting at Eaton, in Cheshire,
then to Macclesfield, Stockport, Morley and Farnly, the last of which was a good meeting.
Here my friend, Samuel Fothergill met me, and we went to a meeting at Sutton;
the next day Susanna Fothergill and her brother Alexander came to see me,
and we had a comfortable time together at Thomas Hough`'s, being owned by truth.
I was next at a laborious meeting at Newton, though it ended well;
next day at Middlewich, then at Nantwich and Chester,
from whence I rode to John Bellows`', at Stretton.
My labours through Cheshire were in a particularly close manner,
though there are some solid Friends in that county.

Passing to Shrewsbury in Shropshire, I was at a meeting on first-day at Colebrookdale,
and had some close work; but truth seemed to give the victory,
and in the evening at Abraham Darby`'s house had an opportunity,
in which the testimony of truth prevailed to the
tendering some high and lofty young people;
whose faults were told them in the power of the Searcher of hearts,
for which the sincere were truly thankful.

Next day returning to Shrewsbury, I went to visit Benjamin Thomas and Richard Bellows,
who had been confined in prison about four years and a
half for their conscientious refusal to pay tithes,
and we had a comfortable season together in the jail,
feeling the living presence of the Lord, which makes his people free, even in prisons.

The day following had a meeting in this town,
and one in the evening at the house of John Young, both which afforded some peace;
but the life of truth is at a low state in Shropshire,
and the professors with us few in number.

I then passed into North Wales, to Charles Lloyd`'s, at Dolobran, in Montgomeryshire,
John Young being with me, and had a meeting there.
At this place there was formerly a large meeting; but it is now much declined.

From thence we went to Tydynygarrig, in Merrionethshire,
and had a meeting with a few sincere Friends at the house of Lewis Owen;
after which I proceeded on my visit to the other meetings in this county;
first in the family of Humphrey Owen, which was a comfortable time,
though no other Friends live in this place; then at the house of John Goodwin,
in Esgingoch, in Montgomeryshire, where were several tender Friends;
but the living are scarcely able to bear the weight of those professors,
who although they know the truth, do not abide therein,
and so are as withered branches cast forth.
Next was a pretty large and satisfactory meeting at Talcoyd, in Radnorshire;
then at Cwm and Gluerindrew, and on a first-day at Penbank, where are many professors,
though but few solid Friends.

After these I was at Penplace and Caermarthen,
which last meeting was much to my satisfaction;
the few Friends here being of the better sort.
Thence to Haverfordwest, staying their meetings on first-day,
which were mostly with Friends by themselves; the afternoon was open and satisfactory,
as to others professors who came in;
but pride and worldly mindedness have much hurt the members of our Society,
though there are a few tender Friends.
In the evening I had another opportunity with Friends,
and was enabled to relieve my mind among them with a degree of thankfulness.
The next meeting was at Jamestown,
and in the evening of the day following at Larn with the people of the town,
who behaved civilly, but seemed barren as to true religion;
there was but one in this town in unity with Friends, and he seemed near his end.
Crossing a ferry nearly a mile broad, we were in great danger,
being driven on shore and the wind very high, the boat was likely to fill with water,
and I was obliged to go over a marsh to Caermarthen, being thankful for the deliverance.
I had a public meeting with the town`'s people, to a good degree of satisfaction,
and next morning met with my brother, William Brown, at Swanzey,
and we were made joyful in the company of each other.
Here we had two meetings, and another with Friends selected, in which he got some relief.
He left me here, and having a concern on my mind I visited the families of Friends,
though not without fear; but felt the help and strength of my great and good Master,
who furnished me with power and skill to discharge my duty,
both to the lukewarm and the corrupt disorderly professors,
without wounding his own children, some of whom there are in this town.
I staid their meeting on fourth-day, which being divinely favoured,
I pray may not be forgotten;
the power which alone can enable to tread on scorpions or serpents,
and preserve from the force of deadly poison, was over all: the honour, praise and glory,
be ascribed to the Lord, who is worthy for ever!

Next day I rested, and in a degree of humble thankfulness made these remarks.

I continued many days longer in this town, in which time I had several meetings,
some of which were very satisfactory, many of the town`'s people attending,
and the good hand of the Lord was stretched forth towards them;
for which I was truly thankful.
After spending sixteen days among them, I went to Llantrishon,
and the next day had a meeting at Trewaruge;
then one at Hillary with a tender inquiring people;
also at Cardiff with a seeking people,
who had separated themselves from the public worship and met together in silence;
this opportunity was an instructive season.
On the first-day following I was at Pontypool at two meetings,
and had many close things to deliver, observing a want of order among them.
In the evening had an opportunity with some of the Friends most active in the discipline,
and endeavoured to discharge myself; and on third-day a large and pretty open meeting.
Being detained by a great snow,
I had another meeting with Friends of the foremost rank on sixth-day,
in which I cleared my mind of a great burden I had borne,
on account of a formal ministry among them.
My next meeting was at Shere Newton, which was pretty large, though dull,
the savour of truth being much lost among Friends here;
yet I was favoured with strength to discharge myself,
and in the feeling of peace went that night to the passage over the Severn,
and next day to Bristol.

On third-day I attended their meeting in Bristol, but sat in silence,
and was very heavy hearted under a sense of a forward spirit,
which would prompt to answer the expectations of the people,
and is apt to prevail on some who seem to be called to the work of the ministry;
but truth only blesseth its own motion.

I continued in and near this city about four weeks, attending their several meetings,
but did not feel relief from the burden I was under.
On the 15th of the first month, 1754, hearing that my brother, William Brown,
was at Ann Young`'s, at Erthcot, I went there to see him,
and we were comforted in each other`'s company,
and next day attended their meeting to our refreshment;
from whence we returned together to Bristol,
where we tarried until the 26th. In this time I had several open meetings,
which set me at liberty to leave that city, when we again parted,
and I took meetings at Ulverstone, Thornbury, Sadsbury, Dedmartin,
Tedbury and at Nailsworth, when I had an opportunity to ease my mind,
which was heavily oppressed on account of the formal professors of truth,
also to the comfort of the faithful, which was cause of thankfulness.

Calling to visit the widow Fowler who was in affliction,
I went to meetings at Plainswick, Gloucester, Ross in Herefordshire, Almerly, Leominster,
and Upham;
where I visited the wives of the two Friends who are
imprisoned at Shrewsbury for their testimony against tithes.
Returning to Leominster, I attended the monthly meeting there, in which truth owned us,
and taking a meeting at Broomsgrove went to Worcester,
and on first-day was at two comfortable meetings, and another on third-day,
and the next day attended the quarterly meeting, which was a precious time,
wherein Friends were comforted.
Finding a concern on my mind I went into the women`'s meeting,
wherein the power of truth accompanied, which is the crown of our religious meetings;
here is a tender seed, which will thrive if the Divine power is kept unto.

Being clear of this city, I departed with peace to meetings at Tewksbury, Cheltenham,
and again to Nailsworth, where I was at two meetings, in which though hard,
I had an evidence that the Lord had not forsaken his seeking people.
After attending a conference with several Friends endeavouring to compose a difference,
which ended to satisfaction, I proceeded to the quarterly meeting for Gloucestershire,
held at Tedbury.
Divine goodness and a good degree of the authority of
truth attending in the time of worship,
and in transacting the affairs of the church.

Next day I went to Cirencester, where I had a hard and dull meeting,
the professors of truth having too much departed from the savour thereof;
at another in the evening I had an evidence of having discharged my duty.
Then proceeded to meetings at Farringdon in Berkshire, Litchfield,
Burford in Oxfordshire, Milton, Stow in Gloucestershire, Chipping, Norton, Charlbury,
Witney, Abingdon, Warbury, North End, and from thence to High Wiccomb,
where the weather being very cold I tarried six days,
visiting several families of sick Friends,
and the last public meeting being in the evening,
which many of the town`'s people attended, and it was a solid opportunity.
From thence I went to Amersham, though with difficulty on account of the snow,
and on first-day had a meeting at Chesham; then to Hampstead, and had a meeting,
which was much enlarged by the scholars of William Squire`'s school,
several of whom were affected.

After a good opportunity with Friends at Albans, I went to London,
where I remained seven weeks and three days, visiting the meetings,
and felt much of the weight and burden of the service before me there,
and in the opening and authority of truth,
I had to speak to the present state of our Society,
not only to the instruction of the seeking children and comforting of the mourners;
but also by way of rebuke to the disorderly, and close warning to the rebellious.

During my continuance here I felt my mind drawn towards Wiltshire,
and thought of attending the quarterly meeting there;
but on the day I expected to set forward, found a stop in my mind;
though not relieved from a solid concern,
which engaged me to inquire secretly what I should do.
Notwithstanding this concern to Wiltshire,
my burden respecting London seemed rather to increase; but as I kept quiet,
I found my heart warmed in love and my mind opened,
to write an Epistle to that quarterly meeting,
which with thankfulness I esteemed a great favour from my good Master,
being in a poor state of health, the weather unfavourable, and the journey long.
In the opening of truth, I wrote as followeth.

[.embedded-content-document.epistle]
--

[.letter-heading]
To Friends in Wiltshire.

Having had strong desires in my mind for your welfare in the truth,
I purposed to attend your quarterly meeting, but being let at this time,
and not knowing that I shall ever have an opportunity to see you,
I feel a freedom to visit you with a few lines in the opening and love of truth,
which flows to you ward.

Dear friends, old and young,
as many of you as are desirous to be called the
children of God and followers of Christ Jesus,
be humble, that you may be taught of him; for it is the humble he teaches of his ways;
and be ye meek and low in heart,
that you may serve him in your generation and one another in his pure fear,
so you will know him for your rest, and his peace your quiet habitation.

My soul hath mourned, and is in some degree covered therewith at this time,
under a sense that the love of the world, and its pleasures and delights,
abound in too many, which are iniquity,
and because thereof the love of many towards God waxeth cold.
For want of witnessing the love of God in a pure heart, the mind becomes lukewarm,
and indifferent about the things which belong to our peace and future happiness;
and so fathers and mothers, masters and mistresses, become dull,
if not dead to that holy concern, which should excite them, both by example and precept,
to instruct and train up their children and
servants in godliness of life and conversation.

Oh dear friends! search your hearts,
and diligently inquire whether something hath not subtilly
crept in and stolen away your affections from God;
and the deep attention of your minds from the instructions of his holy Spirit of truth.
If this becomes your concern,
I fully believe the Lord will bless you with enlightened minds to see,
and willing hearts to give up all to the fire and sword of his Word and Spirit,
that your hearts may be purged, and made temples in which he would take delight to dwell.
If the soul is chaste in love to God,
and the eye of the mind single to the instruction of the Spirit of Truth,
the whole body will be full of light.
It is here that the children of God are preserved safe in their steps before the Lord,
and free from giving occasion of stumbling to others.

I am fully persuaded there is a remnant amongst you, who feelingly know,
that the living sense of the presence and power of God,
in your meetings both for worship and discipline, is not plentifully enjoyed,
but is at a low ebb.
And it is in my mind to let you know what has
appeared to me to be one great reason of it,
viz. There are many professors of the truth amongst you,
who delight to be accounted Friends in esteem in the Society;
who have a smooth and fawning behaviour, and flattering tongues,
and do seek the love and friendship of such as are Friends of truth,
for their own honour and credit, and the reputation of self.
Dear friends of such beware, for their friendship is poison,
and their intimate fellowship, if cleaved unto, is benumbing, even to insensibility.
And for want of a clear discovery of that spirit,
some of the tender and sincere hearted amongst you have suffered.

In whomsoever earthly mindedness prevails, or the love of the world and its friendship;
there is a secret giving way to, and a gradual reconciliation with its sordid practices;
and the eye that once saw in the true light, becomes closed or dimmed,
if not wholly blinded by the god of this world.

Liberty is then taken by parents, and indulgence is given to their children;
which occasion pain and distress of heart to
those who have not lost their sight and feeling.
But some, for fear of being rebuked and disesteemed by such who have a sense of them,
will court their affections; with which bait they have been taken,
and so have been afraid to speak their minds plainly, lest they should offend,
or drive them further from the Society; concluding there is a tender thing in them,
because they seem to love Friends.
Thus many who might have made great progress have lost ground,
for want of speaking truth to their neighbours; and the infection of pride, libertinism,
and earthly mindedness has spread and prevailed,
even to the hurt of some families who were once exceedingly grieved therewith.

Wherefore my dear friends, fear God with a perfect heart,
and in his light watch over your own selves and your families.
So shall your hearts be warmly influenced and filled
with holy zeal and love to God and his truth;
in which you will be bold to act in your meetings for discipline,
and in the power of God, which is the authority of the church,
you will be able to judge those who walk disorderly; and being faithful therein,
you will remove the stumbling blocks,
and roll away the reproach which is imputed to the church.

The Lord would feed these faithful labourers with his heavenly bread,
and honour them with his life giving presence,
and whether the disorderly would hear or forbear,
the Lord would be the shield and exceeding great reward of his people,
and fill their hearts with praise to his name, who is worthy forever and ever.

[.signed-section-signature]
John Churchman.

[.signed-section-context-close]
London, 4th of the Fourth month, 1754.

[.postscript]
Let this be read in your men`'s and women`'s meetings.

--

In my travelling to the meetings in Wiltshire,
and attending the quarterly meeting in the seventh month, 1750,
I was straitened to clear myself towards them,
which occasioned me to leave them in pain of mind,
but now having sent them this epistle I was made easy, believing they would read it,
and send copies thereof to their several monthly meetings,
which would be likely to be heard by more Friends than if my
concern had been delivered in the quarterly meeting only.
Enclosing it to an innocent Friend at Chippenham,
I desired him to deliver it to the said meeting, which I afterwards understood he did,
and that Friends had answered my request.

Feeling my mind easy to leave London for a while, I went to Esher, in Surry;
was the next day at a large meeting at Kingston, on Thames,
which was pretty open as to doctrine, and the people seemed attentive,
and several much tendered; there are but few Friends here.

I then visited other meetings in Hampshire and Berkshire,
being made thankful to the great Author of all good,
who had been with me in the journey under my indisposition of body.
Coming to London I met with many Friends from different parts of the nation,
assembled in order to attend the yearly meeting,
which began on the 2nd day of the sixth month, and continued ten days,
being a very large and in the main a solid meeting.
Many weighty affairs relating to our religious Society were therein considered,
and it was agreed,
that in future this meeting should begin with a meeting of ministers and elders,
on the seventh-day of the week, at the third hour in the afternoon,
that inquiry might be made into the state of the ministry in general,
which I hope may be attended with good service hereafter.

On the 11th of the sixth month after the parting meeting,
I went from London and attended a yearly meeting in Hertford, which was very large.
The next day I accompanied several Friends who were appointed to visit a monthly meeting,
the members of which paid tithes and contended for liberty so to do without censure.
We had a conference with them, in which the testimony of truth was set over them,
and they were taken and confounded in their own arguments.
After this I attended a general or yearly meeting at Baldock,
which was very large and satisfactory, returning next morning to London.
I was truly thankful that I had been enabled to attend these three meetings,
enjoying great peace in my labours there, which lay heavy upon me;
my gracious and good Master gave me wisdom,
boldness and strength to clear myself in the love and power of truth,
to the tendering of many hearts; may I ever remember his mercies to me,
and be enabled to bless and praise his holy name, who is worthy for ever!
Continuing in and near London about ten days,
I then went to a large satisfactory meeting at Rochester, in Kent,
where were several clergymen, who behaved well.
Next day had a meeting at Loos, in the house of Thomas Crisp,
with a few Friends and others; then going to my friend William Patterson`'s,
at Canterbury, I was at their meeting in that town,
and the day following had one on the isle of Thanet,
where there are a few friendly people.
The meeting next day at Dover was pretty open;
on first-day I was at two meetings at Folkstone, which were dull and heavy,
though there are many Friends in that place,
amongst whom I was favoured with strength to ease my mind.

I then visited a number of meetings and came to Chichester,
when finding a concern to visit the families of Friends in this city,
I spent two days in the service and had some close exercise,
though a good degree of peace.
I also attended their two meetings on first-day, which were heavy and laborious;
for though here are some tender people,
yet the spirit of the world has brought a blast on several professors.

I went to Gosport, in Hampshire, where we had a meeting;
also one in the evening at Portsmouth, John Griffith and Jeremiah Waring being with me;
then going to Cowes, on the isle of Wight, had a good meeting at Newport,
likewise one in the evening with the town`'s people.
After another opportunity with Friends, returned to Cowes,
where I had a meeting with a few of our brethren,
and on first-day the 21st of the seventh month, attended two meetings at Pool,
in Dorsetshire, which were dull and laborious;
a worldly libertine spirit has brought a blast on many.
Next day we had a meeting with a few Friends at Weymouth, and then at Bridport;
truth seems at a low ebb in Dorsetshire.

The next meeting was at Ringwood, in Hampshire, which was dull;
where the life of truth is not abode in, people will wither.
The same evening we had a meeting to pretty good satisfaction at Fordingbridge,
and one at Alton; at which place we had another very satisfactory meeting on first-day,
and that evening at Godalming; and taking a few others,
I came to London for the last time, and spent eight days more with Friends in that city.
On my coming here from Albans, on the 19th of the third month before mentioned,
I felt great fear to possess my mind,
having before spent about thirteen weeks in that city,
mostly under a close exercise of spirit,
without an openness to say much in public or private to obtain relief;
so that to go thither again appeared to me like entering into a cloud,
although I was secretly bound in spirit to proceed.
But attending all the meetings as they came in course,
I felt a gradual openness and strength to declare those things,
which before had been sealed up, being now made sensible that every opening or vision,
which the Lord is pleased to manifest to his servants, is not for immediate utterance.
The Lord who gives judgment, should be carefully waited upon, who only can show,
by the manifestation of his heavenly light, the time when,
and by the gentle putting forth of his arm of power,
give ability in the opening of his spirit,
which giveth tongue and utterance to speak the word of
truth in the demonstration of the spirit and power,
that openeth a door of entrance in the hearts of them who hear.
Our dear Lord said,
"`For it is not ye that speak; but the Spirit of your Father, which speaketh in you.`"

As my service opened and strength increased, I was invited by some to their houses,
who before looked on me with indifference;
but now said they should be glad to see me there to be more acquainted.
I felt on my first arrival in this city,
a secret prohibition from going much from house to house without inward leave,
and the same restraint continued with me,
lest by going to such places I might somewhat contradict, by example,
the precepts which truth had directed me to deliver in public, to wit:
a life of self-denial and temperance in eating and drinking,
with a steady inward attention to the teachings of the Spirit of grace,
in order to know an establishment of heart thereby,
as being the certain duty of every follower of Christ Jesus our Lord.
I think I have seen that there is great need to be exceedingly careful,
when the Lord is pleased to reach unto and
convict disorderly walkers by instrumental means,
that we do not lessen the weight of Divine reproof, by being familiar with such,
as if all was well;
for they are apt to be fond of the instrument through whom they have been reached;
and if by their fondling, they gain the esteem of such a Friend,
it seems to heal them before their wounds are searched to the bottom;
so that I rather chose retirement, and to live as privately as I well could.
I also saw, that if I had sought many acquaintance,
and thereby beheld the conduct and behaviour of some in their families,
my way would not have been so open as it now was.

In many meetings the love and power of truth was felt by the humble dependent children,
whose eyes were fixed on their heavenly Helper, and at some of the last in London,
I had with an innocent boldness to appeal to Friends to bear witness
of the manner in which I had spent my time in that city;
that I had not sought to be popular, nor endeavoured to gain the praise of any,
or the friendship of those who were not the real Friends of truth,
keeping in a good degree under the innocency and simplicity thereof.
Though with a near affection I felt my spirit united to
the children of the heavenly family amongst them;
I had never sought to steal their love from the great Parent to whom they did belong;
my prayer and heart`'s desire having been, that their abode might be in the truth,
and their affections placed on God,
and the whole delight of their hearts to meditate in his holy law.
If through me as an instrument they had received any benefit,
the praise belonged to the Lord, the only Supreme good;
and if in future they did but love, fear and serve him,
it was little to me whether they remembered that I had been amongst them.
Nevertheless a participation of the love of God by the members of the true church,
has taught them to know the communion of saints
and the deeply engraven unity of the one spirit,
which makes them as epistles written in one another`'s hearts,
which time or distance can never erase.

Having spent first and last in London about twenty-three weeks,
on the 9th day of the eighth month and sixth of the week,
after a solid meeting at Grace-church street,
I felt myself at liberty to set my face homewards.
The ship in which I came over, and the same captain, Stephen Mesnard,
being now ready to go for Philadelphia, I went that night to Gravesend,
accompanied by about twelve Friends.
Next morning we went on board the ship, where we had a precious uniting time,
and then returned on shore to dine; after which my friend, Samuel Fothergill and myself,
taking leave of our friends,
went on board again and passed down the Thames to Margaret bay, near the isle of Thanet.
On first-day, the 11th, we went to the Downs, by Deal,
and though very much indisposed in body, I enjoyed such quietude of mind,
that I was borne up and preserved from repining.

Samuel Fothergill, before mentioned,
came over with me on a religious visit to Friends in America; and during our passage,
great nearness was between us;
we held meetings constantly on the first and fifth days of the week,
and landed near Wilmington, in New Castle county, on Delaware,
on the 24th of the ninth month, 1754, in the forenoon.
My brother, William Brown, with our friend Joshua Dixon, from the county of Durham,
in Great Britain,
who was coming over also on a religious visit to Friends in these colonies,
having embarked in another ship, which sailed some time before us,
arrived on the same day,
and quite unexpectedly to each other we met in
this town to our mutual joy and satisfaction;
from whence after dining, they with Samuel Fothergill, proceeded up to Philadelphia,
and I went home that evening, where I found a kind reception.
In this visit I was absent from home four years and twelve days,
having travelled by land about nine thousand one hundred miles,
and attended about one thousand meetings, besides those in London and Dublin,
in which cities I spent nearly half a year,
and visited all the families of Friends in North and South Holland.
