== Chapter VIII.

[.chapter-synopsis]
* His attendance of the western quarterly meeting in the second month, 1773
* The spring meeting in Philadelphia, and the general meeting at Duck Creek
* The quarterly meeting at Shrewsbury
* With several other meetings in New Jersey
* The spring meeting in Philadelphia, in 1774
* His last visit to New York and Long island
* His last attendance of the yearly meeting in Philadelphia
* His being at the spring meeting there in 1775, and his last journey to meetings on the Eastern shore of Maryland
* His last illness with some weighty expressions in that time
* His death and burial.

Being somewhat recovered of my indisposition,
I sat in our select meeting of ministers and elders on the 1st of the second month, 1773,
in which I was comforted under a sense of our being
owned in some degree by the visitation of Divine love;
and afterwards attended our quarterly meeting at London-grove,
each sitting whereof was favoured with the continuance of heavenly help,
to the encouragement of the humble waiters.
I returned home with thankfulness to the Lord,
who had furnished me with strength in my weak state to sit with my friends,
in which we ought to be good examples.
I attended our own meeting on the fifth and first-days following,
in the same week went to Wilmington, to the burial of Deborah Ferris, before mentioned;
after which a solid and profitable meeting was held.

On the 26th of the third month I set out from home in order to
attend our general spring meeting at Philadelphia,
but did not get there in time for the first sitting ; such of them as I did attend,
I thought were in the main, times of Divine favour.
On my return homeward I was at a small meeting at Chester,
also the general meeting at Wilmington, and soon after the general meeting at Duck creek,
and their monthly meeting preceding it.
The meeting there on first-day was large, and though a mixed multitude attended,
it was solid, through the overshadowing of heavenly power;
the Lord was pleased to open the mysteries of the kingdom,
influencing my heart to preach the gospel in the love thereof to my humble admiration,
and many were tendered; for which renewed visitation and favour,
a sacrifice of thanksgiving ascended from the hearts of his children,
to the all powerful and merciful God who is worthy for ever.
The meeting on second-day was a time of consolation to the heavy hearted,
instruction to the humble seekers, and a season of strengthening to the weak;
blessed be the name of the Lord, for his mercies endure for ever.
I was next at George`'s creek meeting,
in which Friends were encouraged and in some degree refreshed,
divers not of our Society attending;
the doctrine of personal election and reprobation as held by some, was refuted,
and it was clearly pointed out wherein the election stood, viz: in Christ, the seed,
which being cleaved unto, and chosen by man for his true instructer and leader,
by his light and witness in the heart as a reprover for sin, and so followed and obeyed,
man comes to know himself elected in him.
I went home with George Ford, at Back creek,
and had an opportunity in his family I hope to some profit.

Towards the fall of the year I had a draught in
my mind to attend some meetings in the Jerseys,
particularly the quarterly meeting at Shrewsbury;
of which having acquainted my brethren at home and had their concurrence,
after attending our yearly meeting in Philadelphia and returning from thence,
I set out in company with my friend Samuel England, on the 12th of the tenth month,
but was detained at Philadelphia by a fever, which held me several days.
I so far recovered as to proceed on our journey,
taking on our way meetings at Mount-holly, at a school house near Shreve`'s mount,
in Upper Springfield, in which I had a concern to warn the youth to beware of deism,
and to show the ground and cause of falling into that error; also at Upper Freehold,
and in a Friend`'s house near that called Robbins`'s meeting.
There seems to be a visitation to the youth in that place, to which if they are faithful,
that meeting may again increase.
We reached the meeting of ministers and elders at Shrewsbury,
in which Truth owned the lovers thereof;
the public meetings on the three following days were large,
and thought to be the most quiet and satisfactory which
had been known of late years there;
the affairs of the discipline were, as I thought, pretty well conducted.

Finding myself not clear of the members of our Society at this place,
I proposed to several Friends that they would favour me
so much as to meet on their week-day meeting day,
which I understood they usually had omitted in this week,
requesting that they would acquaint their members with my desire of seeing them,
their children and families together.
I therefore waited until fifth-day, when they generally met,
which gave me an opportunity comfortably to clear myself towards Friends here,
to the encouragement of the sincere;
being led to show the active members the cause of dwarfishness,
the love of the world and its friendships, choking the good seed,
which should grow and bear rule.
I was thankful for this opportunity, and left them with the enjoyment of a quiet mind.

From thence we passed to Rahway, had a meeting at Woodbridge, and another at Plainfield,
in both which Truth owned my service.
I thought there was a tender visitation renewed to Friends in those parts,
in the sense whereof I was thankful,
and that I had been favoured with strength to pay them
a visit in the love of my great and good Master;
may I ever walk answerably to his manifold favours, who is worthy of all praise for ever!
We were next at Stonybrook meeting,
which was made precious in the renewing of Divine favour;
and then at Trenton with a people who have much lost the life and savour of truth.
From thence going to Byberry and Philadelphia,
I reached the quarterly meeting at Concord, which began on the 6th of the eleventh month.
Next day I went to Chichester,
where I was enabled to speak to the states of the people in the love of Truth,
which may be useful if remembered in a right manner;
and returned to the quarterly meeting on second-day, which was comfortable,
the Divine presence being felt.
Our friend Elizabeth Robinson was there, and had good service.
On third-day I attended the general meeting at Chester, which was poor and dull;
the expectations of the people being too much outward, they were disappointed;
then attending the monthly meeting at Wilmington, tarried their meeting the next day,
and proceeded to our quarterly meeting at London-grove,
at which we had the company of our friends Robert Walker,
Elizabeth Robinson and Mary Leaver, from Great Britain;
it was a season of refreshment and comfort to many Friends; then went home,
having travelled in this journey about three hundred and sixty miles.

In the third month, 1774, I attended our general spring meeting in Philadelphia,
the divers sittings whereof were divinely favoured; and after it,
the general meeting at Wilmington, which was held chiefly in silence,
and on that account remarkable.

Having an engagement on my mind for some time to visit Friends on Long island,
with some adjacent meetings, I laid it before my brethren,
who gave me their certificate for that purpose;
and on the 3rd of the fifth month I set out on the journey,
having the company of a Friend from Wilmington.

Taking a meeting at Philadelphia, we reached New-York,
attended their morning and afternoon meetings on first-day,
and had an opportunity with divers Friends in the evening, which was to me instructive,
and I believe through Divine goodness profitable to some others.
We then had meetings at Westchester, Mamaroneck and the Purchase;
the last being a monthly meeting.
These opportunities were close and searching;
the testimony of truth was encouraging to the well-minded,
but very sharp to the formalists,
and my mind was made thankful for the blessing of peace in the discharge of my duty.
We next attended meetings at Flushing, on Long island.
Cowneck, Westbury, Matinicock, Sequitogue and Bethpage, then at Newtown,
the monthly meeting at Westbury, and the quarterly meeting at Flushing,
where the yearly meeting began the next day, which held four days;
and on the whole I believe it may be said,
that the authority of Truth was in some good degree felt to keep down forward spirits,
both in the ministry and discipline,
which was cause of thankfulness to the Lord who rules among his children,
and is worthy of all praise for ever.
Here I had the company of our dear friends, Robert Walker,
Elizabeth Robinson and Susanna Lightfoot, who intending for Rhode Island,
I parted with them, and went to the monthly meeting at New-York,
which through merciful regard was comfortable.

From thence going to Rahway, had a meeting at Plainfield, which was satisfactory,
through the extendings of Divine favour; then at Kingwood on first-day,
from whence crossing Delaware, we were at Buckingham monthly meeting,
where I thought the true spirit of discipline appeared to be much wanting in many;
here my companion returned homewards.
The next day I was at Wright`'stown monthly meeting, which through the Lord`'s blessing,
was edifying to many; and we parted in peace and sweetness of spirit.

The day following I attended the meeting at Pine street, in Philadelphia;
also that at High street, on fifth-day,
which was a precious opportunity to such who loved to live near the Spirit of Truth.
From thence I went to visit my brother-in-law, Daniel Brown, near Chester;
was at Newtown meeting on first-day, and at an afternoon meeting near Amos Yarnall`'s;
then went to the general meetings at Goshen and Uwchland;
after which taking London-grove meeting, I came home,
having rode in this journey about six hundred miles,
and felt a degree of thankfulness that the Lord
was pleased to give me ability to perform it.

I tarried much at home the remaining part of this summer,
and on the 21st of the ninth month,
I set out in order to attend the yearly meeting at Philadelphia,
which was very large in the several sittings, continued a full week,
and I thought it the most solid and weighty in
transacting the affairs of truth that I ever knew.
The testimony thereof against slave keeping was wonderfully exalted,
through the power and love of God, who is worthy of all praise for ever.
In my way home I was at Providence meeting,
in which the testimony of truth went forth by way of
warning to the lukewarm and declining professors,
and of encouragement to the youth.

Our general meeting at Nottingham next day was large, and I hope profitable to some;
after which having a desire to be at the general meeting at Cecil, in Maryland,
I left home on the 7th of the tenth month,
was at the quarterly meeting of ministers and elders there on first-day morning,
which was profitably instructive through Divine goodness.

Two public meetings for worship were held on first and second-days, both large and solid,
several other Friends from Pennsylvania were there;
the business of the quarterly meeting ended on third-day morning;
on the same day we had a comfortable public meeting,
from which we parted with Friends in much love and nearness.
On the following day was their monthly meeting, to attend which several of us staid;
then having a desire to see Friends at Chester river, I went to their weekday meeting,
Nicholas Wain bearing me company; the meeting was large, and through the Lord`'s goodness,
it was, I believe, made profitable to many.
Taking meetings at Sassafras, Duck creek, Motherkill and Little creek,
the two last being their preparative meeting at each place;
the next day was their select meeting of ministers and elders,
and their monthly meeting the day following, which,
with divers other Friends from Pennsylvania, we attended,
and on the first and second-days of the next week, the general meeting at Little creek.
I believe there is a renewed visitation to Friends and some others hereaway;
but formal professors appear to be as stumbling blocks,
by joining with the spirit of the world.
I returned home with an easy mind.

[.asterism]
'''

Weakness and infirmity of body gradually increasing upon our beloved friend,
he frequently mentioned, that many years past,
it was unexpected to him to live to his seventieth year,
and to be favoured with health and strength
sufficient to travel so much as he lately had,
saying, that now he scarcely thought much more would be required of him.
He however attended the western quarterly meeting in the eleventh month, this year,
and in the second month, 1775,
in both which he was favoured with strength and
clearness to speak to the state of the church,
as well in some of the select, as the more public meetings,
tending to the edification and comfort of many.

In the third month, 1775, he also attended the general spring meeting at Philadelphia,
and in some of the sittings thereof was much favoured;
and on his return home from thence he was at Wilmington general meeting,
in company with our friends Robert Walker and Elizabeth Robinson, from Great Britain.

His last journey was on a visit to most of the meetings on the Eastern shore of Maryland,
and to attend the yearly meeting at Third-haven, in Talbot county;
for which purpose he set out from his own habitation on the 22nd of the fifth month,
having, according to his usual care, obtained the concurrence of his brethren,
and was accompanied by a young man, William Jackson,
a member of New-garden monthly meeting,
who has given the following account of this journey:

[quote]
____

"`Our first day`'s ride was to George Ford`'s, near Back creek;
the next morning being damp and foggy, was very trying to his weak constitution,
yet we rode forty-five miles that day to Hannah Turner`'s, in Queen Ann`'s county,
which was thought to be a means of bringing on him a
disorder which proved painful and afflicting,
and increased till near his end.
Being advanced in age, his bodily infirmities appeared great,
but the fervency of his mind for the promotion of truth and righteousness,
and his care as a father in Israel, were truly as prevalent as ever.
On the 24th of the month he went to the preparative meeting at Tuckahoe,
wherein he was concerned to exhort some to faithfulness in times of temptation and trial,
that they might experience an overcoming, and be enabled to strengthen their brethren.

"`Next day we attended Third-haven monthly meeting,
in which he was qualified to speak instructively to the members thereof,
particularly to such who were encumbered with much care about the things of this life;
things, which although lawful in themselves,
yet when suffered to engross the minds and affections of people,
obstruct a progress in religion.
On the 26th, a meeting at Choptank was a time of heavy exercise on account of a lifeless,
lukewarm, indifferent situation of mind, which seemed to attend divers there assembled.
The next day we attended a burial at Third-haven, on which occasion a meeting was held,
and he laboured honestly to arouse those who lived in the neglect of
making timely preparation for their awful and solemn change.

"`On the 28th we were at Tuckahoe meeting, and on second-day at the bay-side,
where were but few of our Society, but several others attended who behaved soberly,
and some of the younger sort were reached and tendered by truth`'s testimony,
to whom he was led instructively to show,
that they need not give their money for that which is not bread,
nor their labour for that which satisfieth not,
and opened to them the way of life and salvation which is attained through the Spirit,
or free gift of grace that is come upon all men for justification,
so that if they attended to the dictates thereof in their own hearts,
it was sufficient to instruct them in the way of godliness; but when people go from,
and neglect this inward teacher, seeking to, or depending on learned men, they err.

"`Next day we had a religious opportunity in the family of John Bartlett,
and on fourth-day went to Tuckahoe meeting again,
where he had to speak of the sufficiency of the grace of God,
and the inconsistency of people`'s living in a
profession thereof without being found in the faith,
or fully believing in this principle as sufficient for salvation.
We next attended the meetings at Third-haven and Marshy creek.
The yearly meeting began on seventh-day,
and continued until the fourth of the following week,
and although he was feeble and unwell, he attended the several sittings thereof,
being nine in the five days, and the last held seven hours.
He was enabled to appear for the cause and testimony of truth,
both in the meetings for worship and discipline;
and like the good scribe well instructed in the things of the kingdom,
had to bring forth out of the treasury, things new and old, profitable and instructive,
being seasoned with the love and virtue of truth.
After the meeting on fourth-day, we went to the house of Joseph Berry,
where next morning we had a religious opportunity in the family,
and the day following a meeting in Queen Ann`'s forest,
from whence we went to Joshua Vansant`'s. Here he was very poorly, having taken some cold;
the next day being very warm, he was much spent with riding, and said,
as he had at several times before on this journey,
'`that he believed it would be his last, if he lived to reach home,
which at times he thought seemed unlikely.`'
On first-day, the 11th of the sixth month,
he had a meeting in a school house at Back creek,
among a people who behaved with much sobriety, which was a satisfactory time,
very instructive and open for doctrine; and that evening reached home,
having travelled in this journey about two hundred and ninety miles.`"
____

On the 14th of the sixth month he went to the week-day meeting at London-grove,
to meet a committee of our quarterly meeting,
and returned to our meeting at Nottingham the next day.
On the first-day of the week following, was there also;
and in the same week he attended our preparative and monthly meetings;
but a fever daily increasing upon him, he was afterwards chiefly confined at home.

On the 4th of the seventh month he expressed himself thus; "`I am glad that I am at home,
I have ever found it best when my service abroad was over,
to get home as quick as might be;
and though I have felt great inward poverty and weakness since my last journey,
so that I can neither see my beginning, nor ending, but seem as if all were hidden,
yet I hope if Providence shall see meet to remove me at this time,
some light will appear again, and that it will be otherwise before I go.`"

At another time he spoke to this purpose;
"`I have found myself much stripped as to a sense of good,
and tried with poverty many days.
I suppose I have been accounted by some, as one of the better sort of people,
but have seen great occasion to beware of a disposition that
would feed upon the praise or commendations of others;
a carnal selfish spirit is very apt to present and creep in here if possible,
and I have seen it hurt many who have had right beginnings;
it always introduceth dimness and oppression, to the pure, precious,
innocent life of truth, which only groweth up into dominion,
through deep abasement of soul and the entire death of self.`"

At several other times he signified to this effect;
"`My present baptism of affliction hath tended to the further refinement of my nature,
and to bring me more perfectly into the image of my Master.`"

He frequently expressed his full submission to the Divine will,
either respecting life or death; several times saying,
"`I now experience my life and my will to be slain, and I have no will left.`"

In the two last weeks of his time it appeared that his desire and hope,
mentioned in the fore part of his illness, for light again to appear,
was fully answered by the fresh influence thereof,
so that although his pain was often great, he would, many times in a day,
break forth into a kind of melody with his voice, without uttering words,
which as he sometimes intimated,
was an involuntary aspiration of his soul in praise to the Lord,
who had again been pleased to shine forth in brightness,
after many days of poverty and deep baptism, which though painful,
had proved beneficial to him,
being a means of further purifying from the dregs of nature; saying,
he was at times afraid to discover that melody in the hearing of some who visited him,
lest they could not comprehend its meaning, and might therefore misconstrue it.

On second-day morning the 17th of the seventh month,
being asked by a Friend how he was, he replied,
"`I am in the body yet, and when I go out of it I hope there is nothing but peace;`"
and soon after said,
"`I have seen that all the bustles and noises that are now in the world,
will end in confusion,
and our young men who know not an establishment
in the truth and the Lord`'s fear for a ballast,
will be caught in a trying moment.`"
At another time he said, "`I feel nothing but peace,
having endeavoured honestly to discharge myself in public, and privately to individuals,
as I apprehended was required; and if it be the Lord`'s will that I should go now,
I shall be released from a great deal of trouble and exercise,
which I believe Friends who are left behind will have to pass through.`"

On the 20th of the same month he thus expressed himself;
"`I love Friends who abide in the truth, as much as ever I did,
and I feel earnest breathings to the Lord,
that there may be those raised up in the church who may go forth in humility,
sweetness and life, clear of all superfluity in expressions and otherwise,
standing for the testimony,
that they may be useful to the church in these difficult times.`"

About three days before his death, several Friends being in his room,
he spoke as follows; "`Friends in the beginning, if they had health and liberty,
were not easily diverted from paying their tribute of worship
to the Almighty on week-days as well as first-days,
but after a while when outward sufferings ceased, life and zeal decaying,
ease and the spirit of the world took place with many,
and thus it became customary for one or two out of a family to attend meetings,
and to leave their children much at home.
Parents also, if worldly concerns were in the way,
could neglect their week-day meetings sometimes; yet be willing to hold the name,
and plead excuse because of a busy time, or the like;
but I believe that such a departure from primitive integrity ever did, and ever will,
occasion a withering from the life of true religion.`"

To a Friend who came to visit him on the 21st of the seventh month, he said,
"`I feel that which lives beyond death and the grave,
which is now an inexpressible comfort to me after a
time of deep baptism that I have passed through;
I believe my being continued here is in the will of Providence,
and I am fully resigned.`"

His illness increasing, he said but little on seventh-day, the 22nd;
in the afternoon he was very low and speechless about twelve hours;
early on first-day morning he recruited a little,
and gave directions about his coffin to a Friend who sat up with him, he being a joiner.
Continuing rather easier the fore part of that day and appearing cheerful,
he expressed divers weighty sentences,
like farewell exhortations to some who came to see him.
On second-day morning he sat up a considerable time,
and in the afternoon he appeared lively and sensible, though very weak,
thus expressing himself; "`I am much refreshed with my Master`'s sweet air,
I feel more life, more light,
more love and sweetness than ever before;`" and often mentioned the Divine
refreshment and comfort he felt flowing like a pure stream to his inward man,
saying to those who were with him,
"`I may tell you of it, but you cannot feel it as I do.`"

In the evening a young person coming into the room,
looking at her earnestly and affectionately, he said,
"`Deborah arose a mother in Israel;`" and shortly after,
"`The sweetness that I feel;`" then his difficulty of breathing increased,
and being turned once or twice, he requested to be helped up,
and was placed in his chair;
in which he expired about the ninth hour on second-day night,
the 24th of the seventh month, 1775, being aged near seventy,
and a minister about forty-two years,
and was buried on the 26th in Friends`' grave yard at East Nottingham,
a large concourse of people attending; after which a solemn meeting was held.
